const words = [
    { en: 'Fast-changing', t: '[fɑːst-ˈʧeɪnʤɪŋ]', ru: 'Быстро меняющийся' },
    {
        en: 'Highly skilled',
        t: '[ˈhaɪli skɪld]',
        ru: 'Высококвалифицированный',
    },
    { en: 'Eligible', t: '[ˈɛlɪʤəbl]', ru: 'Подходящий' },
    { en: 'Vibrant', t: '[ˈvaɪbrənt]', ru: 'Жизнеспособный, яркий, живой' },
    { en: 'Lifelong', t: '[ˈlaɪflɒŋ]', ru: 'Пожизненный' },
    {
        en: 'Fully furnished',
        t: '[ˈfʊli ˈfɜːnɪʃt]',
        ru: 'Полностью обустроенный',
    },
    { en: 'Canonical', t: '[kəˈnɒnɪkəl]', ru: 'Канонический' },
    {
        en: 'Research-based',
        t: '[rɪˈsɜːʧ-beɪst]',
        ru: 'Основанный на исследованиях',
    },
    { en: 'Inspirational', t: '[ˌɪnspəˈreɪʃən(ə)l]', ru: 'Вдохновляющий' },
    { en: 'Holistic', t: '[həˈlɪstɪk]', ru: 'Целостный' },
    { en: 'Empirical', t: '[ɛmˈpɪrɪkəl]', ru: 'Эмпирический' },
    { en: 'Fun-filled', t: '[fʌn-fɪld]', ru: 'Наполненный весельем' },
    {
        en: 'Award-winning',
        t: '[əˈwɔːd-ˈwɪnɪŋ]',
        ru: 'Отмеченный наградой, награжденный',
    },
    { en: 'Rapid', t: '[ˈræpɪd]', ru: 'Быстрый' },
    { en: 'Job-ready', t: '[ʤɒb-ˈrɛdi]', ru: 'Готовый к работе' },
    { en: 'Median', t: '[ˈmiːdiən]', ru: 'Средний, медианный' },
    { en: 'Lucrative', t: '[ˈluːkrətɪv]', ru: 'Выгодный' },
    { en: 'Savvy', t: '[ˈsævi]', ru: 'Проницательный' },
    { en: 'Thoughtful', t: '[θɔːtfʊl]', ru: 'Вдумчивый' },
    { en: 'Elusive', t: '[ɪˈluːsɪv]', ru: 'Неуловимый' },
    { en: 'On-demand', t: '[ɒn-dɪˈmɑːnd]', ru: 'Востребованный' },
    { en: 'Nonexistent', t: '[nɒn ɪgˈzɪstənt]', ru: 'Несуществующий' },
    { en: 'Luxurious', t: '[lʌgˈzjʊərɪəs]', ru: 'Роскошный' },
    { en: 'Entertaining', t: '[ˌɛntəˈteɪnɪŋ]', ru: 'Развлекательный' },
    { en: 'Conscious', t: '[ˈkɒnʃəs]', ru: 'Сознательный' },
    { en: 'Mythological', t: '[ˌmɪθəˈlɒʤɪkəl]', ru: 'Мифологический' },
    { en: 'Prosaic', t: '[prəʊˈzeɪɪk]', ru: 'Прозаический' },
    { en: 'Uplifting', t: '[ʌpˈlɪftɪŋ]', ru: 'Поднимающий настроение' },
    { en: 'Looming', t: '[ˈluːmɪŋ]', ru: 'Надвигающийся' },
    {
        en: 'People-first',
        t: '[ˈpiːpl-fɜːst]',
        ru: 'Ориентированный на человека',
    },
    {
        en: 'User-generated',
        t: '[ˈjuːzə-ˈʤɛnəreɪtɪd]',
        ru: 'Созданный пользователями',
    },
    { en: 'Experimental', t: '[ɛksˌpɛrɪˈmɛntl]', ru: 'Экспериментальный' },
    { en: 'Aesthetic', t: '[iːsˈθɛtɪk]', ru: 'Эстетический' },
    { en: 'Feasible', t: '[ˈfiːzəbl]', ru: 'Осуществимый' },
    { en: 'Foreseeable', t: '[fɔːˈsiːəbl]', ru: 'Предвидимый' },
    {
        en: 'Streamlined',
        t: '[ˈstriːmlaɪnd]',
        ru: 'Оптимизированный, удобный, обтекаемый',
    },
    { en: 'Brand new', t: '[brænd njuː]', ru: 'Инновационный' },
    { en: 'Ephemeral', t: '[ɪˈfɛmərəl]', ru: 'Эфемерный' },
    { en: 'Prevalent', t: '[ˈprɛvələnt]', ru: 'Распространенный' },
    { en: 'Sizable', t: '[ˈsaɪzəbl]', ru: 'Большой' },
    { en: 'Shoppable', t: '[ˈʃɒpəbl]', ru: 'Доступный для покупки' },
    { en: 'Stratospheric', t: '[Strato ˈsfɛrɪk]', ru: 'Стратосферный' },
    { en: 'Major', t: '[ˈmeɪʤə]', ru: 'Крупный, главный' },
    { en: 'Unprecedented', t: '[ʌnˈprɛsɪdəntɪd]', ru: 'Беспрецедентный' },
    { en: 'Exorbitant', t: '[ɪgˈzɔːbɪtənt]', ru: 'Непомерный' },
    { en: 'Artistic', t: '[ɑːˈtɪstɪk]', ru: 'Художественный, творческий' },
    { en: 'Prospective', t: '[prəsˈpɛktɪv', ru: 'Перспективный' },
    { en: 'Like-minded', t: '[ˈlaɪkˈmaɪndɪd]', ru: 'Похожий' },
    {
        en: 'Customer-centric',
        t: '[ˈkʌstəmə-ˈsɛntrɪk]',
        ru: 'Ориентированный на клиента',
    },
    { en: 'Editorial', t: '[ˌɛdɪˈtɔːrɪəl]', ru: 'Редакционный, редакторский' },
    { en: 'Solitary', t: '[ˈsɒlɪtəri]', ru: 'Одиночный, уединенный' },
    { en: 'Controversial', t: '[ˌkɒntrəˈvɜːʃəl]', ru: 'Спорный' },
    { en: 'Shareable', t: '[ˈʃeərəbl]', ru: 'Делимый, разделяемый' },
    { en: 'Journalistic', t: '[ˌʤɜːnəˈlɪstɪk]', ru: 'Журналистский' },
    { en: 'Elegiac', t: '[ˌɛlɪˈʤaɪək]', ru: 'Элегический' },
    { en: 'Short-lived', t: '[ʃɔːt-lɪvd]', ru: 'Недолговечный' },
    { en: 'Authoritative', t: '[ɔːˈθɒrɪtətɪv]', ru: 'Авторитетный' },
    { en: 'Subsequent', t: '[ˈsʌbsɪkwənt]', ru: 'Последующий' },
    { en: 'Unavoidable', t: '[ˌʌnəˈvɔɪdəbl]', ru: 'Неизбежный' },
    { en: 'Disastrous', t: '[dɪˈzɑːstrəs]', ru: 'Катастрофический' },
]

export default words
