const words = [
    {
        en: 'Collaboratively',
        t: '[kəˈlæb(ə)rətɪvli]',
        ru: 'Совместно',
        ua: 'Спільно',
    },
    { en: 'Twofold', t: '[ˈtuːfəʊld]', ru: 'Вдвойне', ua: 'Подвійно' },
    {
        en: 'Backwards',
        t: '[ˈbækwədz]',
        ru: 'Наоборот, назад',
        ua: 'Навпаки, назад',
    },
    { en: 'Alongside', t: '[əˈlɒŋˈsaɪd]', ru: 'Наряду', ua: 'Наряду' },
    {
        en: 'Face-to-face',
        t: '[feɪs-tuː-feɪs]',
        ru: 'Лицом к лицу',
        ua: 'Обличчям до лиця',
    },
    {
        en: 'Increasingly',
        t: '[ɪnˈkriːsɪŋli]',
        ru: 'Все чаще',
        ua: 'Все частіше',
    },
    { en: 'Likewise', t: '[ˈlaɪkwaɪz]', ru: 'Аналогично', ua: 'Аналогічно' },
    {
        en: 'Inherently',
        t: '[ɪnˈhɪərəntli]',
        ru: 'По своей сути',
        ua: 'За своєю суттю',
    },
    {
        en: 'Yearslong',
        t: '[jɪəzlɒŋ]',
        ru: 'В течение года',
        ua: 'Протягом року',
    },
    {
        en: 'Dramatically',
        t: '[drəˈmætɪk(ə)li]',
        ru: 'Значительно',
        ua: 'Значно',
    },
    { en: 'Overall', t: '[ˈəʊvərɔːl]', ru: 'В целом', ua: 'Загалом' },
    { en: 'Sustainably', t: '[səsˈteɪnˈeɪbli]', ru: 'Устойчиво', ua: 'Стійко' },
    { en: 'Thoroughly', t: '[ˈθʌrəli]', ru: 'Тщательно', ua: 'Ретельно' },
    { en: 'Radically', t: '[ˈrædɪkəli]', ru: 'Радикально', ua: 'Радикально' },
    {
        en: 'Undeniably',
        t: '[ˌʌndɪˈnaɪəbli]',
        ru: 'Бесспорно',
        ua: 'Безперечно',
    },
    { en: 'Amongst', t: '[əˈmʌŋst]', ru: 'Среди', ua: 'Серед' },
    {
        en: 'Specifically',
        t: '[spəˈsɪfɪk(ə)li]',
        ru: 'Конкретно',
        ua: 'Конкретно',
    },
    { en: 'Unless', t: '[ənˈlɛs]', ru: 'Если только', ua: 'Якщо тільки' },
    {
        en: 'Seamless',
        t: '[ˈsiːmlɪs]',
        ru: 'Беспрепятственно',
        ua: 'Безперешкодно',
    },
    {
        en: 'Alternatively',
        t: '[ɔːlˈtɜːnətɪvli]',
        ru: 'Альтернативно',
        ua: 'Альтернативно',
    },
    {
        en: 'Disproportionately',
        t: '[ˌdɪsprəˈpɔːʃnɪtli]',
        ru: 'Непропорционально',
        ua: 'Непропорційно',
    },
    { en: 'Innermost', t: '[ˈɪnəməʊst]', ru: 'Сокровенно', ua: 'Сокровно' },
    { en: 'Midway', t: '[ˈmɪdˈweɪ]', ru: 'Посредине', ua: 'Посередині' },
    { en: 'Unthinkable', t: '[ʌnˈθɪŋkəbl]', ru: 'Немыслимо', ua: 'Немислимо' },
    { en: 'Ruthlessly', t: '[ˈruːθlɪsli]', ru: 'Беспощадно', ua: 'Нещадно' },
    { en: 'Altogether', t: '[ˌɔːltəˈgɛðə]', ru: 'В целом', ua: 'Загалом' },
    { en: 'Beneath', t: '[bɪˈniːθ]', ru: 'Под, внизу', ua: 'Під, внизу' },
    {
        en: 'Factually',
        t: '[ˈfækʧʊəli]',
        ru: 'По-настоящему',
        ua: 'По-справжньому',
    },
    { en: 'Indeed', t: '[ɪnˈdiːd]', ru: 'Действительно', ua: 'Справді' },
    {
        en: 'Occasionally',
        t: '[əˈkeɪʒnəli]',
        ru: 'Время от времени',
        ua: 'Іноді',
    },
    {
        en: 'Plenty',
        t: '[ˈplɛnti]',
        ru: 'Много, достаточно, полно',
        ua: 'Багато, достатньо, повно',
    },
    { en: 'Anywise', t: '[ˈɛnɪwaɪz]', ru: 'Как угодно', ua: 'Як завгодно' },
    { en: 'Somewhere', t: '[ˈsʌmweə]', ru: 'Где-то', ua: 'Десь' },
    { en: 'Throughout', t: '[θru(ː)ˈaʊt]', ru: 'Повсюду', ua: 'Повсюди' },
    {
        en: 'Scarcely',
        t: '[ˈskeəsli]',
        ru: 'Скудно, редко',
        ua: 'Скудно, рідко',
    },
    { en: 'Weekly', t: '[ˈwiːkli]', ru: 'Еженедельно', ua: 'Тижня' },
    { en: 'Quietly', t: '[ˈkwaɪətli]', ru: 'Тихо', ua: 'Тихо' },
    {
        en: 'Rather too',
        t: '[ˈrɑːðə tuː]',
        ru: 'Скорее слишком',
        ua: 'Швидше занадто',
    },
    { en: 'Chiefly', t: '[ˈʧiːfli]', ru: 'В основном', ua: 'В основному' },
]

export default words
