const words = [
    { en: 'Collaboratively', t: '[kəˈlæb(ə)rətɪvli]', ru: 'Совместно' },
    { en: 'Twofold', t: '[ˈtuːfəʊld]', ru: 'Вдвойне' },
    { en: 'Backwards', t: '[ˈbækwədz]', ru: 'Наоборот, назад' },
    { en: 'Alongside', t: '[əˈlɒŋˈsaɪd]', ru: 'Наряду' },
    { en: 'Face-to-face', t: '[feɪs-tuː-feɪs]', ru: 'Лицом к лицу' },
    { en: 'Increasingly', t: '[ɪnˈkriːsɪŋli]', ru: 'Все чаще' },
    { en: 'Likewise', t: '[ˈlaɪkwaɪz]', ru: 'Аналогично' },
    { en: 'Inherently', t: '[ɪnˈhɪərəntli]', ru: 'По своей сути' },
    { en: 'Yearslong', t: '[jɪəzlɒŋ]', ru: 'В течение года' },
    { en: 'Dramatically', t: '[drəˈmætɪk(ə)li]', ru: 'Значительно' },
    { en: 'Overall', t: '[ˈəʊvərɔːl]', ru: 'В целом' },
    { en: 'Sustainably', t: '[səsˈteɪnˈeɪbli]', ru: 'Устойчиво' },
    { en: 'Thoroughly', t: '[ˈθʌrəli]', ru: 'Тщательно' },
    { en: 'Radically', t: '[ˈrædɪkəli]', ru: 'Радикально' },
    { en: 'Undeniably', t: '[ˌʌndɪˈnaɪəbli]', ru: 'Бесспорно' },
    { en: 'Amongst', t: '[əˈmʌŋst]', ru: 'Среди' },
    { en: 'Specifically', t: '[spəˈsɪfɪk(ə)li]', ru: 'Конкретно' },
    { en: 'Unless', t: '[ənˈlɛs]', ru: 'Если только' },
    { en: 'Seamless', t: '[ˈsiːmlɪs]', ru: 'Беспрепятственно' },
    { en: 'Alternatively', t: '[ɔːlˈtɜːnətɪvli]', ru: 'Альтернативно' },
    {
        en: 'Disproportionately',
        t: '[ˌdɪsprəˈpɔːʃnɪtli]',
        ru: 'Непропорционально',
    },
    { en: 'Innermost', t: '[ˈɪnəməʊst]', ru: 'Сокровенно' },
    { en: 'Midway', t: '[ˈmɪdˈweɪ]', ru: 'Посредине' },
    { en: 'Unthinkable', t: '[ʌnˈθɪŋkəbl]', ru: 'Немыслимо' },
    { en: 'Ruthlessly', t: '[ˈruːθlɪsli]', ru: 'Беспощадно' },
    { en: 'Altogether', t: '[ˌɔːltəˈgɛðə]', ru: 'В целом' },
    { en: 'Beneath', t: '[bɪˈniːθ]', ru: 'Под, внизу' },
    { en: 'Factually', t: '[ˈfækʧʊəli]', ru: 'По-настоящему' },
    { en: 'Indeed', t: '[ɪnˈdiːd]', ru: 'Действительно' },
    { en: 'Occasionally', t: '[əˈkeɪʒnəli]', ru: 'Время от времени' },
    { en: 'Plenty', t: '[ˈplɛnti]', ru: 'Много, достаточно, полно' },
    { en: 'Anywise', t: '[ˈɛnɪwaɪz]', ru: 'Как угодно' },
    { en: 'Somewhere', t: '[ˈsʌmweə]', ru: 'Где-то' },
    { en: 'Throughout', t: '[θru(ː)ˈaʊt]', ru: 'Повсюду' },
    { en: 'Scarcely', t: '[ˈskeəsli]', ru: 'Скудно, редко' },
    { en: 'Weekly', t: '[ˈwiːkli]', ru: 'Еженедельно' },
    { en: 'Quietly', t: '[ˈkwaɪətli]', ru: 'Тихо' },
    { en: 'Rather too', t: '[ˈrɑːðə tuː]', ru: 'Скорее слишком' },
    { en: 'Chiefly', t: '[ˈʧiːfli]', ru: 'В основном' },
]

export default words