const words = [
    { en: 'nostalgia', t: '[nɒstˈælʤɪə]', ru: 'Ностальгия, сожаление' },
    { en: 'uplighting', t: '[ʌp ˈlaɪtɪŋ]', ru: 'Освещение, просвещение' },
    { en: 'escapism', t: '[ɪsˈkeɪpɪzm]', ru: 'Эскапизм, уход, бегство' },
    {
        en: 'nonfiction',
        t: '[nɒnˈfɪkʃən]',
        ru: 'Нон-фикшн, нехудожественная литература',
    },
    { en: 'psychology', t: '[saɪˈkɒləʤi]', ru: 'Психология' },
    { en: 'funnel', t: '[ˈfʌnl]', ru: 'Воронка, водоворот' },
    { en: 'amateur', t: '[ˈæmətə(ː)]', ru: 'Любитель, фанат' },
    {
        en: 'protagonist',
        t: '[prəʊˈtægənɪst]',
        ru: 'Протагонист, главный герой',
    },
    { en: 'pinpoint', t: '[ˈpɪnpɔɪnt]', ru: 'Точка опоры, привязка' },
    { en: 'announcement', t: '[əˈnaʊnsmənt]', ru: 'Анонс, объявление' },
    { en: 'consequence', t: '[ˈkɒnsɪkwəns]', ru: 'Заключение, следствие' },
    {
        en: 'exaggeration',
        t: '[ɪgˌzæʤəˈreɪʃən]',
        ru: 'Преувеличение, утрирование',
    },
    {
        en: 'scrutiny',
        t: '[ˈskruːtɪni]',
        ru: 'Исследование, тщательная проверка',
    },
    { en: 'blueprint', t: '[ˈbluːprɪnt]', ru: 'План, проект, чертеж' },
    { en: 'expansion', t: '[ɪksˈpænʃən]', ru: 'Развитие, расширение' },
    { en: 'extent', t: '[ɪksˈtɛnt]', ru: 'Степень, размах, масштаб' },
    { en: 'victim', t: '[ˈvɪktɪm]', ru: 'Жертва' },
    { en: 'ownership', t: '[ˈəʊnəʃɪp]', ru: 'Право собственности, владение' },
    {
        en: 'mass-market',
        t: '[mæs-ˈmɑːkɪt]',
        ru: 'Масс-маркет, массовая торговля',
    },
    { en: 'variety', t: '[vəˈraɪəti]', ru: 'Многообразие, разновидность' },
    { en: 'headline', t: '[ˈhɛdlaɪn]', ru: 'Заголовок, заглавие' },
    {
        en: 'allegation',
        t: '[ˌælɪˈgeɪʃ(ə)n]',
        ru: 'Утверждение, заявление, обвинение',
    },
    { en: 'restriction', t: '[rɪsˈtrɪkʃən]', ru: 'Ограничение, запрет' },
    { en: 'comprehension', t: '[ˌkɒmprɪˈhɛnʃən]', ru: 'Понимание, осмысление' },
    { en: 'existence', t: '[ɪgˈzɪstəns]', ru: 'Бытие, существование' },
    { en: 'counterpart', t: '[ˈkaʊntəpɑːt]', ru: 'Аналог, двойник' },
    { en: 'goldmine', t: '[ˈgəʊldmaɪn]', ru: 'Золотая жила' },
    { en: 'applause', t: '[əˈplɔːz]', ru: 'Аплодисменты' },
    {
        en: 'satisfaction',
        t: '[ˌsætɪsˈfækʃən]',
        ru: 'Удовлетворение, удовольствие',
    },
    { en: 'testimonial', t: '[ˌtɛstəˈməʊniəl]', ru: 'Отзыв' },
    { en: 'empathy', t: '[ˈɛmpəθi]', ru: 'Эмпатия' },
    {
        en: 'consideration',
        t: '[kənˌsɪdəˈreɪʃən]',
        ru: 'Размышление, соображение',
    },
    { en: 'touchpoint', t: '[tʌʧ pɔɪnt]', ru: 'Точка соприкосновения' },
    { en: 'jargon', t: '[ˈʤɑːgən]', ru: 'Жаргон' },
    { en: 'background', t: '[ˈbækgraʊnd]', ru: 'Предыстория' },
    { en: 'relief', t: '[rɪˈliːf]', ru: 'Помощь, разрядка' },
    { en: 'perception', t: '[pəˈsɛpʃən]', ru: 'Восприятие' },
    { en: 'stance', t: '[stɑːns]', ru: 'Позиция, отношение' },
    { en: 'catharsis', t: '[kəˈθɑːsɪs]', ru: 'Катарсис' },
    { en: 'solace', t: '[ˈsɒləs]', ru: 'Утешение' },
]

export default words
