const words = [
    { en: 'questionnaire', t: '[ˌkwɛstɪəˈneə]', ru: 'Анкета, опросник' },
    { en: 'oversight', t: '[ˈəʊvəsaɪt]', ru: 'Надзор, контроль, проверка' },
    { en: 'stewardship', t: '[ˈəʊvəsaɪt]', ru: 'Ответственность, управление' },
    { en: 'estimating', t: '[ˈɛstɪmeɪtɪŋ]', ru: 'Оценивание, подсчет, оценка' },
    {
        en: 'inquiry',
        t: '[ɪnˈkwaɪəri]',
        ru: 'Исследование, опрос, изучение, следствие',
    },
    {
        en: 'contemplation',
        t: '[ˌkɒntɛmˈpleɪʃən]',
        ru: 'Размышление, обдумывание, рассуждение',
    },
    { en: 'alternative', t: '[ɔːlˈtɜːnətɪv]', ru: 'Альтернатива' },
    { en: 'grade', t: '[greɪd]', ru: 'Класс, ранг, балл, оценка' },
    { en: 'graduate', t: '[ˈgrædjʊət]', ru: 'Выпускник, дипломник' },
    {
        en: 'credential',
        t: '[krɪˈdɛnʃəl]',
        ru: 'Диплом, аттестат, свидетельство',
    },
    { en: 'accolade', t: '[ækəʊleɪd]', ru: 'Награда, похвала, благодарность' },
    { en: 'scale', t: '[skeɪl]', ru: 'Шкала, величина' },
    { en: 'gliding', t: '[ˈglaɪdɪŋ]', ru: 'Планерка' },
    { en: 'record', t: '[ˈrɛkɔːd]', ru: 'Запись, досье, рекорд' },
    {
        en: 'measurability',
        t: '[ˌmɛʒərəˈbɪlɪti]',
        ru: 'Исчислимость, измеримость, измерение',
    },
    {
        en: 'homeschooler',
        t: '[həʊm skuːlə]',
        ru: 'Ученик на домашнем обучении',
    },
    { en: 'worksheet', t: '[ˈwɜːkˌʃiːt]', ru: 'Рабочий лист, таблица' },
    { en: 'galore', t: '[gəˈlɔː]', ru: 'Множество, куча, обилиие' },
    { en: 'prompt', t: '[prɒmpt]', ru: 'Подсказка, совет' },
    {
        en: 'membership',
        t: '[ˈmɛmbəʃɪp]',
        ru: 'Членство, участие, принадлежность, состав',
    },
    { en: 'progress tracker', t: '[ˈprəʊgrəs ˈtrækə]', ru: 'Трекер прогресса' },
    {
        en: 'sequence',
        t: '[ˈsiːkwəns]',
        ru: 'Последовательность, порядок, очередь',
    },
    { en: 'undergraduate', t: '[ˌʌndəˈgrædjʊɪt]', ru: 'Бакалавр, ученик' },
    { en: 'degree', t: '[dɪˈgriː]', ru: 'Степень, диплом' },
    { en: 'carer', t: '[ˈkeərə]', ru: 'Воспитатель, опекун' },
    { en: 'transition', t: '[trænˈzɪʃ(ə)n]', ru: 'Переход, превращение' },
    { en: 'recognition', t: '[ˌrɛkəgˈnɪʃən]', ru: 'Признание, осознание' },
    { en: 'workforce', t: '[wɜːkˌfɔːs]', ru: 'Рабочая сила, кадры' },
    { en: 'volunteering', t: '[ˌvɒlənˈtɪərɪŋ]', ru: 'Волонтерство' },
    { en: 'internship', t: '[ˈɪntɜːnʃɪp]', ru: 'Стажировка, интернатура' },
    {
        en: 'accommodation',
        t: '[əˌkɒməˈdeɪʃ(ə)n]',
        ru: 'Проживание, размещение, жилье',
    },
    {
        en: 'enrolment',
        t: '[əˌkɒməˈdeɪʃ(ə)n]',
        ru: 'Зачисление, набор, поступление',
    },
    { en: 'guideline', t: '[ˈgaɪdlaɪn]', ru: 'Рекомендация, инструкция' },
    { en: 'hub', t: '[hʌb]', ru: 'Центр, средоточие, концентратор' },
    { en: 'piety', t: '[ˈpaɪəti]', ru: 'Благочестие' },
    { en: 'impact', t: '[ˈɪmpækt]', ru: 'Последствие, результат, влияние' },
    { en: 'well-being', t: '[wɛl-ˈbiːɪŋ]', ru: 'Благополучие' },
    { en: 'reasoning', t: '[ˈriːznɪŋ]', ru: 'Довод, логика, обоснование' },
    { en: 'incursion', t: '[ɪnˈkɜːʃən]', ru: 'Нарушение, столкновение' },
    { en: 'venue', t: '[ˈvɛnjuː]', ru: 'Место проведения' },
]

export default words