const words = [
    { en: 'doorstep', t: '[ˈdɔːstɛp]', ru: 'Порог квартиры' },
    { en: 'supervisor', t: '[ˈsjuːpəvaɪzə]', ru: 'Супервайзер' },
    {
        en: 'affirmation',
        t: '[ˌæfɜːˈmeɪʃ(ə)n]',
        ru: 'Утверждение, подтверждение',
    },
    { en: 'uptick', t: '[ʌp tɪk]', ru: 'Стимул, увеличение, толчок, подъем' },
    { en: 'drop-off', t: '[drɒp-ɒf]', ru: 'Спад, снижение, упадок' },
    {
        en: 'conversation',
        t: '[kɒnvəˈseɪʃən]',
        ru: 'Разговор, беседа, обсуждение',
    },
    { en: 'indifference', t: '[ɪnˈdɪfrəns]', ru: 'Безразличие, безучастие' },
    { en: 'ageism', t: '[ˈeɪʤɪz(ə)m]', ru: 'Эйджизм' },
    { en: 'segmentation', t: '[sɛgmɛnˈteɪʃən]', ru: 'Сегментация' },
    {
        en: 'landmark',
        t: '[ˈlændmɑːk]',
        ru: 'Веха, ориентир, достопримечательность',
    },
    { en: 'upheaval', t: '[ʌpˈhiːvəl]', ru: 'Переворот, катастрофа, волнение' },
    {
        en: 'harassment',
        t: '[ˈhærəsmənt]',
        ru: 'Преследование, домогательство',
    },
    { en: 'disarray', t: '[dɪsəˈreɪ]', ru: 'Беспорядок, разброд' },
    { en: 'proof', t: '[pruːf]', ru: 'Доказательство' },
    { en: 'influx', t: '[ˈɪnflʌks]', ru: 'Наплыв, приток' },
    { en: 'struggle', t: '[ˈstrʌgl]', ru: 'Борьба, поединок, спор' },
    { en: 'loneliness', t: '[ˈləʊnlɪnəs]', ru: 'Одиночество, уединение' },
    { en: 'mental health', t: '[ˈmɛntl hɛlθ]', ru: 'Психическое здоровье' },
    {
        en: 'authenticity',
        t: '[ˌɔːθɛnˈtɪsɪti]',
        ru: 'Подлинность, самобытность',
    },
    { en: 'donation', t: '[dəʊˈneɪʃən]', ru: 'Пожертвование, донорство' },
    { en: 'backlash', t: '[ˈbæklæʃ]', ru: 'Обратная реакция' },
    { en: 'connotation', t: '[kɒnəʊˈteɪʃən]', ru: 'Подтекст, смысл, намек' },
    { en: 'affinity', t: '[ əˈfɪnɪti]', ru: 'Близость, сходство, симпатия' },
    {
        en: 'diversification',
        t: '[daɪˌvɜːsɪfɪˈkeɪʃən]',
        ru: 'Диверсификация, разнообразие',
    },
    { en: 'takeover', t: '[pteɪkˌəʊvə]', ru: 'Поглощение' },
    { en: 'feminism', t: '[ˈfɛmɪnɪzm]', ru: 'Феминизм' },
    { en: 'equality', t: '[i(ː)ˈkwɒlɪti]', ru: 'Равенство' },
    {
        en: 'sustainability',
        t: '[səsˌteɪnəˈbɪlɪti]',
        ru: 'Устойчивость, стабильность',
    },
    { en: 'chunk', t: '[ʧʌŋk]', ru: 'Кусок, ломоть, глыба' },
    { en: 'repercussion', t: '[ˌriːpɜːˈkʌʃən]', ru: 'Последствия, отзвук' },
    { en: 'preference', t: '[ˈprɛfərəns]', ru: 'Предпочтение, преимущество' },
    { en: 'aspiration', t: '[ˌæspəˈreɪʃ(ə)n]', ru: 'Стремление, желание' },
    { en: 'consumption', t: '[kənˈsʌm(p)ʃən]', ru: 'Потребление, расход' },
    { en: 'mismanagement', t: '[ˌmɪsˈmænɪʤmənt]', ru: 'Бесхозяйственность' },
    { en: 'keynote', t: '[ˈkiːnəʊt]', ru: 'Лейтмотив' },
    { en: 'rivalry', t: '[ˈraɪvəlri]', ru: 'Соперничество, противостояние' },
    { en: 'disparity', t: '[dɪsˈpærɪti]', ru: 'Несоответствие, неравенство' },
    { en: 'repayment', t: '[riːˈpeɪmənt]', ru: 'Расплата, погашение, возврат' },
    { en: 'allegation', t: '[ˌælɪˈgeɪʃ(ə)n]', ru: 'Обвинение, утверждение' },
    {
        en: 'prevalence',
        t: '[ˈprɛvələns]',
        ru: 'Распространенность, преобладание',
    },
]

export default words