const words = [
    { en: 'To abhor', t: '[əbˈhɔː]', ru: 'Ненавидеть' },
    { en: 'To abrogate', t: '[ˈæbrəʊgeɪt]', ru: 'Отменить' },
    { en: 'To abstain', t: '[əbˈsteɪn]', ru: 'Воздержаться' },
    { en: 'To strengthen', t: '[ˈstrɛŋθən]', ru: 'Укрепить, усилить' },
    { en: 'To yield', t: '[jiːld]', ru: 'Уступить' },
    { en: 'To sustain', t: '[səsˈteɪn]', ru: 'Поддерживать' },
    { en: 'To seize', t: '[siːz]', ru: 'Захватить' },
    { en: 'To nourish', t: '[ˈnʌrɪʃ]', ru: 'Питать' },
    { en: 'To desist', t: '[dɪˈzɪst]', ru: 'Запретить' },
    { en: 'To recapitulate', t: '[riːkəˈpɪtjʊleɪt]', ru: 'Пересказывать' },
    { en: 'To proclaim', t: '[prəˈkleɪm]', ru: 'Провозгласить, объявить' },
    { en: 'To beget', t: '[bɪˈgɛt]', ru: 'Родить' },
    { en: 'To mature', t: '[məˈtjʊə]', ru: 'Созреть' },
    { en: 'To contemplate', t: '[ˈkɒntɛmpleɪt]', ru: 'Созерцать' },
    { en: 'To flourish', t: '[ˈflʌrɪʃ]', ru: 'Процветать' },
    { en: 'To cable', t: '[ˈkeɪbl]', ru: 'Проводить' },
    { en: 'To congregate', t: '[ˈkɒŋgrɪgeɪt]', ru: 'Собираться' },
    { en: 'To induce', t: '[ɪnˈdjuːs]', ru: 'Побудить, побуждать' },
    { en: 'To highlight', t: '[ˈhaɪˌlaɪt]', ru: 'Выделять' },
    { en: 'To foretell', t: '[fɔːˈtɛl]', ru: 'Предсказывать' },
    { en: 'To foreshadow', t: '[fɔːˈʃædəʊ]', ru: 'Предвещать' },
    { en: 'To interlace', t: '[ɪntə(ː)ˈleɪs]', ru: 'Переплетать' },
    { en: 'To relish', t: '[ˈrɛlɪʃ]', ru: 'Наслаждаться, смаковать' },
    { en: 'To tread', t: '[trɛd]', ru: 'Ухаживать' },
    { en: 'To rehearse', t: '[rɪˈhɜːs]', ru: 'Репетировать' },
    { en: 'To narrate', t: '[nəˈreɪt]', ru: 'Рассказывать' },
    { en: 'To alleviate', t: '[əˈliːvɪeɪt]', ru: 'Облегчать, облегчить' },
    { en: 'To bilk', t: '[bɪlk]', ru: 'Обналичивать' },
    { en: 'To refine', t: '[rɪˈfaɪn]', ru: 'Усовершенствовать' },
    { en: 'To restructure', t: '[riːˈstrʌkʧə]', ru: 'Реструктурировать' },
    { en: 'To decay', t: '[dɪˈkeɪ]', ru: 'Распадаться' },
    { en: 'To corrupt', t: '[kəˈrʌpt]', ru: 'Развращать' },
    { en: 'To alter', t: '[ˈɔːltə]', ru: 'Изменяться' },
    { en: 'To discern', t: '[dɪˈsɜːn]', ru: 'Различить' },
    { en: 'To disclose', t: '[dɪsˈkləʊz]', ru: 'Раскрыть' },
    { en: 'To inscribe', t: '[ɪnˈskraɪb]', ru: 'Начертать' },
    { en: 'To proffer', t: '[ˈprɒfə]', ru: 'Предложить' },
    { en: 'To meddle', t: '[ˈmɛdl]', ru: 'Вмешиваться' },
    { en: 'To violate', t: '[ˈvaɪəleɪt]', ru: 'Нарушать' },
    { en: 'To further', t: '[ˈfɜːðə]', ru: 'Продолжать' },
    { en: 'To humble', t: '[hʌmbl]', ru: 'Смирять' },
    { en: 'To subdue', t: '[səbˈdjuː]', ru: 'Покорять' },
    { en: 'To demote', t: '[dɪˈməʊt]', ru: 'Понижать, разжаловать' },
    { en: 'To obey', t: '[əˈbeɪ]', ru: 'Подчиняться, слушаться' },
    { en: 'To employ', t: '[ɪmˈplɔɪ]', ru: 'Нанимать' },
    { en: 'To chastise', t: '[ʧæsˈtaɪz]', ru: 'Наказывать' },
    { en: 'To concoct', t: '[kənˈkɒkt]', ru: 'Придумать' },
    { en: 'To condone', t: '[kənˈdəʊn]', ru: 'Потворствовать' },
    { en: 'To cringe', t: '[krɪnʤ]', ru: 'Сокрушаться' },
    { en: 'To ensconce', t: '[ɪnˈskɒns]', ru: 'Приютить, успокоить' },
    { en: 'To sanction', t: '[ˈsæŋkʃən]', ru: 'Наказывать' },
    { en: 'To affix', t: '[ˈæfɪks]', ru: 'Прикрепить, зафиксировать' },
    { en: 'To curb', t: '[kɜːb]', ru: 'Ограничить, обуздать' },
    { en: 'To restrain', t: '[rɪsˈtreɪn]', ru: 'Сдерживать' },
    { en: 'To enlarge', t: '[ɪnˈlɑːʤ]', ru: 'Увеличить, повысить' },
    { en: 'To govern', t: '[ˈgʌvən]', ru: 'Управлять' },
    { en: 'To reckon', t: '[ˈrɛkən]', ru: 'Пересчитать' },
    { en: 'To esteem', t: '[ɪsˈtiːm]', ru: 'Ценить, уважать' },
    { en: 'To sweeten', t: '[swiːtn]', ru: 'Подсластить' },
    { en: 'To fluctuate', t: '[ˈflʌktjʊeɪt]', ru: 'Колебаться' },
    { en: 'To fare', t: '[feə]', ru: 'Зависеть, дорожать, подвергаться' },
    { en: 'To halt', t: '[hɔːlt]', ru: 'Остановить, останавливать' },
    { en: 'To endure', t: '[ɪnˈdjʊə]', ru: 'Выдержать, выдерживать' },
    { en: 'To revenge', t: '[rɪˈvɛnʤ]', ru: 'Мстить' },
    { en: 'To attain', t: '[əˈteɪn]', ru: 'Достигать, достичь' },
    { en: 'To divest', t: '[daɪˈvɛst]', ru: 'Расставаться' },
    { en: 'To elucidate', t: '[ɪˈluːsɪdeɪt]', ru: 'Прояснить' },
    { en: 'To invent', t: '[ɪnˈvɛnt]', ru: 'Изобретать, придумывать' },
    { en: 'To shield', t: '[ʃiːld]', ru: 'Защищать' },
    {
        en: 'To resemble',
        t: '[rɪˈzɛmbl]',
        ru: 'Походить, быть похожим, напоминать',
    },
    { en: 'To ingest', t: '[ ɪnˈʤɛst]', ru: 'Проглотить, заглотить' },
    {
        en: 'To dispense',
        t: '[dɪsˈpɛns]',
        ru: 'Раздавать, дозировать, выдавать',
    },
    { en: 'To match', t: '[mæʧ]', ru: 'Соответствовать' },
    { en: 'To engross', t: '[ɪnˈgrəʊs]', ru: 'Вовлечь, увлечь, задействовать' },
    { en: 'To collude', t: '[kəˈluːd]', ru: 'Сговориться, войти' },
    { en: 'To split', t: '[splɪt]', ru: 'Разделить, разрушить' },
    { en: 'To unveil', t: '[ʌnˈveɪl]', ru: 'Раскрыть, огласить, показать' },
    { en: 'To bear', t: '[beə]', ru: 'Выносить, выдерживать, рожать' },
    { en: 'To prompt', t: '[prɒmpt]', ru: 'Подсказать, побудить' },
    { en: 'To mold', t: '[məʊld]', ru: 'Лепить, формировать' },
    { en: 'To rub', t: '[rʌb]', ru: 'Натирать, втирать, растирать' },
    { en: 'To stomp', t: '[stɒmp]', ru: 'Топтать, затоптать' },
    { en: 'To narrate', t: '[nəˈreɪt', ru: 'Рассказывать, повествовать' },
    { en: 'To sense', t: '[sɛns]', ru: 'Чувствовать, понимать' },
    { en: 'To outdate', t: '[ˈaʊtˌdeɪt]', ru: 'Устаревать' },
    { en: 'To clutter', t: '[ˈklʌtə]', ru: 'Загромождать, захламить' },
    { en: 'To scrabble', t: '[ˈskræbl]', ru: 'Царапать' },
    { en: 'To accuse', t: '[əˈkjuːz]', ru: 'Обвинять' },
    { en: 'To summon', t: '[ˈsʌmən]', ru: 'Вызвать, созвать' },
    { en: 'To outfit', t: '[ˈaʊtfɪt]', ru: 'Снарядить, обмундировать' },
    { en: 'To convert', t: '[ˈkɒnvɜːt]', ru: 'Преобразовать' },
    {
        en: 'To override',
        t: '[əʊvəˈraɪd]',
        ru: 'Переопределить, перераспределить',
    },
    { en: 'To bind', t: '[baɪnd]', ru: 'Связать' },
    { en: 'To nurture', t: '[ˈnɜːʧə]', ru: 'Воспитывать' },
    { en: 'To recount', t: '[riːˈkaʊnt]', ru: 'Пересказывать' },
    { en: 'To backlog', t: '[ˈbæklɒg]', ru: 'Отставать' },
    {
        en: 'To inspectorate',
        t: '[ɪnˈspɛktərɪt]',
        ru: 'Инспектировать, проверять',
    },
    { en: 'To unearth', t: '[ʌnˈɜːθ]', ru: 'Раскопать' },
    {
        en: 'To demote',
        t: '[dɪˈməʊt]',
        ru: 'Понизить в должности, разжаловать',
    },
    { en: 'To trap', t: '[træp]', ru: 'Заманить в ловушку' },
]

export default words
