const words = [
    { en: 'Blind', t: '[blaɪnd]', ru: 'Слепой' },
    { en: 'Catchy', t: '[ˈkæʧi]', ru: 'Броский, запоминающийся' },
    { en: 'Common', t: '[ˈkɒmən]', ru: 'Распространенный' },
    { en: 'Familiar', t: '[fəˈmɪliə]', ru: 'Знакомый' },
    { en: 'Frequent', t: '[ˈfriːkwənt]', ru: 'Частый' },
    { en: 'Recurrent', t: '[rɪˈkʌrənt]', ru: 'Повторяющийся' },
    { en: 'Enormous', t: '[ɪˈnɔːməs]', ru: 'Огромный' },
    { en: 'Expensive', t: '[ɪksˈpɛnsɪv]', ru: 'Дорогой' },
    { en: 'Valuable', t: '[ˈvæljʊəbl]', ru: 'Ценный' },
    { en: 'Muslim', t: '[ˈmʊslɪm]', ru: 'Мусульманский' },
    { en: 'Lucky', t: '[ˈlʌki]', ru: 'Удачный' },
    { en: 'Clear', t: '[klɪə]', ru: 'Чистый, понятный' },
    { en: 'Scientific', t: '[saɪənˈtɪfɪk]', ru: 'Научный' },
    { en: 'Huge', t: '[hjuːʤ]', ru: 'Большой, огромный' },
    { en: 'Messy', t: '[ˈmɛsi]', ru: 'Беспорядочный' },
    { en: 'Unforgettable', t: '[ʌnfəˈgɛtəbl]', ru: 'Незабываемый' },
    { en: 'False', t: '[fɔːls]', ru: 'Неверный, неправильный' },
    { en: 'Fierce', t: '[fɪəs]', ru: 'Свирепый, жестокий' },
    { en: 'Explicit', t: '[ɪksˈplɪsɪt]', ru: 'Ярко выраженный' },
    { en: 'Exterior', t: '[ɛksˈtɪərɪə]', ru: 'Внешний' },
    { en: 'Hidden', t: '[ˈhɪdn]', ru: 'Скрытый' },
    { en: 'Powerful', t: '[ˈpaʊəfʊl]', ru: 'Мощный' },
    { en: 'Internal', t: '[ɪnˈtɜːnl]', ru: 'Внутренний' },
    { en: 'Fabulous', t: '[ˈfæbjʊləs]', ru: 'Невероятный' },
    { en: 'Beautiful', t: '[ˈbjuːtəfʊl]', ru: 'Красивый' },
    { en: 'Gorgeous', t: '[ˈgɔːʤəs]', ru: 'Великолепный' },
    { en: 'Fruitful', t: '[ˈfruːtfʊl]', ru: 'Плодотворный' },
    { en: 'Formidable', t: '[ˈfɔːmɪdəbl]', ru: 'Замечательный' },
    { en: 'Fortunate', t: '[ˈfɔːʧnɪt]', ru: 'Удачливый, счастливый' },
    { en: 'Frail', t: '[freɪl]', ru: 'Хилый, хрупкий' },
    { en: 'Friendly', t: '[ˈfrɛndli]', ru: 'Дружелюбный' },
    { en: 'Loyal', t: '[ˈlɔɪəl]', ru: 'Лояльный' },
    { en: 'General', t: '[ˈʤɛnərəl]', ru: 'Общий, генеральный' },
    { en: 'Generous', t: '[ˈʤɛnərəs]', ru: 'Щедрый' },
    { en: 'Gradual', t: '[ˈgrædjʊəl]', ru: 'Постепенный' },
    { en: 'Productive', t: '[prəˈdʌktɪv]', ru: 'Продуктивный' },
    { en: 'Protected', t: '[prəˈtɛktɪd]', ru: 'Защищенный' },
    { en: 'Hardy', t: '[ˈhɑːdi]', ru: 'Выносливый' },
    { en: 'Peaceful', t: '[ˈpiːsfʊl]', ru: 'Мирный, миролюбивый' },
    { en: 'Digital', t: '[ˈdɪʤɪtl]', ru: 'Цифровой' },
    { en: 'Social', t: '[ˈsəʊʃəl]', ru: 'Социальный' },
    { en: 'Hideous', t: '[hɪdɪə]', ru: 'Отвратительный' },
    { en: 'Awful', t: '[ˈɔːfʊl]', ru: 'Ужасный' },
    { en: 'Awesome', t: '[ˈɔːsəm]', ru: 'Милый' },
    { en: 'High-quality', t: '[haɪ-ˈkwɒlɪti]', ru: 'Высококачественный' },
    { en: 'Helpless', t: '[ˈhɛlplɪs]', ru: 'Беспомощный' },
    { en: 'Hilarious', t: '[ hɪˈleərɪəs]', ru: 'Уморительный' },
    { en: 'Idle', t: '[ˈaɪdl]', ru: 'Безработный' },
    { en: 'Immediate', t: '[ɪˈmiːdiət]', ru: 'Незамедлительный' },
    { en: 'Main', t: '[meɪn]', ru: 'Главный' },
    { en: 'European', t: '[jʊərəˈpi(ː)ən]', ru: 'Европейский' },
    { en: 'Simultaneous', t: '[sɪməlˈteɪniəs]', ru: 'Одновременный' },
    { en: 'Special', t: '[ˈspɛʃəl]', ru: 'Специальный' },
    { en: 'Visible', t: '[ˈvɪzəbl]', ru: 'Видимый' },
    { en: 'Honest', t: '[ˈɒnɪst]', ru: 'Честный' },
    { en: 'Mortal', t: '[ˈmɔːtl]', ru: 'Смертельный' },
    { en: 'Hyperactive', t: '[ˈhaɪpə ˈæktɪv]', ru: 'Гиперактивный' },
    { en: 'Personal', t: '[ˈpɜːsnl]', ru: 'Личный, персональный' },
    { en: 'Foolish', t: '[ˈfuːlɪʃ]', ru: 'Безумный, глупый' },
    { en: 'Sudden', t: '[ˈsʌdn]', ru: 'Внезапный' },
]

export default words
