const words = [
    { en: 'Endlessly', t: '[ˈɛndlɪsli]', ru: 'Бесконечно', ua: 'Нескінченно' },
    {
        en: 'Unselfishly',
        t: '[ʌnˈsɛlfɪʃli]',
        ru: 'Бескорыстно',
        ua: 'Безкорисно',
    },
    { en: 'Generously', t: '[ˈʤɛnərəsli]', ru: 'Щедро', ua: 'Щедро' },
    { en: 'Along', t: '[əˈlɒŋ]', ru: 'Вдоль, по', ua: 'По, вздовж' },
    {
        en: 'Accordingly',
        t: '[əˈkɔːdɪŋli]',
        ru: 'Соответственно',
        ua: 'Відповідно',
    },
    {
        en: 'Subsequently',
        t: '[ˈsʌbsɪkwəntli]',
        ru: 'Впоследствии',
        ua: 'Пізніше',
    },
    { en: 'Subtly', t: '[ˈsʌtli]', ru: 'Тонко', ua: 'Тонко' },
    {
        en: 'Precisely',
        t: '[prɪˈsaɪsli]',
        ru: 'Точно, четко',
        ua: 'Точно, чітко',
    },
    { en: 'Better', t: '[ˈbɛtə]', ru: 'Лучше', ua: 'Краще' },
    {
        en: 'Everywhere',
        t: '[ˈɛvrɪweə]',
        ru: 'Везде, где угодно',
        ua: 'Будь-де, де завгодно',
    },
    { en: 'Out', t: '[aʊt]', ru: 'За, из', ua: 'За, із' },
    { en: 'Fully', t: '[ˈfʊli]', ru: 'Полностью', ua: 'Повністю' },
    { en: 'Partly', t: '[ˈpɑːtli]', ru: 'Частично', ua: 'Частково' },
    { en: 'Utterly', t: '[ˈʌtəli]', ru: 'Полностью', ua: 'Повністю' },
    {
        en: 'Entirely',
        t: '[ɪnˈtaɪəli]',
        ru: 'Совершенно, целиком',
        ua: 'Зовсім, цілком',
    },
    { en: 'Therefore', t: '[ˈðeəfɔː]', ru: 'Поэтому', ua: 'Тому' },
    {
        en: 'Hence',
        t: '[hɛns]',
        ru: 'Вот почему, отсюда',
        ua: 'Ось чому, звідси',
    },
    {
        en: 'Consequently',
        t: '[ˈkɒnsɪkwəntli]',
        ru: 'Таким образом, соответственно',
        ua: 'Отже, відповідно',
    },
    {
        en: 'Bravely',
        t: '[ˈbreɪvli]',
        ru: 'Отважно, храбро',
        ua: 'Сміливо, хоробро',
    },
    {
        en: 'Carefully',
        t: '[ˈkeəfli]',
        ru: 'Внимательно, осторожно',
        ua: 'Уважно, обережно',
    },
    { en: 'Seldom', t: '[ˈsɛldəm]', ru: 'Редко', ua: 'Рідко' },
    { en: 'Frequently', t: '[ˈfriːkwəntli]', ru: 'Часто', ua: 'Часто' },
    { en: 'Outside', t: '[aʊtˈsaɪd]', ru: 'Снаружи', ua: 'Ззовні' },
    { en: 'Upstairs', t: '[ʌpˈsteəz]', ru: 'Наверху', ua: 'Зверху' },
    { en: 'Downstairs', t: '[daʊnˈsteəz]', ru: 'Внизу', ua: 'Знизу' },
    { en: 'Quite', t: '[kwaɪt]', ru: 'Вполне', ua: 'Досить' },
    { en: 'Early', t: '[ˈɜːli]', ru: 'Рано', ua: 'Рано' },
    { en: 'Simply', t: '[ˈsɪmpli]', ru: 'Легко, просто', ua: 'Легко, просто' },
    { en: 'Hard', t: '[hɑːd]', ru: 'Трудно', ua: 'Важко' },
    { en: 'Late', t: '[leɪt]', ru: 'Поздно', ua: 'Пізно' },
]

export default words
