const words = [
    { en: 'Endlessly', t: '[ˈɛndlɪsli]', ru: 'Бесконечно' },
    { en: 'Unselfishly', t: '[ʌnˈsɛlfɪʃli]', ru: 'Бескорыстно' },
    { en: 'Generously', t: '[ˈʤɛnərəsli]', ru: 'Щедро' },
    { en: 'Along', t: '[əˈlɒŋ]', ru: 'Вдоль, по' },
    { en: 'Accordingly', t: '[əˈkɔːdɪŋli]', ru: 'Соответственно' },
    { en: 'Subsequently', t: '[ˈsʌbsɪkwəntli]', ru: 'Впоследствии' },
    { en: 'Subtly', t: '[ˈsʌtli]', ru: 'Тонко' },
    { en: 'Precisely', t: '[prɪˈsaɪsli]', ru: 'Точно, четко' },
    { en: 'Better', t: '[ˈbɛtə]', ru: 'Лучше' },
    { en: 'Everywhere', t: '[ˈɛvrɪweə]', ru: 'Везде, где угодно' },
    { en: 'Out', t: '[aʊt]', ru: 'За, из' },
    { en: 'Fully', t: '[ˈfʊli]', ru: 'Полностью' },
    { en: 'Partly', t: '[ˈpɑːtli]', ru: 'Частично' },
    { en: 'Utterly', t: '[ˈʌtəli]', ru: 'Полностью' },
    { en: 'Entirely', t: '[ɪnˈtaɪəli]', ru: 'Совершенно, целиком' },
    { en: 'Therefore', t: '[ˈðeəfɔː]', ru: 'Поэтому' },
    { en: 'Hence', t: '[hɛns]', ru: 'Вот почему, отсюда' },
    {
        en: 'Consequently',
        t: '[ˈkɒnsɪkwəntli]',
        ru: 'Таким образом, соответственно',
    },
    { en: 'Bravely', t: '[ˈbreɪvli]', ru: 'Отважно, храбро' },
    { en: 'Carefully', t: '[ˈkeəfli]', ru: 'Внимательно, осторожно' },
    { en: 'Seldom', t: '[ˈsɛldəm]', ru: 'Редко' },
    { en: 'Frequently', t: '[ˈfriːkwəntli]', ru: 'Часто' },
    { en: 'Outside', t: '[aʊtˈsaɪd]', ru: 'Снаружи' },
    { en: 'Upstairs', t: '[ʌpˈsteəz]', ru: 'Наверху' },
    { en: 'Downstairs', t: '[daʊnˈsteəz]', ru: 'Внизу' },
    { en: 'Quite', t: '[kwaɪt]', ru: 'Вполне' },
    { en: 'Early', t: '[ˈɜːli]', ru: 'Рано' },
    { en: 'Simply', t: '[ˈsɪmpli]', ru: 'Легко, просто' },
    { en: 'Hard', t: '[hɑːd]', ru: 'Трудно' },
    { en: 'Late', t: '[leɪt]', ru: 'Поздно' },
]

export default words
