const words = [
    { en: 'activity', t: '[ækˈtɪvɪti]', ru: 'Деятельность' },
    { en: 'amount', t: '[əˈmaʊnt]', ru: 'Сумма, количество' },
    { en: 'author', t: '[ˈɔːθə]', ru: 'Автор' },
    { en: 'character', t: '[ˈkærɪktə]', ru: 'Характер' },
    { en: 'dictionary', t: '[ˈdɪkʃ(ə)n(ə)ri]', ru: 'Словарь' },
    { en: 'event', t: '[ɪˈvɛnt]', ru: 'Событие' },
    { en: 'guess', t: '[gɛs]', ru: 'Предположение, догадка' },
    { en: 'dashboard', t: '[ˈdæʃbɔːd]', ru: 'Панель управления' },
    { en: 'task manager', t: '[tɑːsk ˈmænɪʤə]', ru: 'Планировщик задач' },
    { en: 'sick day', t: '[sɪk deɪ]', ru: 'Больничный' },
    { en: 'trouble', t: '[ˈtrʌbl]', ru: 'Проблема' },
    { en: 'deadline', t: '[ˈdɛdlaɪn]', ru: 'Дедлайн' },
    { en: 'reason', t: '[ˈriːzn]', ru: 'Причина, смысл' },
    { en: 'to-do list', t: '[təˈduː lɪst]', ru: 'Список дел' },
    { en: 'remark', t: '[ˈrɪˈmɑːk]', ru: 'Замечание, ремарка' },
    { en: 'proofreading', t: '[ˈpruːfˌriːdɪŋ]', ru: 'Редактирование, вычитка' },
    { en: 'performance', t: '[pəˈfɔːməns]', ru: 'Исполнение, выступление' },
    { en: 'co-working space', t: '[kəʊ-ˈwɜːkɪŋ speɪs]', ru: 'Ко-воркинг' },
    { en: 'duty', t: '[ˈdjuːti]', ru: 'Обязанность' },
    { en: 'function', t: '[ˈfʌŋkʃən]', ru: 'Функция' },
    { en: 'burnout', t: '[ˈbɜːnˈaʊt]', ru: 'Выгорание' },
    { en: 'goal', t: '[gəʊl]', ru: 'Цель' },
    { en: 'timetable', t: '[ˈtaɪmˌteɪb(ə)l]', ru: 'Расписание' },
    { en: 'area', t: '[ˈeərɪə]', ru: 'Сфера, область' },
    { en: 'state', t: '[steɪt]', ru: 'Состояние, положение' },
    { en: 'mentoring', t: '[ˈmɛntɔːrɪŋ]', ru: 'Менторство' },
    { en: 'tiredness', t: '[ˈtaɪədnəs]', ru: 'Усталость' },
    {
        en: 'probation period',
        t: '[prəˈbeɪʃən ˈpɪərɪəd]',
        ru: 'Испытательный срок',
    },
    { en: 'expectation', t: '[ɛkspɛkˈteɪʃən]', ru: 'Ожидание' },
    { en: 'benefit', t: '[ˈbɛnɪfɪt]', ru: 'Прибыль' },
    { en: 'salary', t: '[ˈsæləri]', ru: 'Зарплата' },
    { en: 'outsource', t: '[aʊtˈsɔːs]', ru: 'Аутсорс' },
    { en: 'team', t: '[tiːm]', ru: 'Команда' },
    { en: 'lead', t: '[liːd]', ru: 'Лидер, тимлидер' },
    { en: 'project', t: '[ˈprɒʤɛkt]', ru: 'Проект' },
    { en: 'check out', t: '[ʧɛk aʊt]', ru: 'Проверка' },
    { en: 'research', t: '[rɪˈsɜːʧ]', ru: 'Исследование' },
    { en: 'routine', t: '[ruːˈtiːn ]', ru: 'Рутина' },
    { en: 'planner', t: '[ˈplænə]', ru: 'Планнер, блокнот' },
    { en: 'schedule', t: '[ˈʃɛdjuːl]', ru: 'Расписание' },
]

export default words
