const words = [
    { en: 'activist', t: '[ˈæktɪvɪst]', ru: 'Активист', ua: 'Активіст' },
    { en: 'pollution', t: '[pəˈluːʃən]', ru: 'Загрязнение', ua: 'Забруднення' },
    {
        en: 'impurity',
        t: '[ɪmˈpjʊərɪti]',
        ru: 'Примеси, загрязнение',
        ua: 'Домішки, забруднення',
    },
    { en: 'algae', t: '[ˈælʤiː]', ru: 'Водоросли', ua: 'Ворості' },
    { en: 'Earth', t: '[ɜːθ]', ru: 'Земля', ua: 'Земля' },
    { en: 'atmosphere', t: '[ˈætməsfɪə]', ru: 'Атмосфера', ua: 'Атмосфера' },
    {
        en: 'environment',
        t: '[ɪnˈvaɪərənmənt]',
        ru: 'Окружающий мир',
        ua: 'Навколишній світ',
    },
    { en: 'climate', t: '[ˈklaɪmɪt]', ru: 'Климат', ua: 'Клімат' },
    { en: 'air', t: '[eə]', ru: 'Воздух', ua: 'Повітря' },
    {
        en: 'water reserve',
        t: '[ˈwɔːtə rɪˈzɜːv]',
        ru: 'Водные ресурсы',
        ua: 'Водні ресурси',
    },
    {
        en: 'greenhouse effect',
        t: '[ˈgriːnhaʊs ɪˈfɛkt]',
        ru: 'Парниковый эффект',
        ua: 'Парниковий ефект',
    },
    { en: 'oxygen', t: '[ˈɒksɪʤən]', ru: 'Кислород', ua: 'Кисень' },
    { en: 'explorer', t: '[ɪksˈplɔːrə]', ru: 'Исследователь', ua: 'Дослідник' },
    {
        en: 'investigation',
        t: '[ɪnˌvɛstɪˈgeɪʃən]',
        ru: 'Расследование',
        ua: 'Розслідування',
    },
    { en: 'future', t: '[ˈfjuːʧə]', ru: 'Будущее', ua: 'Майбутнє' },
    {
        en: 'tropic forest',
        t: '[ˈtrɒpɪk ˈfɒrɪst]',
        ru: 'Тропический лес',
        ua: 'Тропічний ліс',
    },
    {
        en: 'humidity',
        t: '[hju(ː)ˈmɪdɪti]',
        ru: 'Влажность, влага',
        ua: 'Вологість, волога',
    },
    { en: 'flora', t: '[ˈflɔːrə]', ru: 'Флора', ua: 'Флора' },
    {
        en: 'wildlife',
        t: '[ˈwaɪldlaɪf]',
        ru: 'Дикая природа, животные',
        ua: 'Дика природа, тварини',
    },
    {
        en: 'plastic waste',
        t: '[ˈplæstɪk weɪst]',
        ru: 'Пластиковые отходы',
        ua: 'Пластикові відходи',
    },
    {
        en: 'А recycling',
        t: '[riːˈsaɪklɪŋ]',
        ru: 'Переработка',
        ua: 'Переробка',
    },
    {
        en: 'hydrosphere',
        t: '[ˈhaɪdrəʊsfɪə]',
        ru: 'Гидросфера',
        ua: 'Гідросфера',
    },
    { en: 'meeting', t: '[ˈmiːtɪŋ]', ru: 'Митинг', ua: 'Мітинг' },
    {
        en: 'background',
        t: '[ˈbækgraʊnd]',
        ru: 'Происхождение, фон',
        ua: 'Походження, фон',
    },
    { en: 'bank', t: '[bæŋk]', ru: 'Берег', ua: 'Берег' },
    { en: 'banner', t: '[ˈbænə]', ru: 'Баннер, реклама', ua: 'Банер, реклама' },
    { en: 'beast', t: '[biːst]', ru: 'Зверь, животное', ua: 'Звір, тварина' },
    { en: 'cave', t: '[keɪv]', ru: 'Пещера, грот', ua: 'Печера, грот' },
    { en: 'caviar', t: '[ˈkævɪɑː]', ru: 'Икра', ua: 'Ікра' },
    {
        en: 'charity',
        t: '[ˈʧærɪti]',
        ru: 'Благотворительность',
        ua: 'Благодійність',
    },
    { en: 'chemistry', t: '[ˈkɛmɪstri]', ru: 'Химия', ua: 'Хімія' },
    {
        en: 'economical use',
        t: '[iːkəˈnɒmɪkəl juːz&lt;]',
        ru: 'Экономное потребление',
        ua: 'Економне споживання',
    },
    { en: 'cohesion', t: '[kəʊˈhiːʒən]', ru: 'Уголь', ua: 'Вугілля' },
    {
        en: 'commitment',
        t: '[kəˈmɪtmənt]',
        ru: 'Обязательство',
        ua: "Зобов'язання",
    },
    {
        en: 'concern',
        t: '[kənˈsɜːn]',
        ru: 'Озабоченность',
        ua: 'Стурбованість',
    },
    {
        en: 'conscience',
        t: '[ˈkɒnʃəns]',
        ru: 'Совесть, сознание',
        ua: 'Совість, свідомість',
    },
    { en: 'court', t: '[kɔːt]', ru: 'Суд', ua: 'Суд' },
    {
        en: 'custody',
        t: '[ˈkʌstədi]',
        ru: 'Опека, сохранение',
        ua: 'Опіка, збереження',
    },
    { en: 'desert', t: '[ˈdɛzət]', ru: 'Пустыня', ua: 'Пустиня' },
    { en: 'dimension', t: '[dɪˈmɛnʃən]', ru: 'Разрушение', ua: 'Руйнування' },
    { en: 'disaster', t: '[dɪˈzɑːstə]', ru: 'Катастрофа', ua: 'Катастрофа' },
    { en: 'disease', t: '[dɪˈziːz]', ru: 'Заболевание', ua: 'Захворювання' },
    {
        en: 'downturn',
        t: '[ˈdaʊntɜːn]',
        ru: 'Убыток, спад',
        ua: 'Збиток, спад',
    },
    { en: 'drain', t: '[dreɪn]', ru: 'Сток, слив', ua: 'Сток, слив' },
    { en: 'emphasis', t: '[ˈɛmfəsɪs]', ru: 'Акцент', ua: 'Акцент' },
    { en: 'engine', t: '[ˈɛnʤɪn]', ru: 'Двигатель', ua: 'Двигун' },
    { en: 'evidence', t: '[ˈɛvɪdəns]', ru: 'Доказательство', ua: 'Доказ' },
    { en: 'excess', t: '[ɪkˈsɛs]', ru: 'Превышение', ua: 'Перевищення' },
    { en: 'famine', t: '[ˈfæmɪn]', ru: 'Голод', ua: 'Голод' },
    { en: 'detriment', t: '[ˈdɛtrɪmənt]', ru: 'Ущерб', ua: 'Збитки' },
]

export default words
