const words = [
    { en: 'activist', t: '[ˈæktɪvɪst]', ru: 'Активист' },
    { en: 'pollution', t: '[pəˈluːʃən]', ru: 'Загрязнение' },
    { en: 'impurity', t: '[ɪmˈpjʊərɪti]', ru: 'Примеси, загрязнение' },
    { en: 'algae', t: '[ˈælʤiː]', ru: 'Водоросли' },
    { en: 'Earth', t: '[ɜːθ]', ru: 'Земля' },
    { en: 'atmosphere', t: '[ˈætməsfɪə]', ru: 'Атмосфера' },
    { en: 'environment', t: '[ɪnˈvaɪərənmənt]', ru: 'Окружающий мир' },
    { en: 'climate', t: '[ˈklaɪmɪt]', ru: 'Климат' },
    { en: 'air', t: '[eə]', ru: 'Воздух' },
    { en: 'water reserve', t: '[ˈwɔːtə rɪˈzɜːv]', ru: 'Водные ресурсы' },
    {
        en: 'greenhouse effect',
        t: '[ˈgriːnhaʊs ɪˈfɛkt]',
        ru: 'Парниковый эффект',
    },
    { en: 'oxygen', t: '[ˈɒksɪʤən]', ru: 'Кислород' },
    { en: 'explorer', t: '[ɪksˈplɔːrə]', ru: 'Исследователь' },
    { en: 'investigation', t: '[ɪnˌvɛstɪˈgeɪʃən]', ru: 'Расследование' },
    { en: 'future', t: '[ˈfjuːʧə]', ru: 'Будущее' },
    { en: 'tropic forest', t: '[ˈtrɒpɪk ˈfɒrɪst]', ru: 'Тропический лес' },
    { en: 'humidity', t: '[hju(ː)ˈmɪdɪti]', ru: 'Влажность, влага' },
    { en: 'flora', t: '[ˈflɔːrə]', ru: 'Флора' },
    { en: 'wildlife', t: '[ˈwaɪldlaɪf]', ru: 'Дикая природа, животные' },
    { en: 'plastic waste', t: '[ˈplæstɪk weɪst]', ru: 'Пластиковые отходы' },
    { en: 'А recycling', t: '[riːˈsaɪklɪŋ]', ru: 'Переработка' },
    { en: 'hydrosphere', t: '[ˈhaɪdrəʊsfɪə]', ru: 'Гидросфера' },
    { en: 'meeting', t: '[ˈmiːtɪŋ]', ru: 'Митинг' },
    { en: 'background', t: '[ˈbækgraʊnd]', ru: 'Происхождение, фон' },
    { en: 'bank', t: '[bæŋk]', ru: 'Берег' },
    { en: 'banner', t: '[ˈbænə]', ru: 'Баннер, реклама' },
    { en: 'beast', t: '[biːst]', ru: 'Зверь, животное' },
    { en: 'cave', t: '[keɪv]', ru: 'Пещера, грот' },
    { en: 'caviar', t: '[ˈkævɪɑː]', ru: 'Икра' },
    { en: 'charity', t: '[ˈʧærɪti]', ru: 'Благотворительность' },
    { en: 'chemistry', t: '[ˈkɛmɪstri]', ru: 'Химия' },
    {
        en: 'economical use',
        t: '[iːkəˈnɒmɪkəl juːz&lt;]',
        ru: 'Экономное потребление',
    },
    { en: 'cohesion', t: '[kəʊˈhiːʒən]', ru: 'Уголь' },
    { en: 'commitment', t: '[kəˈmɪtmənt]', ru: 'Обязательство' },
    { en: 'concern', t: '[kənˈsɜːn]', ru: 'Озабоченность' },
    { en: 'conscience', t: '[ˈkɒnʃəns]', ru: 'Совесть, сознание' },
    { en: 'court', t: '[kɔːt]', ru: 'Суд' },
    { en: 'custody', t: '[ˈkʌstədi]', ru: 'Опека, сохранение' },
    { en: 'desert', t: '[ˈdɛzət]', ru: 'Пустыня' },
    { en: 'dimension', t: '[dɪˈmɛnʃən]', ru: 'Разрушение' },
    { en: 'disaster', t: '[dɪˈzɑːstə]', ru: 'Катастрофа' },
    { en: 'disease', t: '[dɪˈziːz]', ru: 'Заболевание' },
    { en: 'downturn', t: '[ˈdaʊntɜːn]', ru: 'Убыток, спад' },
    { en: 'drain', t: '[dreɪn]', ru: 'Сток, слив' },
    { en: 'emphasis', t: '[ˈɛmfəsɪs]', ru: 'Акцент' },
    { en: 'engine', t: '[ˈɛnʤɪn]', ru: 'Двигатель' },
    { en: 'evidence', t: '[ˈɛvɪdəns]', ru: 'Доказательство' },
    { en: 'excess', t: '[ɪkˈsɛs]', ru: 'Превышение' },
    { en: 'famine', t: '[ˈfæmɪn]', ru: 'Голод' },
    { en: 'detriment', t: '[ˈdɛtrɪmənt]', ru: 'Ущерб' },
]

export default words
