const words = [
    { en: 'cartoon', t: '[kɑːˈtuːn]', ru: 'Мультфильм' },
    { en: 'movie', t: '[ˈmuːvi]', ru: 'Фильм' },
    { en: 'circus', t: '[ˈsɜːkəs]', ru: 'Цирк' },
    { en: 'composer', t: '[kəmˈpəʊzə]', ru: 'Композитор' },
    { en: 'dream', t: '[driːm]', ru: 'Мечта' },
    { en: 'daily routine', t: '[ˈdeɪli ruːˈtiːn]', ru: 'Ежедневная рутина' },
    { en: 'horror', t: '[ˈhɒrə]', ru: 'Ужастик' },
    { en: 'laughter', t: '[ˈlɑːftə]', ru: 'Смех' },
    { en: 'novel', t: '[ˈnɒvəl]', ru: 'Роман' },
    { en: 'story', t: '[ˈstɔːri]', ru: 'История' },
    { en: 'weather forecast', t: '[ˈwɛðə ˈfɔːkɑːst]', ru: 'Прогноз погоды' },
    { en: 'thought', t: '[θɔːt]', ru: 'Мысль' },
    { en: 'writer', t: '[ˈraɪtə]', ru: 'Писатель' },
    { en: 'access', t: '[ˈæksɛs]', ru: 'Доступ' },
    { en: 'account', t: '[əˈkaʊnt]', ru: 'Аккаунт' },
    { en: 'adventure', t: '[ədˈvɛnʧə]', ru: 'Приключение' },
    { en: 'affair', t: '[əˈfeə]', ru: 'Страх' },
    { en: 'anniversary', t: '[ænɪˈvɜːsəri]', ru: 'Дело, интрига' },
    { en: 'entertainment', t: '[ɛntəˈteɪnmənt]', ru: 'Развлечение' },
    { en: 'amusement', t: '[əˈmjuːzmənt]', ru: 'Веселье' },
    { en: 'influence', t: '[ˈɪnflʊəns]', ru: 'Влияние' },
    {
        en: 'attraction',
        t: '[əˈtrækʃ(ə)n]',
        ru: 'Достопримечательность, аттракцион',
    },
    { en: 'rock-climbing', t: '[rɒk-ˈklaɪmɪŋ]', ru: 'Скалолазание' },
    { en: 'cycling', t: '[ˈsaɪklɪŋ]', ru: 'Катание на велосипеде' },
    {
        en: 'number painting',
        t: '[ˈnʌmbə ˈpeɪntɪŋ]',
        ru: 'Живопись по номерам',
    },
    { en: 'swimming pool', t: '[ˈswɪmɪŋ puːl]', ru: 'Бассейн' },
    { en: 'yoga', t: '[ˈjəʊgə]', ru: 'Йога' },
    { en: 'coffee shop', t: '[ˈkɒfi ʃɒp]', ru: 'Кофейня' },
    { en: 'central park', t: '[ˈsɛntrəl pɑːk]', ru: 'Центральный парк' },
    { en: 'inspiration', t: '[ɪnspəˈreɪʃən]', ru: 'Вдохновение' },
    { en: 'scenery', t: '[ˈsiːnəri]', ru: 'Пейзаж' },
    { en: 'landscape', t: '[ˈlænskeɪp]', ru: 'Ландшафт, пейзаж' },
    { en: 'computer game', t: '[kəmˈpjuːtə geɪm]', ru: 'Компьютерная игра' },
    { en: 'mood', t: '[muːd]', ru: 'Настроение' },
    { en: 'situation', t: '[sɪtjʊˈeɪʃən]', ru: 'Ситуация' },
    { en: 'movement', t: '[ˈmuːvmənt]', ru: 'Движение' },
    { en: 'arrangement', t: '[əˈreɪnʤmənt]', ru: 'Договоренность' },
    { en: 'accommodation', t: '[əˌkɒməˈdeɪʃ(ə)n]', ru: 'Жилье' },
    { en: 'beverage', t: '[ˈbɛvərɪʤ]', ru: 'Напиток' },
    { en: 'binge', t: '[bɪnʤ]', ru: 'Гулянка' },
]

export default words
