const words = [
    { en: 'cartoon', t: '[kɑːˈtuːn]', ru: 'Мультфильм', ua: 'Мультфільм' },
    { en: 'movie', t: '[ˈmuːvi]', ru: 'Фильм', ua: 'Фільм' },
    { en: 'circus', t: '[ˈsɜːkəs]', ru: 'Цирк', ua: 'Цирк' },
    { en: 'composer', t: '[kəmˈpəʊzə]', ru: 'Композитор', ua: 'Композитор' },
    { en: 'dream', t: '[driːm]', ru: 'Мечта', ua: 'Мрія' },
    {
        en: 'daily routine',
        t: '[ˈdeɪli ruːˈtiːn]',
        ru: 'Ежедневная рутина',
        ua: 'Щоденна рутина',
    },
    { en: 'horror', t: '[ˈhɒrə]', ru: 'Ужастик', ua: 'Жахіття' },
    { en: 'laughter', t: '[ˈlɑːftə]', ru: 'Смех', ua: 'Сміх' },
    { en: 'novel', t: '[ˈnɒvəl]', ru: 'Роман', ua: 'Роман' },
    { en: 'story', t: '[ˈstɔːri]', ru: 'История', ua: 'Історія' },
    {
        en: 'weather forecast',
        t: '[ˈwɛðə ˈfɔːkɑːst]',
        ru: 'Прогноз погоды',
        ua: 'Прогноз погоди',
    },
    { en: 'thought', t: '[θɔːt]', ru: 'Мысль', ua: 'Думка' },
    { en: 'writer', t: '[ˈraɪtə]', ru: 'Писатель', ua: 'Письменник' },
    { en: 'access', t: '[ˈæksɛs]', ru: 'Доступ', ua: 'Доступ' },
    { en: 'account', t: '[əˈkaʊnt]', ru: 'Аккаунт', ua: 'Акаунт' },
    { en: 'adventure', t: '[ədˈvɛnʧə]', ru: 'Приключение', ua: 'Пригода' },
    { en: 'affair', t: '[əˈfeə]', ru: 'Страх', ua: 'Страх' },
    {
        en: 'anniversary',
        t: '[ænɪˈvɜːsəri]',
        ru: 'Дело, интрига',
        ua: 'Справа, інтрига',
    },
    {
        en: 'entertainment',
        t: '[ɛntəˈteɪnmənt]',
        ru: 'Развлечение',
        ua: 'Розвага',
    },
    { en: 'amusement', t: '[əˈmjuːzmənt]', ru: 'Веселье', ua: 'Весілля' },
    { en: 'influence', t: '[ˈɪnflʊəns]', ru: 'Влияние', ua: 'Вплив' },
    {
        en: 'attraction',
        t: '[əˈtrækʃ(ə)n]',
        ru: 'Достопримечательность, аттракцион',
        ua: "Пам'ятки, атракціон",
    },
    {
        en: 'rock-climbing',
        t: '[rɒk-ˈklaɪmɪŋ]',
        ru: 'Скалолазание',
        ua: 'Скелолазіння',
    },
    {
        en: 'cycling',
        t: '[ˈsaɪklɪŋ]',
        ru: 'Катание на велосипеде',
        ua: ' Катання на велосипеді',
    },
    {
        en: 'number painting',
        t: '[ˈnʌmbə ˈpeɪntɪŋ]',
        ru: 'Живопись по номерам',
        ua: 'Живопис за номерами',
    },
    { en: 'swimming pool', t: '[ˈswɪmɪŋ puːl]', ru: 'Бассейн', ua: 'Басейн' },
    { en: 'yoga', t: '[ˈjəʊgə]', ru: 'Йога', ua: 'Йога' },
    { en: 'coffee shop', t: '[ˈkɒfi ʃɒp]', ru: 'Кофейня', ua: "Кав'ярня" },
    {
        en: 'central park',
        t: '[ˈsɛntrəl pɑːk]',
        ru: 'Центральный парк',
        ua: 'Центральний парк',
    },
    {
        en: 'inspiration',
        t: '[ɪnspəˈreɪʃən]',
        ru: 'Вдохновение',
        ua: 'Натхнення',
    },
    { en: 'scenery', t: '[ˈsiːnəri]', ru: 'Пейзаж', ua: 'Пейзаж' },
    {
        en: 'landscape',
        t: '[ˈlænskeɪp]',
        ru: 'Ландшафт, пейзаж',
        ua: 'Ландшафт, пейзаж',
    },
    {
        en: 'computer game',
        t: '[kəmˈpjuːtə geɪm]',
        ru: 'Компьютерная игра',
        ua: "Комп'ютерна гра",
    },
    { en: 'mood', t: '[muːd]', ru: 'Настроение', ua: 'Настрій' },
    { en: 'situation', t: '[sɪtjʊˈeɪʃən]', ru: 'Ситуация', ua: 'Ситуація' },
    { en: 'movement', t: '[ˈmuːvmənt]', ru: 'Движение', ua: 'Рух' },
    {
        en: 'arrangement',
        t: '[əˈreɪnʤmənt]',
        ru: 'Договоренность',
        ua: 'Домовленість',
    },
    { en: 'accommodation', t: '[əˌkɒməˈdeɪʃ(ə)n]', ru: 'Жилье', ua: 'Житло' },
    { en: 'beverage', t: '[ˈbɛvərɪʤ]', ru: 'Напиток', ua: 'Напій' },
    { en: 'binge', t: '[bɪnʤ]', ru: 'Гулянка', ua: 'Гулянка' },
]

export default words
