const words = [
    { en: 'To appear', t: '[əˈpɪə]', ru: 'Появляться' },
    { en: 'To cancel', t: '[ˈkænsəl]', ru: 'Отменять' },
    { en: 'To bite', t: '[baɪt]', ru: 'Кусать, укусить' },
    { en: 'To regret', t: '[rɪˈgrɛt ]', ru: 'Сожалеть' },
    { en: 'To blow', t: '[bləʊ]', ru: 'Дуть (о ветре), развеять, раздувать' },
    { en: 'To compose', t: '[kəmˈpəʊz]', ru: 'Составлять' },
    { en: 'To congratulate', t: '[kənˈgrætjʊleɪt]', ru: 'Поздравлять' },
    { en: 'To correct', t: '[kəˈrɛkt]', ru: 'Исправлять' },
    { en: 'To fall asleep', t: '[fɔːl əˈsliːp]', ru: 'Засыпать' },
    { en: 'To burn', t: '[bɜːn]', ru: 'Гореть' },
    { en: 'To invent', t: '[ɪnˈvɛnt]', ru: 'Придумать, изобретать' },
    { en: 'To mention', t: '[ˈmɛnʃən]', ru: 'Упоминать, заметить, отметить' },
    { en: 'To suppose', t: '[səˈpəʊz]', ru: 'Предполагать' },
    { en: 'To suggest', t: '[səˈʤɛst]', ru: 'Предлагать, намекать' },
    { en: 'To consider', t: '[kənˈsɪdə]', ru: 'Размышлять, учитывать' },
    { en: 'To escape', t: '[ɪsˈkeɪp]', ru: 'Сбегать, убегать' },
    { en: 'To publish', t: '[ˈpʌblɪʃ]', ru: 'Публиковать' },
    { en: 'To solve', t: '[sɒlv]', ru: 'Решить, разгадать' },
    { en: 'To tidy up', t: '[ˈtaɪdi ʌp]', ru: 'Убираться, наводить порядок' },
    { en: 'To win', t: '[‘taɪdi ʌp]', ru: 'Выиграть' },
    { en: 'To swallow', t: '[ˈswɒləʊ]', ru: 'Глотать' },
    { en: 'To follow', t: '[ˈfɒləʊ]', ru: 'Следовать' },
    { en: 'To abandon', t: '[əˈbændən]', ru: 'Покидать, оставлять' },
    { en: 'To be able', t: '[biː ˈeɪbl]', ru: 'Быть в состоянии' },
    { en: 'To abuse', t: '[əˈbjuːs]', ru: 'Оскорблять' },
    { en: 'To accelerate', t: '[əkˈsɛləreɪt]', ru: 'Ускорять' },
    { en: 'To reveal', t: '[rɪˈviːl]', ru: 'Раскрывать' },
    { en: 'To consist of', t: '[kənˈsɪst ɒv]', ru: 'Состоять из' },
    { en: 'To include', t: '[ɪnˈkluːd]', ru: 'Включать' },
    { en: 'To guess', t: '[gɛs]', ru: 'Думать, предполагать' },
    { en: 'To accept', t: '[əkˈsɛpt]', ru: 'Одобрять, согласовать' },
    { en: 'To formulate', t: '[ˈfɔːmjʊleɪt]', ru: 'Формулировать' },
    { en: 'To form', t: '[fɔːm]', ru: 'Формировать' },
    { en: 'To achieve', t: '[əˈʧiːv]', ru: 'Достигать' },
    { en: 'To acknowledge', t: '[əkˈnɒlɪʤ]', ru: 'Подтверждать' },
    { en: 'To act', t: '[ækt]', ru: 'Действовать' },
    { en: 'To adhere', t: '[ədˈhɪə]', ru: 'Придерживаться' },
    { en: 'To admire', t: '[ədˈmaɪə]', ru: 'Восхищаться' },
    { en: 'To adjust', t: '[əˈʤʌst]', ru: 'Адаптировать, настроить' },
    { en: 'To advise', t: '[ədˈvaɪz]', ru: 'Советовать' },
    { en: 'To allow', t: '[əˈlaʊ]', ru: 'Позволять, разрешать' },
    { en: 'To improve', t: '[ɪmˈpruːv]', ru: 'Улучшать' },
    { en: 'To edit', t: '[ˈɛdɪt]', ru: 'Редактировать' },
    { en: 'To conclude', t: '[kənˈkluːd]', ru: 'Включать в себя' },
    { en: 'To settle', t: '[ˈsɛtl]', ru: 'Располагаться, поселиться' },
    { en: 'To handle', t: '[ˈhændl]', ru: 'Справиться' },
    { en: 'To boost', t: '[buːst]', ru: 'Увеличить, поддержать' },
    { en: 'To amplify', t: '[ˈæmplɪfaɪ]', ru: 'Усилить, расширить' },
    { en: 'To appeal', t: '[əˈpiːl]', ru: 'Просить, обращаться' },
    { en: 'To assemble', t: '[əˈsɛmbl]', ru: 'Собираться, созывать' },
    { en: 'To assess', t: '[əˈsɛs]', ru: 'Оценивать, рассматривать' },
    { en: 'To assist', t: '[əˈsɪst]', ru: 'Присутствовать, помогать' },
    { en: 'To astonish', t: '[əsˈtɒnɪʃ]', ru: 'Удивлять' },
    { en: 'To assure', t: '[əˈʃʊə]', ru: 'Убеждать, заверять' },
    { en: 'To avoid', t: '[əˈvɔɪd]', ru: 'Избегать' },
    { en: 'To await', t: '[əˈweɪt]', ru: 'Ожидать' },
    { en: 'To pick up', t: '[pɪk ʌp]', ru: 'Подбирать, забирать' },
    { en: 'To cross off', t: '[krɒs ɒf]', ru: 'Вычеркивать' },
    { en: 'To claim', t: '[kleɪm]', ru: 'Утверждать, заявлять' },
    { en: 'To hurry up', t: '[ˈhʌri ʌp]', ru: 'Торопиться' },
    { en: 'To find out', t: '[faɪnd aʊt]', ru: 'Находить' },
    { en: 'To divide', t: '[dɪˈvaɪd]', ru: 'Делить, разделять' },
    { en: 'To bark', t: '[bɑːk]', ru: 'Лаять' },
    { en: 'To bathe', t: '[beɪð]', ru: 'Купаться' },
    { en: 'To beat', t: '[biːt]', ru: 'Бить, превосходить' },
    { en: 'To blackmail', t: '[ˈblækmeɪl]', ru: 'Шантажировать' },
    { en: 'To spent', t: '[spɛnt]', ru: 'Тратить' },
    { en: 'To send', t: '[sɛnd]', ru: 'Посылать' },
    { en: 'To laugh', t: '[lɑːf]', ru: 'Смеяться' },
    { en: 'To struggle', t: '[ˈstrʌgl]', ru: 'Бороться' },
    { en: 'To motivate', t: '[ˈməʊtɪveɪt]', ru: 'Мотивировать' },
    { en: 'To perceive', t: '[pəˈsiːv ]', ru: 'Воспринимать' },
    { en: 'To receive', t: '[rɪˈsiːv]', ru: 'Получать' },
    { en: 'To recognize', t: '[ˈrɛkəgnaɪz]', ru: 'Распознавать' },
    { en: 'To remain', t: '[rɪˈmeɪn]', ru: 'Напоминать' },
    { en: 'To retain', t: '[ rɪˈteɪn]', ru: 'Удержать' },
    { en: 'To remember', t: '[rɪˈmɛmbə]', ru: 'Помнить, запоминать' },
    { en: 'To observed', t: '[əbˈzɜːvd]', ru: 'Исследовать' },
    { en: 'To fight', t: '[faɪt]', ru: 'Драться' },
    { en: 'To renew', t: '[rɪˈnju]', ru: 'Обновлять' },
    { en: 'To keep calm', t: '[kiːp kɑːm]', ru: 'Успокаиваться' },
    { en: 'To break up', t: '[breɪk ʌp]', ru: 'Разрушать, расходиться' },
    { en: 'To focus', t: '[ˈfəʊkəs]', ru: 'Фокусироваться' },
    { en: 'To perform', t: '[pəˈfɔːm]', ru: 'Исполнять обязанности' },
    { en: 'To offer', t: '[ˈɒfə]', ru: 'Предлагать' },
    { en: 'To display', t: '[dɪsˈpleɪ]', ru: 'Отображать' },
    { en: 'To behave', t: '[bɪˈheɪv]', ru: 'Вести себя' },
    { en: 'To get rid', t: '[gɛt rɪd]', ru: 'Избавляться' },
    { en: 'To squeeze', t: '[skwiːz]', ru: 'Выжимать' },
    { en: 'To release', t: '[rɪˈliːs]', ru: 'Выпускать, публиковать' },
    { en: 'To push', t: '[pʊʃ]', ru: 'Толкать' },
    { en: 'To foster', t: '[ˈfɒstə]', ru: 'Поощрять' },
    { en: 'To enhance', t: '[ɪnˈhɑːns]', ru: 'Расширять, поощрять' },
    { en: 'To develop', t: '[dɪˈvɛləp]', ru: 'Развивать, разрабатывать' },
    { en: 'To envelop', t: '[ɪnˈvɛləp]', ru: 'Окутывать, обволакивать' },
    { en: 'To obtain', t: '[əbˈteɪn]', ru: 'Получить, добиться, приобрести' },
    { en: 'To investigate', t: '[ɪnˈvɛstɪgeɪt]', ru: 'Расследовать' },
    { en: 'To adore', t: '[əˈdɔː]', ru: 'Обожать' },
    { en: 'To block out', t: '[blɒk aʊt]', ru: 'Блокировать' },
    { en: 'To boil', t: '[bɔɪl]', ru: 'Кипеть' },
    { en: 'To bother', t: '[ˈbɒðə]', ru: 'Побеспокоить, заморачиваться' },
    { en: 'To breathe', t: '[briːð]', ru: 'Дышать' },
    { en: 'To brew', t: '[bruː]', ru: 'Варить, заваривать' },
    { en: 'To celebrate', t: '[ˈsɛlɪbreɪt]', ru: 'Отмечать' },
    { en: 'To broadcast', t: '[ˈbrɔːdkɑːst]', ru: 'Вещать, транслировать' },
    { en: 'To modify', t: '[ˈmɒdɪfaɪ]', ru: 'Изменять, модифицировать' },
    { en: 'To bump', t: '[bʌmp]', ru: 'Ударять' },
    { en: 'To buzz', t: '[bʌz]', ru: 'Жужжать' },
    { en: 'To lead', t: '[liːd]', ru: 'Вести, лидировать, быть лидером' },
    { en: 'To call back', t: '[kɔːl bæk]', ru: 'Перезвонить' },
    { en: 'To waste', t: '[weɪst]', ru: 'Тратить впустую, мусорить' },
    { en: 'To take care', t: '[teɪk keə]', ru: 'Заботиться' },
    { en: 'To carry out', t: '[ˈkæri aʊt]', ru: 'Выполнять, осуществлять' },
    { en: 'To carve', t: '[kɑːv]', ru: 'Вырезать' },
    { en: 'To cease', t: '[siːs]', ru: 'Прекратить' },
    { en: 'To collaborate', t: '[kəˈlæbəreɪt]', ru: 'Сотрудничать' },
    { en: 'To reward', t: '[rɪˈwɔːd]', ru: 'Награждать' },
    { en: 'To come back', t: '[kʌm bæk]', ru: 'Возвращаться' },
    { en: 'To relate', t: '[rɪˈleɪt]', ru: 'Относиться, касаться' },
    { en: 'To upgrade', t: '[ʌpˈgreɪd]', ru: 'Обновлять' },
    { en: 'To restore', t: '[rɪsˈtɔː]', ru: 'Восстановить' },
    { en: 'To describe', t: '[dɪsˈkraɪb]', ru: 'Описывать' },
    { en: 'To share', t: '[ʃeə]', ru: 'Делиться' },
    { en: 'To increase', t: '[ˈɪnkriːs]', ru: 'Увеличивать' },
    { en: 'To automate', t: '[ˈɔːtəmeɪt]', ru: 'Автоматизировать' },
    { en: 'To manage', t: '[ˈmænɪʤ]', ru: 'Управлять' },
    { en: 'To provide', t: '[prəˈvaɪd]', ru: 'Обеспечивать' },
    { en: 'To integrate', t: '[ˈɪntɪgreɪt]', ru: 'Соединять, интегрировать' },
    { en: 'To realize', t: '[ˈrɪəlaɪz]', ru: 'Реализовывать, осуществлять' },
    { en: 'To remind', t: '[ˈrɪmaɪnd]', ru: 'Напоминать' },
    { en: 'To install', t: '[ɪnˈstɔːl]', ru: 'Устанавливать' },
    { en: 'To download', t: '[daʊnˈləʊd]', ru: 'Загружать' },
    { en: 'To unpack', t: '[ʌnˈpæk]', ru: 'Распаковать' },
    { en: 'To engage', t: '[ɪnˈgeɪʤ]', ru: 'Увлечь, привлечь' },
    { en: 'To create', t: '[kri(ː)ˈeɪt]', ru: 'Создавать' },
    { en: 'To prefer', t: '[priˈfɜː]', ru: 'Предпочитать' },
    { en: 'To inspire', t: '[ɪnˈspaɪə]', ru: 'Вдохновлять' },
    { en: 'To apply', t: '[əˈplaɪ]', ru: 'Применять' },
    { en: 'To explain', t: '[ɪksˈpleɪn]', ru: 'Объяснять' },
    { en: 'To simplify', t: '[ˈsɪmplɪfaɪ]', ru: 'Упрощать' },
    { en: 'To strive', t: '[straɪv]', ru: 'Стремиться' },
    { en: 'To arrive', t: '[əˈraɪv]', ru: 'Прибывать' },
    { en: 'To enable', t: '[ɪˈneɪbl]', ru: 'Разрешить, включить' },
    { en: 'To support', t: '[səˈpɔːt]', ru: 'Поддерживать' },
    { en: 'To allot', t: '[əˈlɒt]', ru: 'Выделить' },
    { en: 'To empower', t: '[ɪmˈpaʊə]', ru: 'Разрешать, уполномочить' },
    { en: 'To overwhelm', t: '[əʊvəˈwɛlm]', ru: 'Переполнять' },
    { en: 'To fulfill', t: '[fʊlˈfɪl]', ru: 'Выполнять' },
    { en: 'To take over', t: '[teɪk ˈəʊvə]', ru: 'Принять на себя' },
    { en: 'To encourage', t: '[ɪnˈkʌrɪʤ]', ru: 'Поощрять' },
    { en: 'To stimulate', t: '[ˈstɪmjʊleɪt]', ru: 'Стимулировать' },
    { en: 'To cause', t: '[kɔːz]', ru: 'Вызывать' },
    { en: 'To deal', t: '[diːl]', ru: 'Справляться' },
    { en: 'To reach', t: '[riːʧ]', ru: 'Достигать' },
    { en: 'To touch', t: '[tʌʧ]', ru: 'Прикасаться' },
    { en: 'To attain', t: '[əˈteɪn]', ru: 'Достигать, получать' },
    { en: 'To require', t: '[rɪˈkwaɪə]', ru: 'Запрашивать, требовать' },
    { en: 'To figure out', t: '[ˈfɪgər aʊt]', ru: 'Разбираться' },
    { en: 'To forgive', t: '[fəˈgɪv]', ru: 'Прощать' },
    { en: 'To light', t: '[laɪt]', ru: 'Освещать, светить' },
    { en: 'To shine', t: '[ʃaɪn]', ru: 'Сиять' },
    { en: 'To spread', t: '[sprɛd]', ru: 'Распространять' },
    { en: 'To throw', t: '[θrəʊ]', ru: 'Бросать' },
    { en: 'To spoil', t: '[spɔːɪl]', ru: 'Испортить' },
    { en: 'To split', t: '[splɪt]', ru: 'Разбить, разделить' },
    { en: 'To go mad', t: '[gəʊ mæd]', ru: 'Сходить с ума' },
    { en: 'To steal', t: '[stiːl]', ru: 'Украсть' },
    { en: 'To smell', t: '[smɛl]', ru: 'Пахнуть' },
]

export default words
