const words = [
    { en: 'Inaccessible', t: '[ˌɪnækˈsɛsəbl]', ru: 'Недоступный' },
    { en: 'Pioneering', t: '[ˌpaɪəˈnɪərɪŋ]', ru: 'Новаторский, первый' },
    { en: 'Astonishing', t: '[əsˈtɒnɪʃɪŋ]', ru: 'Поразительный' },
    {
        en: 'Eccentric',
        t: '[ɪkˈsɛntrɪk]',
        ru: 'Эксцентричный, экстравагантный',
    },
    { en: 'Ethnographic', t: '[ˌɛθnəʊˈgræfɪk]', ru: 'Этнографический' },
    { en: 'Quintessential', t: '[ˌkwɪntɪˈsɛnʃəl]', ru: 'Полный, оригинальный' },
    { en: 'Colonial', t: '[kəˈləʊniəl]', ru: 'Колониальный' },
    { en: 'Religious', t: '[rɪˈlɪʤəs]', ru: 'Религиозный' },
    {
        en: 'Multi-sensory',
        t: '[ˈmʌltɪ-ˈsɛnsəri]',
        ru: 'Мультисенсорный, чувственный',
    },
    {
        en: 'Life-threatening',
        t: '[laɪf-ˈθrɛtnɪŋ]',
        ru: 'Опасный для жизни, угрожающий',
    },
    { en: 'Subsequent', t: '[ˈsʌbsɪkwənt]', ru: 'Последующий, дальнейший' },
    { en: 'Uneventful', t: '[ˌʌnɪˈvɛntfʊl]', ru: 'Беспристрастный' },
    { en: 'Insightful', t: '[ˈɪnsaɪtf(ə)l]', ru: 'Проницательный' },
    { en: 'Apparent', t: '[əˈpærənt]', ru: 'Очевидный' },
    { en: 'Disrespectful', t: '[ˌdɪsrɪsˈpɛktfʊl]', ru: 'Неуважительный' },
    { en: 'Inefficient', t: '[ˌɪnɪˈfɪʃənt]', ru: 'Неэффективный' },
    { en: 'Abnormal', t: '[æbˈnɔːməl]', ru: 'Аномальный' },
    {
        en: 'Detectable',
        t: '[dɪˈtɛktəbl]',
        ru: 'Обнаруживаемый, различимый, выявляемый',
    },
    { en: 'Cellular', t: '[ˈsɛljʊlə]', ru: 'Клеточный' },
    {
        en: 'Counterintuitive',
        t: '[kaʊntərɪnˈtjuːɪtɪv]',
        ru: 'Нелогичный, противоречивый, парадоксальный',
    },
    { en: 'Disparate', t: '[ˈdɪspərɪt]', ru: 'Разрозненный, несопоставимый' },
    { en: 'Excessive', t: '[ɪkˈsɛsɪv]', ru: 'Чрезмерный, избыточный' },
    {
        en: 'Detrimental',
        t: '[ˌdɛtrɪˈmɛntl]',
        ru: 'Пагубный, губительный, вредный',
    },
    {
        en: 'Indecisive',
        t: '[ˌɪndɪˈsaɪsɪv]',
        ru: 'Нерешительный, неопределенный, неясный',
    },
    {
        en: 'Resilient',
        t: '[rɪˈzɪlɪənt]',
        ru: 'Устойчивый, упругий, эластичный',
    },
    { en: 'Adverse', t: '[ˈædvɜːs]', ru: 'Неблагоприятный, негативный' },
    {
        en: 'Manageable',
        t: '[ˈmænɪʤəbl]',
        ru: 'Управляемый, поддающийся, преодолимый',
    },
    { en: 'Ingenious', t: '[ɪnˈʤiːniəs]', ru: 'Изобретательный, оригинальный' },
    { en: 'Free-roaming', t: '[friː-ˈrəʊmɪŋ]', ru: 'Свободный' },
    { en: 'Harsh', t: '[hɑːʃ]', ru: 'Суровый, резкий, жесткий, грубый' },
    { en: 'Warm-blooded', t: '[wɔːm-ˈblʌdɪd]', ru: 'Теплокровный' },
    { en: 'Ground-breaking', t: '[graʊnd-ˈbreɪkɪŋ]', ru: 'Новаторский' },
    { en: 'Uninhabitable', t: '[ˌʌnɪnˈhæbɪtəbl]', ru: 'Непригодный для жизни' },
    { en: 'Hilarious', t: '[hɪˈleərɪəs]', ru: 'Уморительный, веселый' },
    {
        en: 'Unconscious',
        t: '[ʌnˈkɒnʃəs]',
        ru: 'Бессознательный, неосознанный',
    },
    { en: 'Reproducible', t: '[ˌriːprəˈdjuːsəbl]', ru: 'Воспроизводимый' },
    { en: 'Grim', t: '[grɪm]', ru: 'Мрачный, грозный' },
    { en: 'Irrefutable', t: '[ɪˈrɛfjʊtəbl]', ru: 'Неопровержимый' },
    {
        en: 'Simplistic',
        t: '[sɪmˈplɪstɪk]',
        ru: 'Упрощённый, простой, простодушный',
    },
    { en: 'Disastrous', t: '[dɪˈzɑːstrəs]', ru: 'Катастрофический' },
    { en: 'Scarce', t: '[skeəs]', ru: 'Скудный, дефицитный' },
    { en: 'Vicious', t: '[ˈvɪʃəs]', ru: 'Злобный, порочный, ужасный' },
]

export default words
