const words = [
    { en: 'Axis', t: '[ˈæksɪs]', ru: 'Ось' },
    { en: 'modality', t: '[məʊˈdælɪti]', ru: 'Метод, форма' },
    { en: 'Discerning', t: '[dɪˈsɜːnɪŋ]', ru: 'распознавание' },
    { en: 'Similarity', t: '[sɪmɪˈlærɪti]', ru: 'Сходство, подобие, аналогия' },
    { en: 'Pattern', t: '[pætən]', ru: 'Образец, модель, схема' },
    {
        en: 'Sequencing',
        t: '[ˈsiːkwənsɪŋ]',
        ru: 'Последовательность, порядок, упорядочивание',
    },
    { en: 'Anthropologist', t: '[ˌænθrəˈpɒləʤɪst]', ru: 'Антрополог' },
    { en: 'Oversight', t: '[ˈəʊvəsaɪt]', ru: 'Надзор, контроль' },
    { en: 'Exhibition', t: '[ˌɛksɪˈbɪʃən]', ru: 'Выставка' },
    { en: 'Specimen', t: '[ˈspɛsɪmɪn]', ru: 'Образец, модель, экспонат' },
    {
        en: 'Interference',
        t: '[ˌɪntəˈfɪərəns]',
        ru: 'Интерференция, вмешательство',
    },
    { en: 'Bureaucracy', t: '[bjʊəˈrɒkrəsi]', ru: 'Бюрократия' },
    { en: 'Generation', t: '[ˌʤɛnəˈreɪʃən]', ru: 'Поколение' },
    { en: 'Evolutionist', t: '[ˌiːvəˈluːʃənɪst]', ru: 'Эволюционист' },
    {
        en: 'Significance',
        t: '[sɪgˈnɪfɪkəns]',
        ru: 'Значение, значимость, важность',
    },
    { en: 'Unveiling', t: '[ʌnˈveɪlɪŋ]', ru: 'Разоблачение, раскрытие' },
    {
        en: 'Implication',
        t: '[ˌɪmplɪˈkeɪʃən]',
        ru: 'Следствие, последствие, подтекст, влияние',
    },
    { en: 'Biomarker', t: '[ˈbaɪəʊˈmɑːkə]', ru: 'Биомаркер' },
    { en: 'Offspring', t: '[ˈɒfsprɪŋ]', ru: 'Потомство' },
    { en: 'Cognition', t: '[kɒgˈnɪʃən]', ru: 'Познание' },
    {
        en: 'Prevalence',
        t: '[kɒgˈnɪʃən]',
        ru: 'Распространенность, превалирование, предрасположенность',
    },
    { en: 'Conjecture', t: '[kənˈʤɛkʧə]', ru: 'Догадка, гипотеза' },
    { en: 'Percentage', t: '[pəˈsɛntɪʤ]', ru: 'Процент, процентовка' },
    { en: 'Existence', t: '[ɪgˈzɪstəns]', ru: 'Существование, наличие' },
    { en: 'Assertion', t: '[əˈsɜːʃ(ə)n]', ru: 'Утверждение, заявление' },
    {
        en: 'Correlation',
        t: '[ˌkɒrɪˈleɪʃən]',
        ru: 'Соотношение, корреляция, взаимосвязь',
    },
    { en: 'Cohort', t: '[ˈkəʊhɔːt]', ru: 'Когорта, выборка, совокупность' },
    { en: 'Extent', t: '[ɪksˈtɛnt]', ru: 'Протяженность, объем, степень' },
    {
        en: 'Coherence',
        t: '[kəʊˈhɪərəns]',
        ru: 'Когерентность, слаженность, связь',
    },
    { en: 'Abstractedness', t: '[æbˈstræktɪdnɪs]', ru: 'Абстрактность' },
    { en: 'Gist', t: '[ʤɪst]', ru: 'Суть, сущность, понятие, смысл' },
    {
        en: 'Likelihood',
        t: '[ˈlaɪklɪhʊd]',
        ru: 'Вероятность, правдоподобность, достоверность',
    },
    { en: 'Instance', t: '[ˈɪnstəns]', ru: 'Экземпляр, объект, вариант' },
    { en: 'Vindication', t: '[ˌvɪndɪˈkeɪʃən]', ru: 'Доказательство' },
    {
        en: 'Ambiguity',
        t: '[ˌæmbɪˈgju(ː)ɪti]',
        ru: 'Двусмысленность, неоднозначность',
    },
]

export default words
