const words = [
    { en: 'Earthquake', t: '[ˈɜːθkweɪk]', ru: 'Землетрясение' },
    { en: 'Stillness', t: '[ˈstɪlnəs]', ru: 'Неподвижность, штиль, затишье' },
    {
        en: 'Contamination',
        t: '[kənˌtæmɪˈneɪʃən]',
        ru: 'Загрязнение, заражение',
    },
    { en: 'Lifespan', t: '[ˈlaɪfspæn]', ru: 'Продолжительность жизни' },
    { en: 'Predator', t: '[ˈprɛdətə]', ru: 'Хищник' },
    { en: 'Overpopulation', t: '[ˌəʊvəˌpɒpjʊˈleɪʃən]', ru: 'Перенаселение' },
    { en: 'Aftermath', t: '[ˈɑːftəmæθ]', ru: 'Последствия' },
    { en: 'Wasteland', t: '[ˈweɪstˌlænd]', ru: 'Пустошь' },
    { en: 'Grassland', t: '[ˈgrɑːslænd]', ru: 'Пастбище' },
    { en: 'Cattle', t: '[ˈkætl]', ru: 'Крупный рогатый скот' },
    { en: 'Carbon emission', t: '[ˈkɑːbən ɪˈmɪʃən]', ru: 'Выброс углерода' },
    {
        en: 'Deteriorating',
        t: '[dɪˈtɪərɪəreɪtɪŋ]',
        ru: 'Ухудшение, деградация',
    },
    { en: 'Erasure', t: '[ɪˈreɪʒə]', ru: 'Стирание' },
    { en: 'Drought', t: '[draʊt]', ru: 'Засуха' },
    { en: 'Dieback', t: '[ˈdaɪˌbæk]', ru: 'Вымирание' },
    { en: 'Foraging', t: '[ˈfɒrɪʤɪŋ]', ru: 'Кормление' },
    { en: 'Breeding', t: '[ˈbriːdɪŋ]', ru: 'Размножение' },
    { en: 'Fluctuation', t: '[ˌflʌktjʊˈeɪʃən]', ru: 'Колебания, зыбкость' },
    {
        en: 'Resilience',
        t: '[rɪˈzɪlɪəns]',
        ru: 'Жизнеспособность, устойчивость',
    },
    { en: 'Hedgerow', t: '[ˈhɛʤrəʊ]', ru: 'Живая изгородь' },
    { en: 'Ditche', t: '[dɪtʃ]]', ru: 'Канава, траншея, сточная яма' },
    { en: 'Coastal', t: '[ˈkəʊstəl]', ru: 'Прибрежная зона' },
    { en: 'Combustion', t: '[kəmˈbʌsʧən]', ru: 'Сжигание, горение' },
    { en: 'Restoration', t: '[ˌrɛstəˈreɪʃən]', ru: 'Восстановление' },
    { en: 'Disturbance', t: '[dɪsˈtɜːbəns]', ru: 'Нарушение, вмешательство' },
    {
        en: 'Encroachment',
        t: '[ɪnˈkrəʊʧmənt]',
        ru: 'Вторжение, захват, поглощение',
    },
    { en: 'Photosynthesis', t: '[ˌfəʊtəʊˈsɪnθɪsɪs]', ru: 'Фотосинтез' },
    {
        en: 'Annihilation',
        t: '[əˌnaɪəˈleɪʃ(ə)n]',
        ru: 'Уничтожение, разрушение, удаление',
    },
    { en: 'Overload', t: '[ˈəʊvələʊd]', ru: 'Перегрузка' },
    {
        en: 'Biodiversity',
        t: '[ˌbaɪəʊdaɪˈvɜːsɪti]',
        ru: 'Биологическое разнообразие',
    },
    { en: 'Sustenance', t: '[ˈsʌstɪnəns]', ru: 'Пропитание, питание' },
    { en: 'Limestone', t: '[ˈlaɪmstəʊn]', ru: 'Известняк' },
    {
        en: 'Sequestration',
        t: '[ˌsiːkwɛsˈtreɪʃən]',
        ru: 'Секвестрация, поглощение',
    },
    { en: 'Wilderness', t: '[ˈwɪldənɪs]', ru: 'Дикая природа' },
]

export default words
