const words = [
    { en: 'To abate', t: '[əˈbeɪt]', ru: 'Сокращать, уменшать, ослаблять' },
    {
        en: 'To abjure',
        t: '[əbˈʤʊə]',
        ru: 'Отказаться, отрекаться, воздерживаться',
    },
    { en: 'To dangle', t: '[ˈdæŋgl]', ru: 'Болтаться, зависать, висеть' },
    { en: 'To abscond', t: '[əbˈskɒnd]', ru: 'Скрыться, пропасть, уйти' },
    { en: 'To assuage', t: '[əˈsweɪʤ]', ru: 'Успокаивать, утешать, усмирять' },
    {
        en: 'To disabuse',
        t: '[ˌdɪsəˈbjuːz]',
        ru: 'Разочаровать, расстроить, развенчать',
    },
    {
        en: 'To equivocate',
        t: '[ɪˈkwɪvəkeɪt]',
        ru: 'Увиливать, оправдываться, оспаривать',
    },
    { en: 'To incise', t: '[ɪnˈsaɪz]', ru: 'Надрезать' },
    { en: 'To diminish', t: '[dɪˈmɪnɪʃ]', ru: 'Уменьшать' },
    { en: 'To jeopardize', t: '[ˈʤɛpədaɪz]', ru: 'Ставить под угрозу' },
    { en: 'To breed', t: '[briːd]', ru: 'Размножаться' },
    { en: 'To prevaricate', t: '[prɪˈværɪkeɪt]', ru: 'Преувеличивать' },
    { en: 'To recant', t: '[rɪˈkænt]', ru: 'Отказаться от показаний' },
    { en: 'To refute', t: '[rɪˈfjuːt]', ru: 'Опровергать' },
    { en: 'To ignoble', t: '[ɪgˈnəʊbl]', ru: 'Обольстить' },
    { en: 'To banish', t: '[ˈbænɪʃ', ru: 'Изгнать' },
    { en: 'To disavow', t: '[ˌdɪsəˈvaʊ]', ru: 'Отречься' },
    { en: 'To explode', t: '[ɪksˈpləʊd]', ru: 'Взорваться' },
    { en: 'To unearth', t: '[ ʌnˈɜːθ]', ru: 'Раскопать' },
    { en: 'To depict', t: '[dɪˈpɪkt]', ru: 'Отобразить' },
    { en: 'To unpick', t: '[ʌnˈpɪk]', ru: 'Распарывать, распустить' },
    { en: 'To originate', t: '[əˈrɪʤɪneɪt]', ru: 'Зарождаться' },
    { en: 'To pluck', t: '[plʌk]', ru: 'Вырывать' },
    { en: 'To amass', t: '[əˈmæs]', ru: 'Накапливать' },
    { en: 'To staff', t: '[stɑːf]', ru: 'Укомплектовать' },
    { en: 'To shrink', t: '[ʃrɪŋk]', ru: 'Сокращаться' },
    { en: 'To mold', t: '[məʊld]', ru: 'Лепить' },
    { en: 'To contrive', t: '[kənˈtraɪv]', ru: 'Придумывать' },
    { en: 'To entice', t: '[ɪnˈtaɪs]', ru: 'Завлекать' },
    { en: 'To pervade', t: '[pɜːˈveɪd]', ru: 'Пронизывать' },
    { en: 'To prevail', t: '[prɪˈveɪl]', ru: 'Преобладать' },
    { en: 'To supersede', t: '[ˌsjuːpəˈsiːd]', ru: 'Вытеснять' },
    { en: 'To redeem', t: '[rɪˈdiːm]', ru: 'Выкупить' },
    { en: 'To wrack', t: '[ræk]', ru: 'Потревожить' },
    { en: 'To mesh', t: '[mɛʃ]', ru: 'Зацеплять' },
    { en: 'To render', t: '[ˈrɛndə]', ru: 'Оказывать' },
    { en: 'To lease', t: '[liːs]', ru: 'Сдать в аренду' },
    { en: 'To stipulate', t: '[ˈstɪpjʊleɪt]', ru: 'Оговаривать' },
    { en: 'To decree', t: '[dɪˈkriː]', ru: 'Постановить' },
    { en: 'To reminisce', t: '[ˌrɛmɪˈnɪs]', ru: 'Вспоминать' },
    { en: 'To rarefy', t: '[ˈreərɪfaɪ]', ru: 'Редеть' },
    { en: 'To venerate', t: '[ˈvɛnəreɪt]', ru: 'Почитать' },
    { en: 'To hatch', t: '[hæʧ]', ru: 'Вылупляться' },
    { en: 'To anchor', t: '[ˈæŋkə]', ru: 'Бросить якорь' },
    { en: 'To inherit', t: '[ɪnˈhɛrɪt]', ru: 'Получить в наследство' },
    { en: 'To stab', t: '[stæb]', ru: 'Закалывать, нападать, вонзать' },
    { en: 'To sublet', t: '[ˌsʌbˈlɛt]', ru: 'Сдавать в субаренду' },
    {
        en: 'To outline',
        t: '[ˈaʊtlaɪn]',
        ru: 'Начертить, обрисовать, наметить',
    },
    {
        en: 'To infiltrate',
        t: '[ˈɪnfɪltreɪt]',
        ru: 'Проникнуь, внедриться, просачиваться',
    },
    { en: 'To utter', t: '[ˈʌtə]', ru: 'Произносить, изрекать, проговаривать' },
    { en: 'To vituperate', t: '[vɪˈtjuːpəreɪt]', ru: 'Издеваться, обижать' },
    { en: 'To waver', t: '[ˈweɪvə]', ru: 'Колебаться, извиваться, дрогнуть' },
    {
        en: 'To withstand',
        t: '[wɪðˈstænd]',
        ru: 'Выдерживать, устоять, терпеть',
    },
    { en: 'To swap', t: '[swɒp]', ru: 'Поменять местами, сменить' },
    { en: 'To coax', t: '[kəʊks]', ru: 'Соединить' },
    { en: 'To conspire', t: '[kənˈspaɪə]', ru: 'Сговориться' },
    { en: 'To append', t: '[əˈpɛnd]', ru: 'Приложить' },
    { en: 'To entail', t: '[ɪnˈteɪl]', ru: 'Влечь за собой' },
    { en: 'To repine', t: '[rɪˈpaɪn]', ru: 'Порицать' },
    { en: 'To glance', t: '[glɑːns]', ru: 'Бросить взгляд, мельком глянуть' },
    { en: 'To resort', t: '[rɪˈzɔːt]', ru: 'Прибегать' },
    { en: 'To substitute', t: '[ˈsʌbstɪtjuːt]', ru: 'Заменить' },
    { en: 'To surpass', t: '[sɜːˈpɑːs]', ru: 'Превзойти' },
    { en: 'To deem', t: '[diːm]', ru: 'Считать' },
    { en: 'To prophesy', t: '[ˈprɒfɪsaɪ]', ru: 'Пророчествовать' },
    { en: 'To unveil', t: '[ʌnˈveɪl]', ru: 'Раскрыть' },
    {
        en: 'To discard',
        t: '[ˈdɪskɑːd]',
        ru: 'Отказаться, списывать, отвергнуть',
    },
    { en: 'To eradicate', t: '[ɪˈrædɪkeɪt]', ru: 'Искоренить' },
    { en: 'To propagate', t: '[ˈprɒpəgeɪt]', ru: 'Распространять' },
    { en: 'To terminate', t: '[ˈtɜːmɪneɪt]', ru: 'Прекратить' },
    { en: 'To engross', t: '[ɪnˈgrəʊs]', ru: 'Захватить' },
    {
        en: 'To overtake',
        t: '[ˌəʊvəˈteɪk]',
        ru: 'Обгонять, нагнать, преодолеть',
    },
    { en: 'To shield', t: '[ ʃiːld]', ru: 'Укрыть, заслонить, оградить' },
    { en: 'To ingest', t: '[ɪnˈʤɛst]', ru: 'Проглотить' },
    { en: 'To malign', t: '[məˈlaɪn]', ru: 'Очернить' },
    { en: 'To exhibit', t: '[ɪgˈzɪbɪt]', ru: 'Выставлять' },
    { en: 'To extirpate', t: '[ˈɛkstɜːpeɪt]', ru: 'Уничтожить' },
    { en: 'To initiate', t: '[ɪˈnɪʃɪɪt]', ru: 'Инициировать' },
    { en: 'To adjoy', t: '[ ædʤɔɪ]', ru: 'Придерживаться' },
    { en: 'To delve', t: '[dɛlv]', ru: 'Углубиться' },
    { en: 'to vow', t: '[ vaʊ]', ru: 'Клясться, ручаться, обещать' },
    { en: 'to alienate', t: '[ˈeɪliəneɪt]', ru: 'отчуждать' },
    { en: 'to reimburse', t: '[ˌriːɪmˈbɜːs]', ru: 'возмещать' },
    { en: 'to disperse', t: '[dɪsˈpɜːs]', ru: 'Рассеивать, расходиться' },
    { en: 'to overlook', t: '[ˌəʊvəˈlʊk]', ru: 'упускать из виду' },
    {
        en: 'to dismantle',
        t: '[dɪsˈmæntl]',
        ru: 'Демонтировать, разобрать, убрать, разрушить',
    },
    { en: 'to exhilarate', t: '[ɪgˈzɪləreɪt]', ru: 'взбодриться' },
    { en: 'to thrill', t: '[θrɪl]', ru: 'возбуждать' },
    { en: 'to underpin', t: '[ˌʌndəˈpɪn]', ru: 'поддерживать' },
    { en: 'to follow-up', t: '[ˈfɒləʊˈʌp]', ru: 'следить' },
    {
        en: 'to predispose',
        t: '[ˌpriːdɪsˈpəʊz]',
        ru: 'Предрасполагать, склонять, располагать',
    },
    { en: 'to peer', t: '[pɪə]', ru: 'Равняться, сравнивать, подглядывать' },
    { en: 'to intervene', t: '[ˌɪntə(ː)ˈviːn]', ru: 'вмешиваться' },
    { en: 'to resonate', t: '[ˈrɛzəˌneɪt]', ru: 'резонировать' },
    {
        en: 'to contradict',
        t: '[ˌkɒntrəˈdɪkt]',
        ru: 'Противоречить, возражать, опровергнуть',
    },
    {
        en: 'to distil',
        t: '[dɪsˈtɪl]',
        ru: 'Дистиллировать, смягчать, рассеивать',
    },
    { en: 'to mitigate', t: '[ˈmɪtɪgeɪt]', ru: 'Смягчать, сгладить, ослабить' },
    {
        en: 'to bounce back',
        t: '[baʊns bæk]',
        ru: 'Отскочить, вернуться, возвращаться, восстановиться',
    },
    {
        en: 'To indulge',
        t: '[ɪnˈdʌlʤ]',
        ru: 'Побаловать, потакать, потворствовать',
    },
    { en: 'To sniff', t: '[snɪf]', ru: 'Нюхать, принюхиваться, сопеть' },
]

export default words
