const words = [
    { en: 'Afraid', t: '[əˈfreɪd]', ru: 'Напуганный', ua: 'Схвильований' },
    { en: 'Angry', t: '[ˈæŋɡri]', ru: 'Сердитый', ua: 'розлючений' },
    { en: 'Asleep', t: '[əˈsliːp]', ru: 'Спящий', ua: 'сплячий' },
    { en: 'Attentive', t: '[əˈten.tɪv]', ru: 'Внимательный', ua: 'уважний' },
    { en: 'Available', t: '[əˈveɪləbl]', ru: 'Доступный', ua: 'доступний' },
    { en: 'Basic', t: '[ˈbeɪsɪk]', ru: 'Базовый', ua: 'базовий' },
    { en: 'Beautiful', t: '[ˈbjuːtɪfl]', ru: 'Красивый', ua: 'красивий' },
    { en: 'Big', t: '[bɪɡ]', ru: 'Большой', ua: 'великий' },
    { en: 'Brave', t: '[breɪv]', ru: 'Смелый', ua: 'хоробрий' },
    { en: 'Busy', t: '[ˈbɪzi]', ru: 'Занятой', ua: 'зайнятий' },
    { en: 'Calm', t: '[kɑːm]', ru: 'Спокойный', ua: 'спокійний' },
    {
        en: 'Careful',
        t: '[ˈkeəfl]',
        ru: 'Внимательный, заботливый',
        ua: 'обережний',
    },
    { en: 'Cheap', t: '[tʃiːp]', ru: 'Дешевый', ua: 'дешевий' },
    { en: 'Clean', t: '[kliːn]', ru: 'Чистый', ua: 'чистий' },
    { en: 'Clever', t: '[ˈklevə(r)]', ru: 'Умный', ua: 'розумний' },
    { en: 'Cold', t: '[kəʊld]', ru: 'Холодный', ua: 'холодний' },
    {
        en: 'Comfortable',
        t: '[ˈkʌmftəbl]',
        ru: 'Комфортный',
        ua: 'комфортабельний',
    },
    { en: 'Confident', t: '[ˈkɒnfɪdənt]', ru: 'Уверенный', ua: 'впевнений' },
    { en: 'Constant', t: '[ˈkɒnstənt]', ru: 'Постоянный', ua: 'постійний' },
    { en: 'Curious', t: '[ˈkjʊəriəs]', ru: 'Любопытный', ua: 'допитливий' },
    { en: 'Dangerous', t: '[ˈdeɪndʒərəs]', ru: 'Опасный', ua: 'небезпечний' },
    { en: 'Dark', t: '[dɑːk]', ru: 'Темный', ua: 'темний' },
    { en: 'Deep', t: '[diːp]', ru: 'Глубокий', ua: 'глибокий' },
    { en: 'Different', t: '[ˈdɪfrənt]', ru: 'Разный', ua: 'різний' },
    { en: 'Difficult', t: '[ˈdɪfɪkəlt]', ru: 'Трудный', ua: 'складний' },
    { en: 'Dirty', t: '[ˈdɜːti]', ru: 'Грязный', ua: 'брудний' },
    { en: 'Easy', t: '[ˈiːzi]', ru: 'Легкий', ua: 'легкий' },
    { en: 'Every', t: '[ˈevri]', ru: 'Каждый', ua: 'кожен' },
    { en: 'Expensive', t: '[ɪkˈspensɪv]', ru: 'Дорогой', ua: 'дорогий' },
    { en: 'Exact', t: '[ɪɡˈzækt]', ru: 'Точный', ua: 'точний' },
    { en: 'Fast', t: '[fɑːst]', ru: 'Быстрый', ua: 'швидкий' },
    { en: 'Fair', t: '[feə(r)]', ru: 'Честный, светлый', ua: 'справедливий' },
    { en: 'Fine', t: '[faɪn]', ru: 'Замечательный', ua: 'добре' },
    { en: 'Foreign', t: '[ˈfɒrən]', ru: 'Иностранный', ua: 'іноземний' },
    { en: 'Free', t: '[friː]', ru: 'Свободный', ua: 'вільний' },
    { en: 'Fresh', t: '[freʃ]', ru: 'Свежий', ua: 'свіжий' },
    { en: 'Full', t: '[fʊl]', ru: 'Полный', ua: 'повний' },
    { en: 'Funny', t: '[ˈfʌni]', ru: 'Забавный', ua: 'смішний' },
    { en: 'Guilty', t: '[ˈɡɪlti]', ru: 'Виновный', ua: 'винний' },
    { en: 'Healthy', t: '[ˈhelθi]', ru: 'Здоровый', ua: 'здоровий' },
    { en: 'Hard', t: '[hɑːd]', ru: 'Тяжелый', ua: 'важкий' },
    { en: 'Helpful', t: '[ˈhelpfl]', ru: 'Полезный', ua: 'корисний' },
    { en: 'Honest', t: '[ˈɒnɪst]', ru: 'Честный', ua: 'чесний' },
    { en: 'Hot', t: '[hɒt]', ru: 'Горячий', ua: 'гарячий' },
    { en: 'Hungry', t: '[ˈhʌŋɡri]', ru: 'Голодный', ua: 'голодний' },
    { en: 'Important', t: '[ɪmˈpɔːtnt]', ru: 'Важный', ua: 'важливий' },
    {
        en: 'Illegal',
        t: '[ɪˈliːɡl]',
        ru: 'Нелегальный, незаконный',
        ua: 'нелегальний',
    },
    { en: 'Impossible', t: '[ɪmˈpɒsəbl]', ru: 'Невозможный', ua: 'неможливий' },
    {
        en: 'Independent',
        t: '[ˌɪndɪˈpendənt]',
        ru: 'Независимый',
        ua: 'незалежний',
    },
    { en: 'Interesting', t: '[ˈɪntrəstɪŋ]', ru: 'Интересный', ua: 'цікавий' },
    { en: 'Kind', t: '[kaɪnd]', ru: 'Добрый', ua: 'добрий' },
    { en: 'Legal', t: '[ˈliːɡl]', ru: 'Законный', ua: 'законний' },
    { en: 'Little', t: '[ˈlɪtl]', ru: 'Маленький', ua: 'малий' },
    { en: 'Lucky', t: '[ˈlʌki]', ru: 'Удачливый', ua: 'щасливий' },
    { en: 'Necessary', t: '[ˈnesəsəri]', ru: 'Необходимый', ua: 'необхідний' },
    { en: 'Normal', t: '[ˈnɔːml]', ru: 'Нормальный', ua: 'нормальний' },
    { en: 'Old', t: '[əʊld]', ru: 'Старый', ua: 'старий' },
    {
        en: 'Opposite',
        t: '[ˈɒpəzɪt]',
        ru: 'Противоположный',
        ua: 'протилежний',
    },
    { en: 'Perfect', t: '[pəˈfekt]', ru: 'Идеальный', ua: 'ідеальний' },
    { en: 'Poor', t: '[pɔː(r)]', ru: 'Бедный', ua: 'бідний' },
    { en: 'Powerful', t: '[ˈpaʊəfl]', ru: 'Мощный', ua: 'потужний' },
    { en: 'Possible', t: '[ˈpɒsəbl]', ru: 'Возможный', ua: 'можливий' },
    { en: 'Quiet', t: '[ˈkwaɪət]', ru: 'Тихий', ua: 'тихий' },
    { en: 'Rare', t: '[reə(r)]', ru: 'Редкий', ua: 'рідкісний' },
    { en: 'Recent', t: '[ˈriːsnt]', ru: 'Недавний', ua: 'недавній' },
    {
        en: 'Relevant',
        t: '[ˈreləvənt]',
        ru: 'Релевантный, актуальный',
        ua: 'відповідний',
    },
    { en: 'Remote', t: '[rɪˈməʊt]', ru: 'Удаленный', ua: 'віддалений' },
    { en: 'Safe', t: '[seɪf]', ru: 'Безопасный', ua: 'безпечний' },
    { en: 'Short', t: '[ʃɔːt]', ru: 'Короткий', ua: 'короткий' },
    { en: 'Small', t: '[smɔːl]', ru: 'Маленький', ua: 'малий' },
    {
        en: 'Strange',
        t: '[streɪndʒ]',
        ru: 'Странный, незнакомый, чужой',
        ua: 'дивний',
    },
    { en: 'Successful', t: '[səkˈsesfl]', ru: 'Успешный', ua: 'успішний' },
    { en: 'Tasty', t: '[ˈteɪ.sti]', ru: 'Вкусный, приятный', ua: 'смачний' },
    { en: 'Terrible', t: '[ˈterəbl]', ru: 'Жуткий', ua: 'жахливий' },
    { en: 'Tired', t: '[ˈtaɪəd]', ru: 'Усталый', ua: 'втомлений' },
    { en: 'Warm', t: '[wɔːm]', ru: 'Теплый', ua: 'теплий' },
    { en: 'Weak', t: '[wiːk]', ru: 'Слабый', ua: 'слабкий' },
    {
        en: 'Responsible',
        t: '[rɪˈspɒnsəbl]',
        ru: 'Ответственный, надежный',
        ua: 'відповідальний',
    },
    { en: 'Sad', t: '[sæd]', ru: 'Грустный', ua: 'сумний' },
    {
        en: 'International',
        t: '[ˌɪntəˈnæʃnəl]',
        ru: 'Международный',
        ua: 'міжнародний',
    },
]

export default words
