const words = [
    { en: 'Together', t: '[təˈɡeðə(r)]', ru: 'Вместе', ua: 'Разом' },
    { en: 'According', t: '[əˈkɔːdɪŋ]', ru: 'В соответствии', ua: 'згідно з' },
    { en: 'Again', t: '[əˈɡen]', ru: 'Снова', ua: 'знову' },
    { en: 'Always', t: '[ˈɔːlweɪz]', ru: 'Всегда', ua: 'завжди' },
    { en: 'Beautifully', t: '[ˈbjuːtɪfli]', ru: 'Красиво', ua: 'красиво' },
    { en: 'Carefully', t: '[ˈkeə.fəl.i]', ru: 'Осторожно', ua: 'обережно' },
    {
        en: 'Correctly',
        t: '[kəˈrektli]',
        ru: 'Верно, правильно',
        ua: 'правильно',
    },
    { en: 'Especially', t: '[ɪˈspeʃəli]', ru: 'Особенно', ua: 'особливо' },
    { en: 'Friendly', t: '[ˈfrendli]', ru: 'Дружелюбно', ua: 'дружньо' },
    { en: 'Indeed', t: '[ɪnˈdiːd]', ru: 'Действительно', ua: 'відповідно' },
    { en: 'Above', t: '[əˈbʌv]', ru: 'Выше', ua: 'вище' },
    {
        en: 'Accidentally',
        t: '[ˌæk.sɪˈden.təl.i]',
        ru: 'Случайно',
        ua: 'випадково',
    },
    { en: 'Actually', t: '[ˈæktʃuəli]', ru: 'На самом деле', ua: 'фактично' },
    { en: 'Badly', t: '[ˈbædli]', ru: 'Плохо', ua: 'погано' },
    { en: 'Besides', t: '[bɪˈsaɪdz]', ru: 'Помимо этого', ua: 'крім того' },
    { en: 'Briefly', t: '[ˈbriːfli]', ru: 'Кратко', ua: 'коротко' },
    { en: 'Certainly', t: '[ˈsɜːtnli]', ru: 'Конечно', ua: 'безперечно' },
    { en: 'Daily', t: '[ˈdeɪli]', ru: 'Ежедневно', ua: 'щоденно' },
    { en: 'Dreamily', t: '[ˈdriː.mɪ.li]', ru: 'Мечтательно', ua: 'мрійливо' },
    { en: 'Even', t: '[ˈiːvn]', ru: 'Даже', ua: 'навіть' },
    {
        en: 'Eventually',
        t: '[ɪˈventʃuəli]',
        ru: 'В конце концов',
        ua: 'врешті-решт',
    },
    { en: 'Foolishly', t: '[ˈfuːlɪʃli]', ru: 'Глупо', ua: 'дурно' },
    { en: 'Forward', t: '[ˈfɔːwəd]', ru: 'Вперед', ua: 'вперед' },
    { en: 'Ever', t: '[ˈevə(r)]', ru: 'Когда-либо', ua: 'завжди' },
    { en: 'Equally', t: '[ˈiːkwəli]', ru: 'Одинаково', ua: 'рівно' },
    {
        en: 'Fortunately',
        t: '[ˈfɔː.tʃən.ət.li]',
        ru: 'К счастью',
        ua: 'щасливо',
    },
    { en: 'Honestly', t: '[ˈɒnɪstli]', ru: 'Честно', ua: 'чесно' },
    { en: 'Instead', t: '[ɪnˈsted]', ru: 'Вместо', ua: 'замість' },
    { en: 'Inside', t: '[ˌɪnˈsaɪd]', ru: 'Внутри', ua: 'всередині' },
    { en: 'Also', t: '[ˈɔːlsəʊ]', ru: 'Также', ua: 'також' },
    { en: 'Hardly', t: '[ˈhɑːdli]', ru: 'С трудом', ua: 'ледве' },
    { en: 'Lately', t: '[ˈleɪt.li]', ru: 'Недавно', ua: 'недавно' },
    { en: 'Less', t: '[les]', ru: 'Меньше', ua: 'менше' },
    { en: 'Loudly', t: '[ˈlaʊd.li]', ru: 'Громко, шумно', ua: 'голосно' },
    { en: 'Nearly', t: '[ˈnɪəli]', ru: 'Около', ua: 'майже' },
    { en: 'Never', t: '[ˈnevə(r)]', ru: 'Никогда', ua: 'ніколи' },
    { en: 'Only', t: '[ˈəʊnli]', ru: 'Только', ua: 'лише' },
    { en: 'Once', t: '[wʌns]', ru: 'Один раз', ua: 'один раз' },
    { en: 'Often', t: '[ˈɒfn]', ru: 'Часто', ua: 'часто' },
    { en: 'Perhaps', t: '[pəˈhæps]', ru: 'Возможно', ua: 'можливо' },
    { en: 'Quickly', t: '[ˈkwɪkli]', ru: 'Быстро', ua: 'швидко' },
    { en: 'Probably', t: '[ˈprɒbəbli]', ru: 'Вероятно', ua: 'мабуть' },
    { en: 'Rarely', t: '[ˈreəli]', ru: 'Редко', ua: 'рідко' },
    { en: 'Really', t: '[ˈriːəli]', ru: 'Действительно', ua: 'дійсно' },
    { en: 'Sometimes', t: '[ˈsʌmtaɪmz]', ru: 'Иногда', ua: 'іноді' },
    { en: 'Yesterday', t: '[ˈjestədeɪ]', ru: 'Вчера', ua: 'вчора' },
    { en: 'Thus', t: '[ðʌs]', ru: 'Таким образом', ua: 'таким чином' },
    { en: 'Somehow', t: '[ˈsʌmhaʊ]', ru: 'Как-то', ua: 'якось' },
    { en: 'Soon', t: '[suːn]', ru: 'Скоро', ua: 'скоро' },
    { en: 'Regularly', t: '[ˈreɡjələli]', ru: 'Регулярно', ua: 'регулярно' },
    { en: 'Somewhere', t: '[ˈsʌmweə(r)]', ru: 'Где-то', ua: 'десь' },
]

export default words
