const words = [
    { en: 'boy', t: 'Мальчик', ru: '[bɔɪ]', ua: 'Разом' },
    { en: 'girl', t: 'Девочка', ru: '[ɡɜːl]', ua: 'згідно з' },
    { en: 'mother', t: 'Мама', ru: '[ˈmʌðə(r)]', ua: 'знову' },
    { en: 'father', t: 'Отец', ru: '[ˈfɑːðə(r)]', ua: 'завжди' },
    { en: 'son', t: 'Сын', ru: '[sʌn]', ua: 'красиво' },
    { en: 'daughter', t: 'Дочь', ru: '[ˈdɔːtə(r)]', ua: 'обережно' },
    { en: 'baby', t: 'Малыш', ru: '[ˈbeɪbi]', ua: 'правильно' },
    { en: 'family', t: 'Семья', ru: '[ˈfæməli]', ua: 'особливо' },
    { en: 'grand mother', t: 'Бабушка', ru: '[ɡrænd ˈməT͟Hər]', ua: 'дружньо' },
    {
        en: 'grand father',
        t: 'Дедушка',
        ru: '[ɡrænd ˈfɑːðə(r)]',
        ua: 'відповідно',
    },
    { en: 'children', t: 'Дети', ru: '[ˈtʃɪl.drən]', ua: 'вище' },
    { en: 'home', t: 'Дом', ru: '[həʊm]', ua: 'випадково' },
    { en: 'love', t: 'Любовь', ru: '[lʌv]', ua: 'фактично' },
    { en: 'apartment', t: 'Квартира', ru: '[əˈpɑːtmənt]', ua: 'погано' },
    { en: 'joy', t: 'Радость', ru: '[dʒɔɪ]', ua: 'крім того' },
    { en: 'nephew', t: 'Племянник', ru: '[ˈnefjuː]', ua: 'коротко' },
    { en: 'aunt', t: 'Тетя', ru: '[ɑːnt]', ua: 'безперечно' },
    { en: 'uncle', t: 'Дядя', ru: '[ˈʌŋkl]', ua: 'щоденно' },
    {
        en: 'cousin',
        t: 'Двоюродная сестра или брат',
        ru: '[ˈkʌzn]',
        ua: 'мрійливо',
    },
    { en: 'man', t: 'Мужчина', ru: '[mæn]', ua: 'навіть' },
    { en: 'woman', t: 'Женщина', ru: '[ˈwʊmən]', ua: 'врешті-решт' },
    { en: 'child', t: 'Ребенок', ru: '[tʃaɪld]', ua: 'дурно' },
    { en: 'sister', t: 'Сестра', ru: '[ˈsɪstə(r)]', ua: 'вперед' },
    { en: 'brother', t: 'Брат', ru: '[ˈbrʌðə(r)]', ua: 'завжди' },
    { en: 'Relatives', t: 'Родственники', ru: '[ˈrel.ə.tɪv]', ua: 'рівно' },
    { en: 'friend', t: 'Друг', ru: '[frend]', ua: 'щасливо' },
    { en: 'wife', t: 'Жена', ru: '[waɪf]', ua: 'чесно' },
    { en: 'husband', t: 'Муж', ru: '[ˈhʌzbənd]', ua: 'замість' },
    { en: 'address', t: 'Адрес', ru: '[əˈdres]', ua: 'всередині' },
    { en: 'happiness', t: 'Счастье', ru: '[ˈhæp.i.nəs]', ua: 'також' },
    { en: 'People', t: 'Люди', ru: '[ˈpiːpl]', ua: 'ледве' },
]

export default words
