const words = [
    { en: 'boy', t: '[bɔɪ]', ru: 'Мальчик', ua: 'Хлопчик' },
    { en: 'girl', t: '[ɡɜːl]', ru: 'Девочка', ua: 'Дівчинка' },
    { en: 'mother', t: '[ˈmʌðə(r)]', ru: 'Мама', ua: 'Мама' },
    { en: 'father', t: '[ˈfɑːðə(r)]', ru: 'Отец', ua: 'Батько' },
    { en: 'son', t: '[sʌn]', ru: 'Сын', ua: 'Син' },
    { en: 'daughter', t: '[ˈdɔːtə(r)]', ru: 'Дочь', ua: 'Дочка' },
    { en: 'baby', t: '[ˈbeɪbi]', ru: 'Малыш', ua: 'Малюк' },
    { en: 'family', t: '[ˈfæməli]', ru: 'Семья', ua: "Сім'я" },
    { en: 'grand mother', t: '[ɡrænd ˈməT͟Hər]', ru: 'Бабушка', ua: 'Бабуся' },
    { en: 'grand father', t: '[ɡrænd ˈfɑːðə(r)]', ru: 'Дедушка', ua: 'Дідусь' },
    { en: 'children', t: '[ˈtʃɪl.drən]', ru: 'Дети', ua: 'Діти' },
    { en: 'home', t: '[həʊm]', ru: 'Дом', ua: 'Дім' },
    { en: 'love', t: '[lʌv]', ru: 'Любовь', ua: 'Кохання' },
    { en: 'apartment', t: '[əˈpɑːtmənt]', ru: 'Квартира', ua: 'Квартира' },
    { en: 'joy', t: '[dʒɔɪ]', ru: 'Радость', ua: 'Радість' },
    { en: 'nephew', t: '[ˈnefjuː]', ru: 'Племянник', ua: 'Племінник' },
    { en: 'aunt', t: '[ɑːnt]', ru: 'Тетя', ua: 'Тітка' },
    { en: 'uncle', t: '[ˈʌŋkl]', ru: 'Дядя', ua: 'Дядько' },
    {
        en: 'cousin',
        t: '[ˈkʌzn]',
        ru: 'Двоюродная сестра или брат',
        ua: 'Двоюрідна сестра чи брат',
    },
    { en: 'man', t: '[mæn]', ru: 'Мужчина', ua: 'Чоловік' },
    { en: 'woman', t: '[ˈwʊmən]', ru: 'Женщина', ua: 'Жінка' },
    { en: 'child', t: '[tʃaɪld]', ru: 'Ребенок', ua: 'Дитина' },
    { en: 'sister', t: '[ˈsɪstə(r)]', ru: 'Сестра', ua: 'Сестра' },
    { en: 'brother', t: '[ˈbrʌðə(r)]', ru: 'Брат', ua: 'Брат' },
    { en: 'Relatives', t: '[ˈrel.ə.tɪv]', ru: 'Родственники', ua: 'Родичі' },
    { en: 'friend', t: '[frend]', ru: 'Друг', ua: 'Друг' },
    { en: 'wife', t: '[waɪf]', ru: 'Жена', ua: 'Дружина' },
    { en: 'husband', t: '[ˈhʌzbənd]', ru: 'Муж', ua: 'Чоловік' },
    { en: 'address', t: '[əˈdres]', ru: 'Адрес', ua: 'Адреса' },
    { en: 'happiness', t: '[ˈhæp.i.nəs]', ru: 'Счастье', ua: 'Щастя' },
    { en: 'People', t: '[ˈpiːpl]', ru: 'Люди', ua: 'Люди' },
]

export default words
