const words = [
    { en: 'phone', t: '[fəʊn]', ru: 'Телефон', ua: 'телефон' },
    { en: 'question', t: '[ˈkwestʃən]', ru: 'Вопрос', ua: 'питання' },
    { en: 'place', t: '[pleɪs]', ru: 'Место', ua: 'місце' },
    { en: 'market', t: '[ˈmɑːkɪt]', ru: 'Рынок', ua: 'ринок' },
    { en: 'order', t: '[ˈɔːdə(r)]', ru: 'Заказ', ua: 'замовлення' },
    { en: 'food', t: '[fuːd]', ru: 'Еда', ua: 'їжа' },
    { en: 'work', t: '[wɜːk]', ru: 'Работа', ua: 'робота' },
    {
        en: 'communication',
        t: '[kəˌmjuːnɪˈkeɪʃn]',
        ru: 'Общение',
        ua: 'спілкування',
    },
    { en: 'story', t: '[ˈstɔːri]', ru: 'История', ua: 'розповідь' },
    { en: 'relax', t: '[rɪˈlæks]', ru: 'Отдых', ua: 'відпочинок' },
    { en: 'time', t: '[taɪm]', ru: 'Время', ua: 'час' },
    { en: 'word', t: '[wɜːd]', ru: 'Слово', ua: 'слово' },
    { en: 'dialogue', t: '[ˈdaɪ.ə.lɒɡ]', ru: 'Диалог', ua: 'діалог' },
    { en: 'meeting', t: '[ˈmiːtɪŋ]', ru: 'Встреча', ua: 'зустріч' },
    { en: 'week', t: '[wiːk]', ru: 'Неделя', ua: 'тиждень' },
    { en: 'distance', t: '[ˈdɪstəns]', ru: 'Дистанция', ua: 'дистанція' },
    { en: 'club', t: '[klʌb]', ru: 'Клуб', ua: 'клуб' },
    { en: 'theatre', t: '[ˈθɪətə(r)]', ru: 'Театр', ua: 'театр' },
    { en: 'cinema', t: '[ˈsɪnəmə]', ru: 'Кинотеатр', ua: 'кіно' },
    { en: 'coffee shop', t: '[ˈkɒfi ʃɒp]', ru: 'Кофейня', ua: "кав'ярня" },
    { en: 'friendship', t: '[ˈfrendʃɪp]', ru: 'Дружба', ua: 'дружба' },
    { en: 'behavior', t: '[bɪˈheɪ.vjər]', ru: 'Поведение', ua: 'поведінка' },
    { en: 'attitude', t: '[ˈætɪtjuːd]', ru: 'Отношение', ua: 'ставлення' },
    { en: 'student', t: '[ˈstjuːdnt]', ru: 'Студент', ua: 'студент' },
    {
        en: 'university',
        t: '[ˌjuːnɪˈvɜːsəti]',
        ru: 'Университет',
        ua: 'університет',
    },
    { en: 'union', t: '[ˈjuːniən]', ru: 'Объединение', ua: 'спілка' },
    { en: 'party', t: '[ˈpɑːti]', ru: 'Вечеринка', ua: 'вечірка' },
    { en: 'date', t: '[deɪt]', ru: 'Свидание', ua: 'побачення' },
    {
        en: 'sweetheart',
        t: '[ˈswiːt.hɑːt]',
        ru: 'Партнер, возлюбленный',
        ua: 'кохана',
    },
    { en: 'leisure time', t: '[ˈleʒ.ər taɪm]', ru: 'Досуг', ua: 'дозвілля' },
]

export default words
