const words = [
    { en: 'air', t: '[ən eə(r)]', ru: 'Воздух', ua: 'повітря' },
    { en: 'wind', t: '[wɪnd]', ru: 'Ветер', ua: 'вітер' },
    { en: 'water', t: '[ˈwɔːtə(r)]', ru: 'Вода', ua: 'вода' },
    { en: 'west', t: '[west]', ru: 'Запад', ua: 'захід' },
    { en: 'east', t: '[iːst]', ru: 'Восток', ua: 'схід' },
    { en: 'north', t: '[nɔːθ]', ru: 'Север', ua: 'північ' },
    { en: 'south', t: '[saʊθ]', ru: 'Юг', ua: 'південь' },
    { en: 'tree', t: '[triː]', ru: 'Дерево', ua: 'дерево' },
    { en: 'sea', t: '[siː]', ru: 'Море', ua: 'море' },
    { en: 'ocean', t: '[ˈəʊʃn]', ru: 'Океан', ua: 'океан' },
    { en: 'rock', t: '[rɒk]', ru: 'Скала', ua: 'скеля' },
    { en: 'plant', t: '[plɑːnt]', ru: 'Растение', ua: 'рослина' },
    { en: 'flower', t: '[ˈflaʊə(r)]', ru: 'Цветок', ua: 'квітка' },
    { en: 'forest', t: '[ˈfɒrɪst]', ru: 'Лес', ua: 'ліс' },
    { en: 'person', t: '[ˈpɜːsn]', ru: 'Личность', ua: 'людина' },
    { en: 'night', t: '[naɪt]', ru: 'Ночь', ua: 'ніч' },
    { en: 'morning', t: '[ˈmɔːnɪŋ]', ru: 'Утро', ua: 'ранок' },
    { en: 'day', t: '[deɪ]', ru: 'День', ua: 'день' },
    { en: 'evening', t: '[ˈiːvnɪŋ]', ru: 'Вечер', ua: 'вечір' },
    { en: 'life', t: '[laɪf]', ru: 'Жизнь', ua: 'життя' },
    { en: 'mountain', t: '[ˈmaʊntən]', ru: 'Гора', ua: 'гора' },
    { en: 'land', t: '[lænd]', ru: 'Земля', ua: 'земля' },
    { en: 'house', t: '[haʊs]', ru: 'Дом', ua: 'дім' },
    { en: 'fire', t: '[ˈfaɪə(r)]', ru: 'Огонь', ua: 'пожежа' },
    { en: 'country', t: '[ˈkʌntri]', ru: 'Страна', ua: 'країна' },
    { en: 'animal', t: '[ˈænɪml]', ru: 'Животное', ua: 'тварина' },
    { en: 'bird', t: '[bɜːd]', ru: 'Птица', ua: 'птах' },
    { en: 'fish', t: '[fɪʃ]', ru: 'Рыба', ua: 'риба' },
    { en: 'insect', t: '[ˈɪnsekt]', ru: 'Насекомое', ua: 'комаха' },
    { en: 'city', t: '[ˈsɪti]', ru: 'Город', ua: 'місто' },
    { en: 'world', t: '[wɜːld]', ru: 'Мир', ua: 'світ' },
]

export default words
