const words = [
    { en: 'road', t: '[rəʊd]', ru: 'Дорога', ua: 'дорога' },
    { en: 'ticket', t: '[ˈtɪkɪt]', ru: 'Билет', ua: 'квиток' },
    { en: 'map', t: '[mæp]', ru: 'Карта', ua: 'карта' },
    { en: 'motel', t: '[məʊˈtel]', ru: 'Мотель', ua: 'мотель' },
    { en: 'highway', t: '[ˈhaɪweɪ]', ru: 'Шоссе', ua: 'шосе' },
    {
        en: 'reception',
        t: '[rɪˈsepʃn]',
        ru: 'Регистратура, ресепшн',
        ua: 'ресепшен',
    },
    { en: 'wallet', t: '[ˈwɒlɪt]', ru: 'Бумажник', ua: 'гаманець' },
    { en: 'bank', t: '[bæŋk]', ru: 'Банк', ua: 'банк' },
    { en: 'subway', t: '[ˈsʌb.weɪ]', ru: 'Метро', ua: 'метро' },
    { en: 'cab', t: '[kæb]', ru: 'Такси', ua: 'таксі' },
    { en: 'parking', t: '[ˈpɑː.kɪŋ]', ru: 'Парковка', ua: 'стоянка' },
    {
        en: 'food order',
        t: '[fuːd ˈɔːdə(r)]',
        ru: 'Заказ еды',
        ua: 'замовлення їжі',
    },
    { en: 'cash', t: '[kæʃ]', ru: 'Наличные', ua: ' готівка' },
    { en: 'passport', t: '[ˈpɑːspɔːt]', ru: 'Паспорт', ua: 'паспорт' },
    { en: 'permission', t: '[pəˈmɪʃn]', ru: 'Разрешение', ua: 'дозвіл' },
    { en: 'lawyer', t: '[ˈlɔːjə(r)]', ru: 'Адвокат', ua: 'адвокат' },
    { en: 'problem', t: '[ˈprɒbləm]', ru: 'Проблема', ua: 'проблема' },
    {
        en: 'waiting room',
        t: '[weɪtin: ruːm]',
        ru: 'Зал ожидания',
        ua: 'зал очікування',
    },
    { en: 'transfer', t: '[trænsˈfɜː(r)]', ru: 'Пересадка', ua: 'трансфер' },
    { en: 'bag', t: '[bæɡ]', ru: 'Сумка', ua: 'сумка' },
    { en: 'suitcase', t: '[ˈsuːtkeɪs]', ru: 'Чемодан', ua: 'валіза' },
    { en: 'property', t: '[ˈprɒpəti]', ru: 'Имущество', ua: 'майно' },
    { en: 'law', t: '[lɔː]', ru: 'Право, закон', ua: 'право' },
    {
        en: 'police station',
        t: '[pəˈliːs ˈsteɪʃn]',
        ru: 'Полицейский участок',
        ua: 'поліцейська дільниця',
    },
    { en: 'price', t: '[praɪs]', ru: 'Стоимость, цена', ua: ' прайс' },
    { en: 'price list', t: '[praɪs lɪst]', ru: 'Ценник', ua: 'прайс-лист' },
    { en: 'courier', t: '[ˈkʊr.i.ər]', ru: 'Курьер', ua: "кур'єр" },
    { en: 'delivery', t: '[dɪˈlɪvəri]', ru: 'Доставка', ua: 'доставка' },
    { en: 'location', t: '[ləʊˈkeɪʃn]', ru: 'Местоположение', ua: 'місце' },
    { en: 'route', t: '[ruːt]', ru: 'Маршрут', ua: 'маршрут' },
    { en: 'agreement', t: '[əˈɡriːmənt]', ru: 'Договор', ua: 'договір' },
    { en: 'hospital', t: '[ˈhɒspɪtl]', ru: 'Больница', ua: 'лікарня' },
    {
        en: 'ambulance',
        t: '[ˈæmbjələns]',
        ru: 'Скорая помощь',
        ua: 'швидка допомога',
    },
]

export default words
