export const words = [
    { en: 'To be', t: '[tə biː]', ru: 'Быть', ua: 'Бути' },
    { en: 'To do', t: '[du]', ru: 'Делать', ua: 'Робити' },
    { en: 'To feel', t: '[fiːl]', ru: 'Чувствовать', ua: 'Відчувати' },
    { en: 'To see', t: '[siː]', ru: 'Видеть', ua: 'Бачити' },
    { en: 'To hear', t: '[hɪər]', ru: 'Слышать', ua: 'Чути' },
    { en: 'To run', t: '[rʌn]', ru: 'Бежать', ua: 'Бігати' },
    { en: 'To get', t: '[ɡet]', ru: 'Получать', ua: 'Здобувати' },
    { en: 'To make', t: '[meɪk]', ru: 'Сделать', ua: 'Зробити' },
    { en: 'To cook', t: '[kʊk]', ru: 'Готовить', ua: 'Приготувати' },
    { en: 'To sing', t: '[sɪŋ]', ru: 'Петь', ua: 'Співати' },
    { en: 'To speak', t: '[spiːk]', ru: 'Разговаривать', ua: 'Говорити' },
    { en: 'To say', t: '[seɪ]', ru: 'Говорить', ua: 'Сказати' },
    { en: 'To tell', t: '[tel]', ru: 'Рассказывать', ua: 'Розповісти' },
    { en: 'To take', t: '[teɪk]', ru: 'Брать', ua: 'Взяти' },
    { en: 'To sit', t: '[sɪt]', ru: 'Садиться', ua: 'Сісти' },
    { en: 'To stand', t: '[stænd]', ru: 'Стоять', ua: 'Стояти' },
    { en: 'To laugh', t: '[lɑːf]', ru: 'Смеяться', ua: 'Сміятися' },
    { en: 'To smile', t: '[smaɪl]', ru: 'Улыбаться', ua: 'Усміхатися' },
    { en: 'To open', t: '[ˈəʊpən]', ru: 'Открывать', ua: 'Відкривати' },
    { en: 'To close', t: '[kləʊz]', ru: 'Закрывать', ua: 'Закривати' },
    { en: 'To love', t: '[lʌv]', ru: 'Любить', ua: 'Любити' },
    { en: 'To like', t: '[laɪk]', ru: 'Нравиться', ua: 'Любити' },
    { en: 'To give', t: '[ɡɪv]', ru: 'Давать', ua: 'Дарувати' },
    { en: 'To bring', t: '[brɪŋ]', ru: 'Приносить', ua: 'Приносити' },
    { en: 'To breath', t: '[breθ]', ru: 'Дышать', ua: 'Дихати' },
    { en: 'To buy', t: '[baɪ]', ru: 'Покупать', ua: 'Купити' },
    { en: 'To sell', t: '[sel]', ru: 'Продавать', ua: 'Продавати' },
    { en: 'To forget', t: '[fəˈɡet]', ru: 'Забывать', ua: 'Забути' },
    { en: 'To believe', t: '[bɪˈliːv]', ru: 'Верить', ua: 'Вірити' },
    { en: 'To have', t: '[həv]', ru: 'Иметь', ua: 'Мати' },
    { en: 'To go', t: '[ɡəʊ]', ru: 'Идти', ua: 'Поїти' },
    { en: 'To know', t: '[nəʊ]', ru: 'Знать', ua: 'Знати' },
    { en: 'To think', t: '[θɪŋk]', ru: 'Думать', ua: 'Подумати' },
    { en: 'To come', t: '[kʌm]', ru: 'Приходить', ua: 'Прийти' },
    { en: 'To want', t: '[wɒnt]', ru: 'Хотеть', ua: 'Захотіти' },
    { en: 'To use', t: '[juːz]', ru: 'Использовать', ua: 'Скористатися' },
    { en: 'To find', t: '[faɪnd]', ru: 'Находить', ua: 'Знайти' },
    { en: 'To work', t: '[wɜːk]', ru: 'Работать', ua: 'Працювати' },
    { en: 'To eat', t: '[iːt]', ru: 'Есть', ua: 'Їсти' },
    { en: 'To drink', t: '[drɪŋk]', ru: 'Пить', ua: 'Пити' },
    { en: 'To write', t: '[raɪt]', ru: 'Писать', ua: 'Написати' },
    { en: 'To read', t: '[riːd]', ru: 'Читать', ua: 'Прочитати' },
    { en: 'To call', t: '[kɔːl]', ru: 'Звонить', ua: 'Подзвонити' },
    { en: 'To try', t: '[traɪ]', ru: 'Пытаться', ua: 'Спробувати' },
    { en: 'To need', t: '[niːd]', ru: 'Нуждаться', ua: 'Потрібно' },
    { en: 'To become', t: '[bɪˈkʌm]', ru: 'Становиться', ua: 'Стати' },
    { en: 'To put', t: '[pʊt]', ru: 'Класть', ua: 'Покласти' },
    { en: 'To leave', t: '[liːv]', ru: 'Оставлять', ua: 'Залишити' },
    { en: 'To pay', t: '[peɪ]', ru: 'Платить', ua: 'Заплатити' },
    { en: 'To play', t: '[pleɪ]', ru: 'Играть', ua: 'Грати' },
    { en: 'To pray', t: '[preɪ]', ru: 'Молиться', ua: 'Молитися' },
    { en: 'To stay', t: '[steɪ]', ru: 'Оставаться', ua: 'Залишитися' },
    { en: 'To mean', t: '[miːn]', ru: 'Означать', ua: 'Значити' },
    { en: 'To keep', t: '[kiːp]', ru: 'Держать, хранить', ua: 'Зберегти' },
    { en: 'To let', t: '[let]', ru: 'Оставлять', ua: 'Дозволити' },
    { en: 'To begin', t: '[bɪˈɡɪn]', ru: 'Начинать', ua: 'Почати' },
    { en: 'To start', t: '[stɑːt]', ru: 'Стартовать', ua: 'Почати' },
    { en: 'To finish', t: '[ˈfɪnɪʃ]', ru: 'Заканчивать', ua: 'Закінчити' },
    { en: 'To help', t: '[help]', ru: 'Помогать', ua: 'Допомогти' },
    { en: 'To show', t: '[ʃəʊ]', ru: 'Показывать', ua: 'Показати' },
    { en: 'To cry', t: '[kraɪ]', ru: 'Плакать', ua: 'Плакати' },
    { en: 'To move', t: '[muːv]', ru: 'Двигаться', ua: 'Рухатися' },
    { en: 'To jump', t: '[dʒʌmp]', ru: 'Прыгать', ua: 'Стрибати' },
    { en: 'To live', t: '[lɪv]', ru: 'Жить', ua: 'Жити' },
    { en: 'To die', t: '[daɪ]', ru: 'Умирать', ua: 'Померти' },
    { en: 'To happen', t: '[ˈhæpən]', ru: 'Случаться', ua: 'Відбутися' },
    { en: 'To lose', t: '[luːz]', ru: 'Проигрывать', ua: 'Втратити' },
    { en: 'To hate', t: '[heɪt]', ru: 'Ненавидеть', ua: 'Ненавидіти' },
    {
        en: 'To include',
        t: '[ɪnˈkluːd]',
        ru: 'Включать в себя',
        ua: 'Включити',
    },
    {
        en: 'To turn on',
        t: '[tɜːn ɒn]',
        ru: 'Включать (о приборе)',
        ua: 'Ввімкнути',
    },
    { en: 'To turn off', t: '[tɜːn ɒf]', ru: 'Выключать', ua: 'Вимкнути' },
    {
        en: 'To continue',
        t: '[kənˈtɪnjuː]',
        ru: 'Продолжать',
        ua: 'Продовжити',
    },
    { en: 'To change', t: '[tʃeɪndʒ]', ru: 'Менять', ua: 'Змінити' },
    { en: 'To wash', t: '[wɒʃ]', ru: 'Мыть', ua: 'Вимити' },
    { en: 'To clean', t: '[kliːn]', ru: 'Убирать, очищать', ua: 'Очистити' },
    { en: 'To lead', t: '[liːd]', ru: 'Вести', ua: 'Вести' },
    {
        en: 'To understand',
        t: '[ˌʌndəˈstænd]',
        ru: 'Понимать',
        ua: 'Зрозуміти',
    },
    { en: 'To watch', t: '[wɒtʃ]', ru: 'Смотреть', ua: 'Дивитися' },
    {
        en: 'To discover',
        t: '[dɪˈskʌvə(r)]',
        ru: 'Исследовать',
        ua: 'Відкрити',
    },
    { en: 'To imagine', t: '[ɪˈmædʒɪn]', ru: 'Представлять', ua: 'Уявити' },
    {
        en: 'To introduce',
        t: '[ˌɪntrəˈdjuːs]',
        ru: 'Представить',
        ua: 'Познайомити',
    },
    { en: 'To follow', t: '[ˈfɒləʊ]', ru: 'Следовать', ua: 'Наслідувати' },
    { en: 'To create', t: '[kriˈeɪt]', ru: 'Создавать', ua: 'Створити' },
    { en: 'To grow', t: '[ɡrəʊ]', ru: 'Расти', ua: 'Зростати' },
    { en: 'To spend', t: '[spend]', ru: 'Тратить', ua: 'Витрачати' },
    { en: 'To win', t: '[wɪn]', ru: 'Выигрывать', ua: 'Виграти' },
    { en: 'To offer', t: '[ˈɒfə(r)]', ru: 'Предлагать', ua: 'Пропонувати ' },
    { en: 'To learn', t: '[lɜːn]', ru: 'Изучать', ua: 'Навчитися' },
    { en: 'To appear', t: '[əˈpɪə(r)]', ru: 'Появляться', ua: "З'явитися" },
    { en: 'To disappear', t: '[ˌdɪsəˈpɪə(r)]', ru: 'Исчезать', ua: 'Зникнути' },
    { en: 'To build', t: '[bɪld]', ru: 'Строить', ua: 'Будувати' },
    { en: 'To break', t: '[breɪk]', ru: 'Ломать', ua: 'Зламати' },
    { en: 'To send', t: '[send]', ru: 'Посылать', ua: 'Послати' },
    { en: 'To fall', t: '[fɔːl]', ru: 'Падать', ua: 'Впасти' },
    { en: 'To cut', t: '[kʌt]', ru: 'Резать', ua: 'Розрізати' },
    { en: 'To achieve', t: '[əˈtʃiːv]', ru: 'Достигать', ua: 'Досягти' },
    {
        en: 'To communicate',
        t: '[kəˈmjuːnɪkeɪt]',
        ru: 'Общаться',
        ua: 'Спілкуватися ',
    },
    { en: 'To kill', t: '[kɪl]', ru: 'Убивать', ua: 'Вбити' },
    { en: 'To pass', t: '[pɑːs]', ru: 'Проходить', ua: 'Пройти' },
    { en: 'To fly', t: '[flaɪ]', ru: 'Летать', ua: 'Полетіти' },
    { en: 'To swim', t: '[swɪm]', ru: 'Плавать', ua: 'Плисти' },
    { en: 'To decide', t: '[dɪˈsaɪd]', ru: 'Решать', ua: 'Вирішити' },
    { en: 'To return', t: '[rɪˈtɜːn]', ru: 'Возвращаться', ua: 'Повернутися' },
    { en: 'To hope', t: '[həʊp]', ru: 'Надеяться', ua: 'Сподіватися' },
    { en: 'To explain', t: '[ɪkˈspleɪn]', ru: 'Объяснять', ua: 'Пояснити' },
    { en: 'To propose', t: '[prəˈpəʊz]', ru: 'Предлагать', ua: 'Пропонувати' },
    { en: 'To develop', t: '[dɪˈveləp]', ru: 'Развивать', ua: 'Розвинути' },
    { en: 'To support', t: '[səˈpɔːt]', ru: 'Поддерживать', ua: 'Підтримати' },
    { en: 'To dance', t: '[dɑːns]', ru: 'Танцевать', ua: 'Танцювати' },
    { en: 'To draw', t: '[drɔː]', ru: 'Рисовать', ua: 'Намалювати' },
    { en: 'To book', t: '[bʊk]', ru: 'Бронировать', ua: 'Забронювати' },
    { en: 'To be afraid', t: '[bi əˈfreɪd]', ru: 'Бояться', ua: 'Побоюватися' },
    { en: 'To agree', t: '[əˈɡriː]', ru: 'Соглашаться', ua: 'Погодитися' },
    { en: 'To check up', t: '[tʃek ʌp]', ru: 'Проверять', ua: 'Перевірити' },
    { en: 'To delete', t: '[dɪˈliːt]', ru: 'Удалять', ua: 'Видалити' },
    { en: 'To choose', t: '[tʃuːz]', ru: 'Выбирать', ua: 'Вибрати' },
    { en: 'To catch', t: '[kætʃ]', ru: 'Ловить', ua: 'Спіймати' },
    { en: 'To ask', t: '[ɑːsk]', ru: 'Спрашивать', ua: 'Запитати' },
    { en: 'To hesitate', t: '[ˈhezɪteɪt]', ru: 'Cомневаться', ua: 'Вагатися' },
    { en: 'To answer', t: '[ˈɑːnsə(r)]', ru: 'Отвечать', ua: 'Відповісти' },
]

export default words
