const words = [
    { en: 'Слово', t: 'Транскрипция', ru: 'Перевод' },
    { en: 'Arrogant', t: '[ˈærəʊgənt]', ru: 'Высокомерный, заносчивый' },
    { en: 'Civilian', t: '[səˈvɪljən]', ru: 'Гражданский' },
    { en: 'Commercial', t: '[kəˈmɜːʃəl]', ru: 'Коммерческий' },
    { en: 'Convenient', t: '[kənˈviːniənt]', ru: 'Удобный' },
    { en: 'Creative', t: '[kri(ː)ˈeɪtɪv]', ru: 'Креативный, творческий' },
    { en: 'Naughty', t: '[ˈnɔːti]', ru: 'Озорной, шаловливый' },
    { en: 'Stationary', t: '[ˈsteɪʃnəri]', ru: 'Стационарный' },
    { en: 'Valuable', t: '[ˈvæljʊəbl]', ru: 'Ценный' },
    {
        en: 'Significant',
        t: '[sɪgˈnɪfɪkənt]',
        ru: 'Значительный, существенный',
    },
    { en: 'Foremost', t: '[ˈfɔːməʊst]', ru: 'Передовой, основной, главный' },
    { en: 'Recent', t: '[ˈriːsnt]', ru: 'Недавний' },
    { en: 'Updated', t: '[ʌpˈdeɪtɪd]', ru: 'Обновленный' },
    {
        en: 'Operational',
        t: '[ˌɒpəˈreɪʃənl]',
        ru: 'Оперативный, рабочий, действующий',
    },
    {
        en: 'Intuitive',
        t: '[ɪnˈtju(ː)ɪtɪv]',
        ru: 'Интуитивно понятный, интуитивный',
    },
    { en: 'Essential', t: '[ɪˈsɛnʃəl]', ru: 'Существенный, важный' },
    { en: 'Numerous', t: '[ˈnjuːmərəs]', ru: 'Многочисленный' },
    { en: 'Compliant', t: '[kəmˈplaɪənt]', ru: 'Соответствующий' },
    {
        en: 'Straightforward',
        t: '[streɪtˈfɔːwəd]',
        ru: 'Прямой, прямолинейный',
    },
    { en: 'Understandable', t: '[ʌndəˈstændəbl]', ru: 'Понятный, доступный' },
    { en: 'Uncompromising', t: '[ʌnˈkɒmprəmaɪzɪŋ]', ru: 'Беспрекословный' },
    {
        en: 'Distinguished',
        t: '[dɪsˈtɪŋgwɪʃt]',
        ru: 'Выдающийся, уважаемый, отличительный',
    },
    { en: 'Separate', t: '[ˈsɛprɪt]', ru: 'Отдельный' },
    { en: 'Outstanding', t: '[aʊtˈstændɪŋ]', ru: 'Незаурядный' },
    { en: 'Principal', t: '[ˈprɪnsəpəl]', ru: 'Принципиальный, главный' },
    { en: 'Leading', t: '[ˈliːdɪŋ]', ru: 'Ведущий, лидирующий' },
    { en: 'Cognitive', t: '[ˈkɒgnɪtɪv]', ru: 'Когнитивный, познавательный' },
    { en: 'Cutting-edge', t: '[kʌtɪŋ-ɛʤ]', ru: 'Современный, новейший' },
    { en: 'Precise', t: '[prɪˈsaɪs]', ru: 'Точный, четкий' },
    { en: 'Unmatched', t: '[ʌnˈmæʧt]', ru: 'Неповторимый, непревзойденный' },
    { en: 'Reasonable', t: '[ˈriːznəbl]', ru: 'Разумный, целесообразный' },
    { en: 'Fundamental', t: '[ˌfʌndəˈmɛntl]', ru: 'Основополагающий' },
    { en: 'Brilliant', t: '[ˈbrɪljənt]', ru: 'Блестящий, гениальный' },
    { en: 'Inflexible', t: '[ɪnˈflɛksəbl]', ru: 'Несгибаемый, непогрешимый' },
    { en: 'Crucial', t: '[ɪnˈflɛksəbl]', ru: 'Решающий, критический, важный' },
    { en: 'Contemporary', t: '[kənˈtɛmpərəri]', ru: 'Современный, актуальный' },
    { en: 'Duplicated', t: '[ˈdjuːplɪkeɪtɪd]', ru: 'Дублированный' },
    {
        en: 'Tedious',
        t: '[ˈtiːdiəs]',
        ru: 'Утомительный, кропотливый, надоедливый',
    },
    { en: 'Multiple', t: '[ˈmʌltɪpl]', ru: 'Множественный, многочисленный' },
    { en: 'Individual', t: '[ɪndɪˈvɪdjʊəl]', ru: 'Личный, индивидуальный' },
    { en: 'Fitting', t: '[ˈfɪtɪŋ]', ru: 'Подходящий' },
    { en: 'Monotonous', t: '[məˈnɒtnəs]', ru: 'Монотонный, однообразный' },
    { en: 'Ruthless', t: '[ˈruːθlɪs]', ru: 'Бесчеловечный' },
    { en: 'Multi-channel', t: '[ˈmʌltɪ-ˈʧænl]', ru: 'Многоканальный' },
    { en: 'Astonishing', t: '[əsˈtɒnɪʃɪŋ]', ru: 'Удивительный, изумительный' },
    { en: 'Ambitious', t: '[æmˈbɪʃəs]', ru: 'Амбициозный, честолюбивый' },
    {
        en: 'Captivating',
        t: '[ˈkæptɪveɪtɪŋ]',
        ru: 'Захватывающий, завораживающий',
    },
    { en: 'Profound', t: '[prəˈfaʊnd]', ru: 'Глубокомысленный' },
    { en: 'Qualified', t: '[ˈkwɒlɪfaɪd]', ru: 'Квалифицированный' },
    {
        en: 'Remarkable',
        t: '[rɪˈmɑːkəbl]',
        ru: 'Замечательный, примечательный, выдающийся',
    },
    { en: 'Additional', t: '[əˈdɪʃənl]', ru: 'Дополнительный' },
    { en: 'Burning', t: '[ˈbɜːnɪŋ]', ru: 'Горящий, жгучий' },
    { en: 'Unassuming', t: '[ˌʌnəˈsjuːmɪŋ]', ru: 'Непритязательный' },
    { en: 'Meaningful', t: '[ˈmiːnɪŋfʊl]', ru: 'Значимый, осмысленный' },
    { en: 'Private', t: '[ˈpraɪvɪt]', ru: 'Личный, частный' },
    { en: 'Careful', t: '[ˈkeəfʊl]', ru: 'Бережный, осторожный' },
    { en: 'Obscure', t: '[əbˈskjʊə]', ru: 'Наблюдательный, непонятный' },
    {
        en: 'Accomplished',
        t: '[əˈkɒmplɪʃt]',
        ru: 'Состоятельный, успешный, достигнутый',
    },
    { en: 'Ridiculous', t: '[rɪˈdɪkjʊləs]', ru: 'Нелепый, смешной' },
    { en: 'Contemptuous', t: '[kənˈtɛmptjʊəs]', ru: 'Презрительный' },
    { en: 'Fashionable', t: '[ˈfæʃnəbl]', ru: 'Модный' },
]


export default words