const words = [
    { en: 'Invariably', t: '[ɪnˈveərɪəbli]', ru: 'Неизменно' },
    { en: 'Intermittently', t: '[ɪntə(ː)ˈmɪtəntli]', ru: 'Иногда' },
    { en: 'Infrequently', t: '[ɪntə(ː)ˈmɪtəntli]', ru: 'Редко' },
    { en: 'Predominantly', t: '[prɪˈdɒmɪnəntli]', ru: 'Постоянно' },
    { en: 'Elsewhere', t: '[ˈɛlsˈweə]', ru: 'Где-нибудь' },
    { en: 'Scarcely', t: '[ ˈskeəsli]', ru: 'Едва' },
    { en: 'Otherwise', t: '[ˈʌðəwaɪz]', ru: 'Иначе' },
    { en: 'Quickly', t: '[ˈkwɪkli]', ru: 'Быстро' },
    { en: 'Quietly', t: '[ˈkwaɪətli]', ru: 'Спокойно, тихо' },
    { en: 'Moreover', t: '[mɔːˈrəʊvə]', ru: 'Более того' },
    { en: 'Nevertheless', t: '[ˌnɛvəðəˈlɛs]', ru: 'Тем не менее' },
    { en: 'Somewhat', t: '[ˈsʌmwɒt]', ru: 'До некоторой степени' },
    { en: 'Cheerfully', t: '[ˈʧɪəfʊli]', ru: 'Весело' },
    { en: 'Clumsily', t: '[klʌmzɪli]', ru: 'Неуклюже' },
    { en: 'In vain', t: '[ɪn veɪn]', ru: 'Напрасно' },
    { en: 'At once', t: '[æt wʌns]', ru: 'Немедленно' },
    { en: 'Casually', t: '[ˈkæʒjʊəli]', ru: 'Случайно' },
    { en: 'Since that', t: '[sɪns ðæt]', ru: 'С тех пор' },
    { en: 'By all means', t: '[baɪ ɔːl miːnz]', ru: 'Во что бы то ни стало' },
    { en: 'Readily', t: '[ˈrɛdɪli]', ru: 'Охотно' },
    { en: 'Outside', t: '[ˌaʊtˈsaɪd]', ru: 'Снаружи' },
    { en: 'Besides', t: '[bɪˈsaɪdz]', ru: 'Кроме того' },
    { en: 'Once', t: '[wʌns]', ru: 'Однажды' },
    { en: 'However', t: '[haʊˈɛvə]', ru: 'Однако, как бы ни' },
    { en: 'Yet', t: '[jɛt]', ru: 'Еще, до сих пор' },
    { en: 'Foolishly', t: '[ˈfuːlɪʃli]', ru: 'Глупо, по глупости' },
    { en: 'Clearly', t: '[ˈklɪəli]', ru: 'Очевидно' },
    { en: 'Actually', t: '[ˈækʧʊəli]', ru: 'В общем, вообще-то' },
    { en: 'Completely', t: '[kəmˈpliːtli]', ru: 'Совершенно, абсолютно' },
    { en: 'Extremely', t: '[ɪksˈtriːmli]', ru: 'Безумно' },
    { en: 'Nearby', t: '[ˈnɪəbaɪ]', ru: 'Рядом, неподалеку' },
    { en: 'Unmistakable', t: '[ʌnmɪsˈteɪkəbl]', ru: 'Безошибочно' },
    { en: 'Accurately', t: '[ˈækjʊrɪtli]', ru: 'Точно' },
    { en: 'Definitely', t: '[ˈdɛfɪnɪtli]', ru: 'Абсолютно' },
    { en: 'Relentlessly', t: '[rɪˈlɛntlɪsli]', ru: 'Безостановочно' },
    {
        en: 'Incredibly',
        t: '[ɪnˈkrɛdəbli]',
        ru: 'Невероятно, очень, неимоверно',
    },
    { en: 'Decidedly', t: '[dɪˈsaɪdɪdli]', ru: 'Решительно' },
    { en: 'Firmly', t: '[ˈfɜːmli]', ru: 'Уверенно' },
    { en: 'Carelessly', t: '[ˈkeəlɪsli]', ru: 'Беспечно' },
]

export default words
