const words = [
    { en: 'Invariably', t: '[ɪnˈveərɪəbli]', ru: 'Неизменно', ua: 'Незмінно' },
    {
        en: 'Intermittently',
        t: '[ɪntə(ː)ˈmɪtəntli]',
        ru: 'Иногда',
        ua: 'Іноді',
    },
    { en: 'Infrequently', t: '[ɪntə(ː)ˈmɪtəntli]', ru: 'Редко', ua: 'Рідко' },
    {
        en: 'Predominantly',
        t: '[prɪˈdɒmɪnəntli]',
        ru: 'Постоянно',
        ua: 'Постійно',
    },
    { en: 'Elsewhere', t: '[ˈɛlsˈweə]', ru: 'Где-нибудь', ua: 'Де-небудь' },
    { en: 'Scarcely', t: '[ ˈskeəsli]', ru: 'Едва', ua: 'Тільки' },
    { en: 'Otherwise', t: '[ˈʌðəwaɪz]', ru: 'Иначе', ua: 'Інакше' },
    { en: 'Quickly', t: '[ˈkwɪkli]', ru: 'Быстро', ua: 'Швидко' },
    {
        en: 'Quietly',
        t: '[ˈkwaɪətli]',
        ru: 'Спокойно, тихо',
        ua: 'Спокійно, тихо',
    },
    { en: 'Moreover', t: '[mɔːˈrəʊvə]', ru: 'Более того', ua: 'Більше того' },
    {
        en: 'Nevertheless',
        t: '[ˌnɛvəðəˈlɛs]',
        ru: 'Тем не менее',
        ua: 'Тим не менш',
    },
    {
        en: 'Somewhat',
        t: '[ˈsʌmwɒt]',
        ru: 'До некоторой степени',
        ua: 'Деякою мірою',
    },
    { en: 'Cheerfully', t: '[ˈʧɪəfʊli]', ru: 'Весело', ua: 'Весело' },
    { en: 'Clumsily', t: '[klʌmzɪli]', ru: 'Неуклюже', ua: 'Незграбно' },
    { en: 'In vain', t: '[ɪn veɪn]', ru: 'Напрасно', ua: 'Дарма' },
    { en: 'At once', t: '[æt wʌns]', ru: 'Немедленно', ua: 'Негайно' },
    { en: 'Casually', t: '[ˈkæʒjʊəli]', ru: 'Случайно', ua: 'Випадково' },
    { en: 'Since that', t: '[sɪns ðæt]', ru: 'С тех пор', ua: 'З тих пір' },
    {
        en: 'By all means',
        t: '[baɪ ɔːl miːnz]',
        ru: 'Во что бы то ни стало',
        ua: 'У будь-що',
    },
    { en: 'Readily', t: '[ˈrɛdɪli]', ru: 'Охотно', ua: 'Охоче' },
    { en: 'Outside', t: '[ˌaʊtˈsaɪd]', ru: 'Снаружи', ua: 'Зовні' },
    { en: 'Besides', t: '[bɪˈsaɪdz]', ru: 'Кроме того', ua: 'Крім того' },
    { en: 'Once', t: '[wʌns]', ru: 'Однажды', ua: 'Одного разу' },
    {
        en: 'However',
        t: '[haʊˈɛvə]',
        ru: 'Однако, как бы ни',
        ua: 'Однак, як би не',
    },
    { en: 'Yet', t: '[jɛt]', ru: 'Еще, до сих пор', ua: 'Ще, досі' },
    {
        en: 'Foolishly',
        t: '[ˈfuːlɪʃli]',
        ru: 'Глупо, по глупости',
        ua: 'Дурно, по дурості',
    },
    { en: 'Clearly', t: '[ˈklɪəli]', ru: 'Очевидно', ua: 'Очевидно' },
    {
        en: 'Actually',
        t: '[ˈækʧʊəli]',
        ru: 'В общем, вообще-то',
        ua: 'Загалом, взагалі-то',
    },
    {
        en: 'Completely',
        t: '[kəmˈpliːtli]',
        ru: 'Совершенно, абсолютно',
        ua: 'Цілком, абсолютно',
    },
    { en: 'Extremely', t: '[ɪksˈtriːmli]', ru: 'Безумно', ua: 'Безумно' },
    {
        en: 'Nearby',
        t: '[ˈnɪəbaɪ]',
        ru: 'Рядом, неподалеку',
        ua: 'Поруч, неподалік',
    },
    {
        en: 'Unmistakable',
        t: '[ʌnmɪsˈteɪkəbl]',
        ru: 'Безошибочно',
        ua: 'Безпомилково',
    },
    { en: 'Accurately', t: '[ˈækjʊrɪtli]', ru: 'Точно', ua: 'Точно' },
    { en: 'Definitely', t: '[ˈdɛfɪnɪtli]', ru: 'Абсолютно', ua: 'Абсолютно' },
    {
        en: 'Relentlessly',
        t: '[rɪˈlɛntlɪsli]',
        ru: 'Безостановочно',
        ua: 'Безупинно',
    },
    {
        en: 'Incredibly',
        t: '[ɪnˈkrɛdəbli]',
        ru: 'Невероятно, очень, неимоверно',
        ua: 'Неймовірно, дуже, неймовірно',
    },
    { en: 'Decidedly', t: '[dɪˈsaɪdɪdli]', ru: 'Решительно', ua: 'Рішуче' },
    { en: 'Firmly', t: '[ˈfɜːmli]', ru: 'Уверенно', ua: 'Упевнено' },
    { en: 'Carelessly', t: '[ˈkeəlɪsli]', ru: 'Беспечно', ua: 'Безпечно' },
]

export default words
