const words = [
    {
        en: 'downfall',
        t: '[ˈdaʊnfɔːl]',
        ru: 'Падение, упадок, крах, понижение',
    },
    { en: 'А setback', t: '[ˈsɛtbæk]', ru: 'Неудача, провал' },
    { en: 'А bad luck', t: '[bæd lʌk]', ru: 'Невезение, несчастье' },
    { en: 'depression', t: '[dɪˈprɛʃən]', ru: 'Депрессия' },
    { en: 'А solitude', t: '[ˈsɒlɪtjuːd]', ru: 'Одиночество' },
    { en: 'А self-blame', t: '[sɛlf-bleɪm]', ru: 'Самобичевание' },
    { en: 'А disorder', t: '[dɪsˈɔːdə]', ru: 'Расстройство, разлад' },
    { en: 'А instability', t: '[ɪnstəˈbɪlɪti]', ru: 'Нестабильность' },
    { en: 'А challenge', t: '[ˈʧælɪnʤ]', ru: 'Вызов, сложность' },
    {
        en: 'А sustainability',
        t: '[səsˌteɪnəˈbɪlɪti]',
        ru: 'Устойчивость, жизнеспособность',
    },
    { en: 'duration', t: '[djʊəˈreɪʃən]', ru: 'Продолжительность' },
    { en: 'А luckiness', t: '[ˈlʌkɪnəs]', ru: 'Удачливость, везение' },
    { en: 'А fluke', t: '[fluːk]', ru: 'Случайность, шанс' },
    { en: 'А winning', t: '[ˈwɪnɪŋ]', ru: 'Выигрыш, победа, завоевание' },
    { en: 'lottery', t: '[ˈlɒtəri]', ru: 'Лотерея' },
    { en: 'destination', t: '[ˌdɛstɪˈneɪʃən]', ru: 'Предназначение' },
    { en: 'advantage', t: '[ədˈvɑːntɪʤ]', ru: 'Преимущество' },
    { en: 'win-win', t: '[wɪn-wɪn]', ru: 'Победа, выигрыш' },
    {
        en: 'condition',
        t: '[kənˈdɪʃən]',
        ru: 'Условие, обстоятельство, состояние',
    },
    { en: 'contest', t: '[ˈkɒntɛst]', ru: 'Соревнование, борьба, конкурс' },
    {
        en: 'А humbleness',
        t: '[ˈhʌmblnəs]',
        ru: 'Смирение, скромность, покорность',
    },
    { en: 'А fearlessness', t: '[ˈfɪəlɪsnəs]', ru: 'Бесстрашие' },
    { en: 'А hardening', t: '[ˈhɑːdnɪŋ]', ru: 'Закалка, твердость' },
    { en: 'А buoyancy', t: '[ˈbɔɪənsi]', ru: 'Оживленность, жизнелюбие' },
    {
        en: 'А cheerfulness',
        t: '[ˈʧɪəfʊlnəs]',
        ru: 'Жизнерадостность, веселость',
    },
    { en: 'А hospitality', t: '[hɒspɪˈtælɪti]', ru: 'Гостеприимство, радушие' },
    { en: 'А pessimism', t: '[ˈpɛsɪmɪzm]', ru: 'Пессимизм' },
    { en: 'А morale', t: '[mɒˈrɑːl]', ru: 'Мораль, дух, нрав, мужество' },
    { en: 'А wisdom', t: '[ˈwɪzdəm]', ru: 'Мудрость' },
    {
        en: 'А proficiency',
        t: '[prəˈfɪʃənsi]',
        ru: 'Мастерство, умение, квалификация',
    },
    {
        en: 'applicant',
        t: '[ˈæplɪkənt]',
        ru: 'Претендент, соискать, заявитель',
    },
    { en: 'А decisiveness', t: '[dɪˈsaɪsɪvnəs]', ru: 'Решительность' },
    { en: 'А loophole', t: '[ˈluːphəʊl]', ru: 'Лазейка, дыра' },
    {
        en: 'А frustration',
        t: '[frʌsˈtreɪ.ʃən]',
        ru: 'Фрустрация, разочарование',
    },
    { en: 'А knowledge', t: '[ˈnɒlɪʤ]', ru: 'Знание, познание' },
    {
        en: 'А decision-making',
        t: '[dɪˈsɪʒən-ˈmeɪkɪŋ]',
        ru: 'Принятие решения',
    },
    {
        en: 'alacrity',
        t: '[əˈlækrɪti]',
        ru: 'Аккуратность, активность, стремительность',
    },
    {
        en: 'extremity',
        t: '[ɪksˈtrɛmɪti]',
        ru: 'Крайность, упорство, чрезмерность',
    },
    { en: 'А background', t: '[ˈbækgraʊnd]', ru: 'Фон, предпосылка' },
    { en: 'А preparatory', t: '[prɪˈpærətəri]', ru: 'Подготовка' },
]

export default words
