const words = [
    {
        en: 'distancing',
        t: '[ˈdɪstənsɪŋ]',
        ru: 'Дистанцирование',
        ua: 'Дистанціювання',
    },
    { en: 'isolation', t: '[ˌaɪsəʊˈleɪʃən]', ru: 'Изоляция', ua: 'Ізоляція' },
    {
        en: 'self-care',
        t: '[sɛlf-keə]',
        ru: 'Забота о себе',
        ua: 'Турбота про себе',
    },
    { en: 'medication', t: '[ˌmɛdɪˈkeɪʃən]', ru: 'Лекарство', ua: 'Ліки' },
    { en: 'celebration', t: '[ˌsɛlɪˈbreɪʃən]', ru: 'Мероприятие', ua: 'Захід' },
    {
        en: 'physician',
        t: '[fɪˈzɪʃən]',
        ru: 'Врач, доктор, терапевт',
        ua: 'Лікар, лікар, терапевт',
    },
    { en: 'treatment', t: '[ˈtriːtmənt]', ru: 'Лечение', ua: 'Лікування' },
    {
        en: 'improvement',
        t: '[ɪmˈpruːvmənt]',
        ru: 'Улучшение',
        ua: 'Поліпшення',
    },
    { en: 'symptom', t: '[ˈsɪmptəm]', ru: 'Симптом', ua: 'Симптом' },
    { en: 'dismay', t: '[dɪsˈmeɪ]', ru: 'Огорчение', ua: 'Смуток' },
    {
        en: 'cancellation',
        t: '[ˌkænsəˈleɪʃən]',
        ru: 'Отмена',
        ua: 'Скасування',
    },
    {
        en: 'suspiciousness',
        t: '[səsˈpɪʃəsnəs]',
        ru: 'Подозрительность',
        ua: 'Підозірливість',
    },
    {
        en: 'escalation',
        t: '[ˌɛskəˈleɪʃən]',
        ru: 'Обострение, эскалация',
        ua: 'Загострення, ескалація',
    },
    {
        en: 'proceeding',
        t: '[prəˈsiːdɪŋ]',
        ru: 'Разбирательство',
        ua: 'Розбірництво',
    },
    { en: 'awareness', t: '[əˈweənəs]', ru: 'Осознание', ua: 'Свідомість' },
    {
        en: 'responsibility',
        t: '[rɪsˌpɒnsəˈbɪlɪti]',
        ru: 'Ответственность',
        ua: 'Відповідальність',
    },
    { en: 'aftermath', t: '[ˈɑːftəmæθ]', ru: 'Последствие', ua: 'Наслідок' },
    { en: 'weakness', t: '[ˈwiːknɪs]', ru: 'Слабость', ua: 'Слабкість' },
    {
        en: 'rivalry',
        t: '[raɪvəlri]',
        ru: 'Соперничество, противостояние',
        ua: 'Суперництво, протистояння',
    },
    {
        en: 'restlessness',
        t: '[ˈrɛstlɪsnɪs]',
        ru: 'Беспокойство',
        ua: 'Занепокоєння',
    },
    {
        en: 'uncertainty',
        t: '[ʌnˈsɜːtnti]',
        ru: 'Неуверенность, неопределенность',
        ua: 'Невпевненість, невизначеність',
    },
    {
        en: 'stress resistance',
        t: '[strɛs rɪˈzɪstəns]',
        ru: 'Стрессоустойчивость',
        ua: 'Стресостійкість',
    },
    { en: 'conscience', t: '[kɒnʃəns]', ru: 'Совесть', ua: 'Совість' },
    {
        en: 'А mindfulness',
        t: '[ˈmaɪndfʊlnəs]',
        ru: 'Внимательность, мышление, осознанность',
        ua: 'Уважність, мислення, усвідомленість',
    },
    {
        en: 'protection',
        t: '[prəˈtɛkʃən]',
        ru: 'Защита, протекция',
        ua: 'Захист, протекція',
    },
    { en: 'referral', t: '[rɪˈfɜrəl]', ru: 'Направление', ua: 'Напрям' },
    {
        en: 'hopelessness',
        t: '[ˈhəʊplɪsnɪs]',
        ru: 'Безнадежность',
        ua: 'Безнадійність',
    },
    {
        en: 'reliability',
        t: '[rɪˌlaɪəˈbɪlɪti]',
        ru: 'Надежность',
        ua: 'Надійність',
    },
    {
        en: 'verification',
        t: '[ˌvɛrɪfɪˈkeɪʃən]',
        ru: 'Проверка',
        ua: 'Перевірка',
    },
    {
        en: 'self-isolation',
        t: '[sɛlf-ˌaɪsəʊˈleɪʃən]',
        ru: 'Самоизоляция',
        ua: 'Самоізоляція',
    },
    {
        en: 'А provocation',
        t: '[prɒvəˈkeɪʃən]',
        ru: 'Провокация',
        ua: 'Провокація',
    },
    {
        en: 'prevention',
        t: '[prɪˈvɛnʃən]',
        ru: 'Профилактика',
        ua: 'Профілактика',
    },
    {
        en: 'side effect',
        t: '[saɪd ɪˈfɛkt]',
        ru: 'Побочный эффект',
        ua: 'Побічний ефект',
    },
    {
        en: 'vaccination',
        t: '[ˌvæksɪˈneɪʃən]',
        ru: 'Вакцинация',
        ua: 'Вакцинація',
    },
    {
        en: 'immunization',
        t: '[ ɪˌmju(ː)naɪˈzeɪʃən]',
        ru: 'Иммунизация',
        ua: 'Імунізація',
    },
    {
        en: 'contradiction',
        t: '[ˌkɒntrəˈdɪkʃən]',
        ru: 'Противоречие',
        ua: 'Протиріччя',
    },
    { en: 'emotion', t: '[ ɪˈməʊʃən]', ru: 'Эмоция', ua: 'Емоція' },
    {
        en: 'disagreement',
        t: '[ˌdɪsəˈgriːmənt]',
        ru: 'Разногласие',
        ua: 'Розбіжність',
    },
    {
        en: 'misunderstanding',
        t: '[ ˌmɪsʌndəˈstændɪŋ]',
        ru: 'Недоразумение, недопонимание',
        ua: 'Непорозуміння, непорозуміння',
    },
    {
        en: 'negotiation',
        t: '[nɪˌgəʊʃɪˈeɪʃən]',
        ru: 'Переговоры',
        ua: 'Переговори',
    },
]

export default words
