const words = [
    { en: 'distancing', t: '[ˈdɪstənsɪŋ]', ru: 'Дистанцирование' },
    { en: 'isolation', t: '[ˌaɪsəʊˈleɪʃən]', ru: 'Изоляция' },
    { en: 'self-care', t: '[sɛlf-keə]', ru: 'Забота о себе' },
    { en: 'medication', t: '[ˌmɛdɪˈkeɪʃən]', ru: 'Лекарство' },
    { en: 'celebration', t: '[ˌsɛlɪˈbreɪʃən]', ru: 'Мероприятие' },
    { en: 'physician', t: '[fɪˈzɪʃən]', ru: 'Врач, доктор, терапевт' },
    { en: 'treatment', t: '[ˈtriːtmənt]', ru: 'Лечение' },
    { en: 'improvement', t: '[ɪmˈpruːvmənt]', ru: 'Улучшение' },
    { en: 'symptom', t: '[ˈsɪmptəm]', ru: 'Симптом' },
    { en: 'dismay', t: '[dɪsˈmeɪ]', ru: 'Огорчение' },
    { en: 'cancellation', t: '[ˌkænsəˈleɪʃən]', ru: 'Отмена' },
    { en: 'suspiciousness', t: '[səsˈpɪʃəsnəs]', ru: 'Подозрительность' },
    { en: 'escalation', t: '[ˌɛskəˈleɪʃən]', ru: 'Обострение, эскалация' },
    { en: 'proceeding', t: '[prəˈsiːdɪŋ]', ru: 'Разбирательство' },
    { en: 'awareness', t: '[əˈweənəs]', ru: 'Осознание' },
    { en: 'responsibility', t: '[rɪsˌpɒnsəˈbɪlɪti]', ru: 'Ответственность' },
    { en: 'aftermath', t: '[ˈɑːftəmæθ]', ru: 'Последствие' },
    { en: 'weakness', t: '[ˈwiːknɪs]', ru: 'Слабость' },
    { en: 'rivalry', t: '[raɪvəlri]', ru: 'Соперничество, противостояние' },
    { en: 'restlessness', t: '[ˈrɛstlɪsnɪs]', ru: 'Беспокойство' },
    {
        en: 'uncertainty',
        t: '[ʌnˈsɜːtnti]',
        ru: 'Неуверенность, неопределенность',
    },
    {
        en: 'stress resistance',
        t: '[strɛs rɪˈzɪstəns]',
        ru: 'Стрессоустойчивость',
    },
    { en: 'conscience', t: '[kɒnʃəns]', ru: 'Совесть' },
    {
        en: 'А mindfulness',
        t: '[ˈmaɪndfʊlnəs]',
        ru: 'Внимательность, мышление, осознанность',
    },
    { en: 'protection', t: '[prəˈtɛkʃən]', ru: 'Защита, протекция' },
    { en: 'referral', t: '[rɪˈfɜrəl]', ru: 'Направление' },
    { en: 'hopelessness', t: '[ˈhəʊplɪsnɪs]', ru: 'Безнадежность' },
    { en: 'reliability', t: '[rɪˌlaɪəˈbɪlɪti]', ru: 'Надежность' },
    { en: 'verification', t: '[ˌvɛrɪfɪˈkeɪʃən]', ru: 'Проверка' },
    { en: 'self-isolation', t: '[sɛlf-ˌaɪsəʊˈleɪʃən]', ru: 'Самоизоляция' },
    { en: 'А provocation', t: '[prɒvəˈkeɪʃən]', ru: 'Провокация' },
    { en: 'prevention', t: '[prɪˈvɛnʃən]', ru: 'Профилактика' },
    { en: 'side effect', t: '[saɪd ɪˈfɛkt]', ru: 'Побочный эффект' },
    { en: 'vaccination', t: '[ˌvæksɪˈneɪʃən]', ru: 'Вакцинация' },
    { en: 'immunization', t: '[ ɪˌmju(ː)naɪˈzeɪʃən]', ru: 'Иммунизация' },
    { en: 'contradiction', t: '[ˌkɒntrəˈdɪkʃən]', ru: 'Противоречие' },
    { en: 'emotion', t: '[ ɪˈməʊʃən]', ru: 'Эмоция' },
    { en: 'disagreement', t: '[ˌdɪsəˈgriːmənt]', ru: 'Разногласие' },
    {
        en: 'misunderstanding',
        t: '[ ˌmɪsʌndəˈstændɪŋ]',
        ru: 'Недоразумение, недопонимание',
    },
    { en: 'negotiation', t: '[nɪˌgəʊʃɪˈeɪʃən]', ru: 'Переговоры' },
]

export default words