const words = [
    {
        en: 'To abolish',
        t: '[əˈbɒlɪʃ]',
        ru: 'Отменять, уничтожать, упразднять',
    },
    { en: 'To approve', t: '[əˈpruːv]', ru: 'Утвердить, одобрить' },
    { en: 'To boast', t: '[bəʊst]', ru: 'Гордиться, хвастаться' },
    {
        en: 'To contribute',
        t: '[kənˈtrɪbju(ː)t]',
        ru: 'Жертвовать, вносить свой вклад',
    },
    {
        en: 'To deliver',
        t: '[dɪˈlɪvə]',
        ru: 'Доставлять, поставлять, приносить',
    },
    { en: 'To descend', t: '[dɪˈsɛnd]', ru: 'Спуститься, сходить, снизойти' },
    { en: 'To concentrate', t: '[ˈkɒnsəntreɪt]', ru: 'Сосредотачиваться' },
    { en: 'To distract', t: '[dɪsˈtrækt]', ru: 'Отвлечь, отвлекать' },
    { en: 'To torture', t: '[ˈtɔːʧə]', ru: 'Мучить, терзать' },
    {
        en: 'To confuse',
        t: '[kənˈfjuːz]',
        ru: 'Путать, запутать, сбить с толку',
    },
    { en: 'To abandon', t: '[əˈbændən]', ru: 'Покинуть, бросить, оставить' },
    {
        en: 'To escape',
        t: '[ɪsˈkeɪp]',
        ru: 'Совершить побег, убежать, сбежать',
    },
    {
        en: 'To distribute',
        t: '[dɪsˈtrɪbju(ː)t]',
        ru: 'Распространять, распределить',
    },
    {
        en: 'To elaborate',
        t: '[ɪˈlæbərɪt]',
        ru: 'Разрабатывать, прорабатывать',
    },
    { en: 'To construct', t: '[kənˈstrʌkt]', ru: 'Строить, построить' },
    { en: 'To humiliate', t: '[hju(ː)ˈmɪlɪeɪt]', ru: 'Унижать' },
    { en: 'To maintain', t: '[meɪnˈteɪn]', ru: 'Поддерживать' },
    { en: 'To squeeze', t: '[skwiːz]', ru: 'Сжимать, выжимать, сжать' },
    { en: 'To delegate', t: '[ˈdɛlɪgɪt]', ru: 'Делегировать, посылать' },
    { en: 'To transfer', t: '[ˈtrænsfə(ː)]', ru: 'Передавать, перечислять' },
    { en: 'To employ', t: '[ɪmˈplɔɪ]', ru: 'Нанимать, использовать, работать' },
    { en: 'To catch', t: '[kæʧ]', ru: 'Поймать, ловить' },
    {
        en: 'To commit',
        t: '[kəˈmɪt]',
        ru: 'Совершить, зафиксировать, поручить',
    },
    { en: 'To arrange', t: '[əˈreɪnʤ]', ru: 'Организовать, устроить' },
    {
        en: 'To implement',
        t: '[ˈɪmplɪmənt]',
        ru: 'Внедрить, реализовать, осуществить',
    },
    { en: 'To insulate', t: '[ˈɪnsjʊleɪt]', ru: 'Ограждать' },
    { en: 'To encourage', t: '[ɪnˈkʌrɪʤ]', ru: 'Стимулировать' },
    { en: 'To foster', t: '[ˈfɒstə]', ru: 'Поощрять' },
    { en: 'To boost', t: '[buːst]', ru: 'Повышать' },
    { en: 'To optimize', t: '[ˈɒptɪmaɪz]', ru: 'Оптимизировать' },
    { en: 'To rank', t: '[ræŋk]', ru: 'Ранжировать' },
    {
        en: 'To identify',
        t: '[aɪˈdɛntɪfaɪ]',
        ru: 'Определить, идентифицировать',
    },
    {
        en: 'To empower',
        t: '[ɪmˈpaʊə]',
        ru: 'Наделить полномочиями, расширять',
    },
    {
        en: 'To ensure',
        t: '[ɪnˈʃʊə]',
        ru: 'Обеспечить, убедить, гарантировать',
    },
    {
        en: 'To accomplish',
        t: '[əˈkɒmplɪʃ]',
        ru: 'Выполнить, завершить, осуществить',
    },
    { en: 'To customize', t: '[ˈkʌstəˌmaɪz]', ru: 'Настроить, сделать' },
    { en: 'To localize', t: '[ˈləʊkəlaɪz]', ru: 'Локализовать, определить' },
    { en: 'To tailor', t: '[ˈteɪlə]', ru: 'Приспособить' },
    { en: 'To validate', t: '[ˈvælɪdeɪt]', ru: 'Удостоверять' },
    { en: 'To reserve', t: '[rɪˈzɜːv]', ru: 'Резервировать' },
    { en: 'To estimate', t: '[ˈɛstɪmɪt]', ru: 'Оценивать' },
    { en: 'To consulate', t: '[ˈkɒnsjʊlɪt]', ru: 'Консультировать' },
    {
        en: 'To regard',
        t: '[rɪˈgɑːd]',
        ru: 'Рассматривать, учитывать, относиться',
    },
    {
        en: 'To indicate',
        t: '[ˈɪndɪkeɪt]',
        ru: 'Указывать, обозначать, показывать',
    },
    { en: 'To unify', t: '[juːnɪfaɪ]', ru: 'Объединять' },
    {
        en: 'To digitalize',
        t: '[ˈdɪdʒɪtəlaɪz]',
        ru: 'Оцифровать, перевести в online-формат',
    },
    { en: 'To expose', t: '[ɪksˈpəʊz]', ru: 'Подвергать' },
    { en: 'To idealize', t: '[ aɪˈdɪəlaɪz]', ru: 'Идеализировать' },
    { en: 'To navigate', t: '[ˈnævɪgeɪt]', ru: 'Ориентироваться' },
    { en: 'To sustain', t: '[səsˈteɪn]', ru: 'Выдерживать' },
    { en: 'To constrain', t: '[kənˈstreɪn]', ru: 'Сдерживать' },
    { en: 'To evade', t: '[ɪˈveɪd]', ru: 'Обойти' },
    { en: 'To purchase', t: '[ˈpɜːʧəs]', ru: 'Приобретать' },
    { en: 'To earn', t: '[ɜːn]', ru: 'Зарабатывать' },
    { en: 'To make sure', t: '[meɪk ʃʊə]', ru: 'Убедиться' },
    { en: 'To prototype', t: '[ˈprəʊtəʊtaɪp]', ru: 'Создать протопит, план' },
    { en: 'To endeavour', t: '[ɪnˈdɛvə]', ru: 'Стремиться' },
    { en: 'To blend', t: '[blɛnd]', ru: 'Смешивать' },
    { en: 'To prioritize', t: '[praɪˈɒrɪˌtaɪz]', ru: 'Расставить приоритеты' },
    { en: 'To mitigate', t: '[ˈmɪtɪgeɪt]', ru: 'Смягчать, принимать' },
    { en: 'To emphasize', t: '[ˈɛmfəsaɪz]', ru: 'Подчеркнуть, придать акцент' },
    { en: 'To observe', t: '[əbˈzɜːv]', ru: 'Наблюдать, замечать' },
    { en: 'To evolve', t: '[ ɪˈvɒlv]', ru: 'Развиваться, расти, проявляться' },
    {
        en: 'To incentivize',
        t: '[ɪnˈsen.tɪ.vaɪz]',
        ru: 'Стимулировать, побуждать',
    },
    { en: 'To respond', t: '[rɪsˈpɒnd]', ru: 'Реагировать, отвечать' },
    { en: 'To connect', t: '[kəˈnɛkt]', ru: 'Соединить' },
    { en: 'To command', t: '[kəˈmɑːnd]', ru: 'Командовать' },
    { en: 'To check-out', t: '[ʧɛk-aʊt]', ru: 'Проверить, оформить' },
    { en: 'To extend', t: '[ɪksˈtɛnd]', ru: 'Продлить, расширить, увеличить' },
    { en: 'To retain', t: '[rɪˈteɪn]', ru: 'Оставить, удержать, сохранить' },
    { en: 'To exhibit', t: '[ɪgˈzɪbɪt]', ru: 'Показывать' },
    { en: 'To invent', t: '[ɪnˈvɛnt]', ru: 'Изобретать' },
    { en: 'To abridge', t: '[əˈbrɪʤ]', ru: 'Ограничивать' },
    { en: 'To self-express', t: '[sɛlf-ɪksˈprɛs]', ru: 'Самовыражаться' },
    { en: 'To neglect', t: '[nɪˈglɛkt]', ru: 'Пренебрегать' },
    {
        en: 'To negotiate',
        t: '[nɪˈgəʊʃɪeɪt]',
        ru: 'Договариваться, вести переговоры',
    },
    { en: 'To upgrade', t: '[ʌpˈgreɪd]', ru: 'Повышать, улучшать' },
    { en: 'To renew', t: '[rɪˈnjuː]', ru: 'Обновить' },
    { en: 'To specialize', t: '[ˈspɛʃəlaɪz]', ru: 'Специализироваться' },
    { en: 'To balance', t: '[ˈbæləns]', ru: 'Уравновешивать' },
    { en: 'To absorb', t: '[əbˈsɔːb]', ru: 'Поглощать' },
    { en: 'To overwhelm', t: '[əʊvəˈwɛlm]', ru: 'Переполнять' },
    { en: 'To align', t: '[əˈlaɪn]', ru: 'Выравнивать' },
    { en: 'To withdraw', t: '[wɪðˈdrɔː]', ru: 'Отстраниться' },
    { en: 'To whistle', t: '[ˈwɪsl]', ru: 'Свистеть' },
    { en: 'To suspect', t: '[ˈsʌspɛkt]', ru: 'Подозревать' },
    { en: 'To surrender', t: '[səˈrɛndə]', ru: 'Сдаваться' },
    { en: 'To depend on', t: '[dɪˈpɛnd ɒn]', ru: 'Зависеть от' },
    { en: 'To correct', t: '[kəˈrɛkt]', ru: 'Исправлять' },
    { en: 'To define', t: '[dɪˈfaɪn]', ru: 'Определить' },
    { en: 'To visualize', t: '[ˈvɪzjʊəlaɪz]', ru: 'Визуализировать' },
    { en: 'To design', t: '[dɪˈzaɪn]', ru: 'Проектировать' },
    { en: 'To minimize', t: '[ˈmɪnɪmaɪz]', ru: 'Минимизировать' },
    { en: 'To disturb', t: '[dɪsˈtɜːb]', ru: 'Нарушить, беспокоить' },
    { en: 'To integrate', t: '[ˈɪntɪgreɪt]', ru: 'Интегрировать' },
    { en: 'To exchange', t: '[ɪksˈʧeɪnʤ]', ru: 'Обменивать, менять' },
    { en: 'To organize', t: '[ˈɔːgənaɪz]', ru: 'Организовать' },
    { en: 'To collaborate', t: '[kəˈlæbəreɪt]', ru: 'Сотрудничать' },
    { en: 'To embed', t: '[ɪmˈbɛd]', ru: 'Встраивать' },
    { en: 'To generate', t: '[ˈʤɛnəreɪt]', ru: 'Генерировать' },
]

export default words
