const words = [
    { en: 'addiction', t: '[əˈdɪkʃ(ə)n]', ru: 'Зависимость, пристрастие' },
    { en: 'amateur', t: '[ˈæmətə(ː)]', ru: 'Любитель' },
    { en: 'ambivalence', t: '[æmˈbɪvələns]', ru: 'Нерешительность' },
    { en: 'commission', t: '[kəˈmɪʃən]', ru: 'Комиссия, поручение, заказчик' },
    {
        en: 'confidence',
        t: '[ˈkɒnfɪdəns]',
        ru: 'Доверие, уверенность, достоверность',
    },
    { en: 'craving', t: '[ˈkreɪvɪŋ]', ru: 'Желание, тяга, стремление, жажда' },
    { en: 'district', t: '[ˈdɪstrɪkt]', ru: 'Район' },
    { en: 'evidence', t: '[ˈɛvɪdəns]', ru: 'Доказательство, признак, факт' },
    { en: 'honesty', t: '[ˈɒnɪsti]', ru: 'Честность' },
    {
        en: 'circumstance',
        t: '[ˈsɜːkəmstəns]',
        ru: 'Обстоятельство, случай, событие',
    },
    { en: 'kindness', t: '[ˈkaɪndnɪs]', ru: 'Доброта' },
    { en: 'justice', t: '[ˈʤʌstɪs]', ru: 'Справедливость' },
    { en: 'disgust', t: '[dɪsˈgʌst]', ru: 'Отвращение, брезгливость' },
    { en: 'А suggestion', t: '[səˈʤɛsʧən]', ru: 'Предложение, суждение, идея' },
    { en: 'А nobility', t: '[nəʊˈbɪlɪti]', ru: 'Благородство, достоинство' },
    { en: 'commotion', t: '[kəˈməʊʃən]', ru: 'Суета' },
    { en: 'adherence', t: '[ədˈhɪərəns]', ru: 'Приверженность' },
    { en: 'devotion', t: '[dɪˈvəʊʃən]', ru: 'Преданность' },
    {
        en: 'enticement',
        t: '[ ɪnˈtaɪsmənt]',
        ru: 'Приманка, соблазн, заманивание',
    },
    { en: 'attractiveness', t: '[ əˈtræktɪvnəs]', ru: 'Привлекательность' },
    { en: 'freedom-loving', t: '[ˈfriːdəm-ˈlʌvɪŋ]', ru: 'Свободолюбие' },
    { en: 'rebel', t: '[ˈrɛbl]', ru: 'Бунтарь' },
    { en: 'influence', t: '[ ˈɪnflʊəns]', ru: 'Влияние' },
    { en: 'sway', t: '[sweɪ]', ru: 'Колебание' },
    { en: 'willpower', t: '[ˈwɪlˌpaʊə]', ru: 'Сила воли' },
    { en: 'inequality', t: '[ˌɪni(ː)ˈkwɒlɪti]', ru: 'Неравенство' },
    { en: 'А violence', t: '[ˈvaɪələns]', ru: 'Насилие, жестокость' },
    { en: 'А bullying', t: '[ˈbʊliɪŋ]', ru: 'Издевательство, травля' },
    { en: 'А godliness', t: '[ˈgɒdlɪnɪs]', ru: 'Благочестие, бодрость' },
    { en: 'А compassion', t: '[kəmˈpæʃən]', ru: 'Сострадание' },
    { en: 'inclusivity', t: '[ɪnˌkluːˈsɪvətɪ]', ru: 'Инклюзивность' },
    { en: 'А reciprocity', t: '[rɛsɪˈprɒsɪti]', ru: 'Взаимность, обоюдность' },
    {
        en: 'friskiness',
        t: '[ˈfrɪskɪnəs]',
        ru: 'Игривость, раскованность, живость',
    },
    { en: 'fervor', t: '[ˈfɜːvə]', ru: 'Пылкость, задор, рвение' },
    { en: 'А youth', t: '[juːθ]', ru: 'Молодежь, юноша, молодость' },
    {
        en: 'adolescence',
        t: '[ædəʊˈlɛsns]',
        ru: 'Подростковый возраст, отрочество',
    },
    { en: 'А prerequisite', t: '[ˌpriːˈrɛkwɪzɪt]', ru: 'Предпосылка, условие' },
    { en: 'fortune', t: '[ˈfɔːʧən]', ru: 'Судьба, удача, желание, успех' },
    { en: 'А Stubbornness', t: '[ˈstʌbənnɪs]', ru: 'Упрямость' },
    { en: 'disappointment', t: '[dɪsəˈpɔɪntmənt]', ru: 'Разочарование' },
]

export default words